- .github/CONTRIBUTING.rst
- README.md
The current README is a bit of a boilerplate, so I'm updating it to the general style of the Qiskit project.
In addition, I struggled with building from source on Mac. Eventually figured it out with helpful feedback from @atilag. I'm updating the build instructions so that it may be useful to others.
> Update README and build instructions on Mac

- .github/CONTRIBUTING.rst
Following the instructions, there was a dash missing. 
A prompt was not on one of the install lines and since requirements were inline I missed it the first time.  
Personally, I would rethink your headings as I don’t know why the using cmake files needs a higher level than the build. 
In Terra, we rearranged to be the following headings. 
Contributing, Installing Code, Documentation, and Development cycle. 
But it builds and works for me now :-).
> Edits to contributing

- qiskit/providers/aer/aerjob.py
- src/base/controller.hpp
Fixes #16 and fixes #10
* Adds `qobj` method to `AerJob` class that returns the submitted/run qobj.
* Fixes the missing definition for `num_threads_circuit` outside the `#ifdef _OPENMP` block so that single threaded execution works when building the simulators without OpenMP.
> Fix non OpenMP build, add qobj method to AerJob

- test/terra/test_noise_model.py
Travis tests are failing due to typo in the test file (tests for error on the `reset` operation were putting the error on the `measure` operation). 
Also increases counts for noise tests from 1000 to 2000.
> Fix failing travis tests

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- src/framework/data.hpp
Checks if the maximum number of qubits in a qobj fits in available system memory for a given Aer backend. If not it raises an exception before execution.
* Backend validation checks number of qubits can fit in available memory before execution.  This Fixes #6 which was causing a broken process pool when the simulator attempted to run a simulation that was too large for available memory.
* Adds missing 'url' to Aer backend configuration
* Adds warnings for QasmSimulator if circuit contains no classical registers, or no measurements (same as BasicAer).
* Changes simulator to return `"data": {}` instead of `"data": null` as required by schema if simulator produces no result data. 
**Note:** We should also add memory checks on the C++ side, since these will be needed by the QasmSimulator in …
> Validate n_qubits before execution

- MANIFEST.in
- setup.py
Better error checking at install time.
If the user doesn't have scikit-build installed, it will show a message encouraging them to install it.
> Improve error reporting if scikit-build is not preinstalled in the system at install time.

- .github/CONTRIBUTING.rst
- test/terra/utils/common.py
Fixed a couple documentation errors I encountered when building.
Fixed a bad dash character and added cmake flags for installing the terra-integrated tests.
> Issue #32: Documentation fixes in CONTRIBUTING and fix import in terra-integrated tests

- qiskit/providers/aer/__init__.py
- qiskit/providers/aer/noise/__init__.py
- qiskit/providers/aer/noise/errors/__init__.py
- qiskit/providers/aer/noise/errors/standard_errors.py
- test/terra/test_noise_model.py
Adds `reset_error` function to the standard errors noise module.
This allows a user to build a single-qubit reset error without having to deal with making a QobInstruction input.
> add reset_error to noise module

- setup.py
As proposed in issue #40, we should add the Qiskit AER's homepage URL to the `setup.py` file. This info is shown as part of the installation details when using commands like `pip show qiskit-aer` and this is the only common Qiskit package that lacks it.
> Adding homepage URL to Qiskit AER setup.py

- src/simulators/stabilizer/clifford.hpp
A small change in deserialization from json in Clifford
Copying a `std::string` object from a string array of `json_t` causes a compilation error in some compilers. This PR changes to extract a `std::string` object from `std::vector<std::string>` instead of a string array of `json_t`.
> use vector<string> in json deserialization for clifford

- qiskit/providers/aer/noise/device/models.py
I fixed UnboundedLocalError in basic_device_noise_model.
In `noise.device.basic_device_noise_model`, if `thermal_relaxation=False`, an error　`UnboundLocalError: local variable 'relax_params' referenced before assignment` occurred at
[line 185](https://github.com/Qiskit/qiskit-aer/blob/master/qiskit/providers/aer/noise/device/models.py#L185). This is because `relax_params` is not declared. This is just a workaround and tests should be added later.
> Fix UnboundedLocalError in basic_device_noise_model

- contrib/standalone/qasm_simulator.cpp
> Fix segfault on Mac OS when running the standalone qasm_simulator.

- contrib/standalone/qasm_simulator.cpp
- src/base/state.hpp
- src/misc/clang_omp_symbols.hpp
- src/misc/gcc_omp_symbols.hpp
- src/simulators/stabilizer/binary_vector.hpp
- src/simulators/stabilizer/clifford.hpp
- src/simulators/stabilizer/pauli.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_state.hpp
- src/simulators/unitary/unitarymatrix.hpp
* Fixes some pedantic compiler warnings for missing declarations and comparisons of signed to unsigned intergers.
* Changes State::allowed_ops to use the previously defined type alias
> Fix compiler warnings

- test/terra/test_statevector_simulator.py
- test/terra/test_unitary_simulator.py
- test/terra/utils/qasm_simulator/qasm_extra.py
Disable tests failing to Terra qobj changes until they can be fixed in Terra.
When updating these should be changed to use the new unitary circuit instruction being worked on in terra PR 1961
> Disable unitary instruction tests until terra fix

- src/framework/operations.hpp
Adds parsing of "initialize" qobj instruction for Issue #82 
This parses a qobj instruction of the form:
```
{"name": "initialize", "qubits": qs, "params": psi}
```
where `qs` is a list of qubits eg `[a, b, c]`, and psi is a (JSON) complex vector corresponding to tensor product order `psi[c] \otimes psi[b] \otimes psi[a]`
> Add parsing of "initialize" qobj instruction

- src/simulators/ch/ch_runner.hpp
This resolve #91 .
Explicitly convert from `json_t` to `std::string`.
```
serialized_states[i] = serialize_state(i).dump();
```
> convert explicitly from json_t to std::string in CHSimulator::Runner

- src/simulators/qasm/qasm_controller.hpp
- src/simulators/statevector/statevector_controller.hpp
- src/simulators/statevector/statevector_state.hpp
Current `AER::Simulator::QasmController` cannot change its `statevec_t` class in `AER::Statevector::State` because `AER::Statevector::State` explicitly specifies `QV::QubitVector` as `statevec_t` in its class definition.
This PR changes`AER::Statevector::State` not to specify `statevec_t` and `AER::Simulator::QasmController` specifies `QV::QubitVector` in `run_circuit()`.
Originally, `AER::Statevector::State` explicitly specifies `QV::QubitVector` as `statevec_t` in its class definition.
```
template <class data_t = complex_t*>
class State : public Base::State<QV::QubitVector<data_t>> {
public:
using BaseState = Base::State<QV::QubitVector<data_t>>;
```
This PR changes`AER::Statevector::State` not to specify `statevec_t`.
```
template <class statevec_t>
class State : public …
```
> allow various qubit vector classes in qasm controller

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
fixes #87 
The specification says that all backends must have a `coupling_map`.  This PR makes Aer backends inline with the spec.
> Add coupling_map to backends

- src/framework/operations.hpp
- src/simulators/ch/ch_state.hpp
- test/terra/test_ch_simulator.py
Fixes a GCC-5 bug where `std::unordered_set` doesn't work with `enum class` objects unless an explicit hash table is provided.
> fix unordered_set enum class for gcc5

- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- test/terra/test_ch_simulator.py
`qiskit._util` was renamed with `qiskit.util`
`qiskit._util` was renamed with `qiskit.util` in https://github.com/Qiskit/qiskit-terra/pull/2013.
`aerbackend.py` and `*_simulator.py` are using `qiskit._util`.
> use qiskit.util instead of qiskit._util

- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/noise/errors/quantum_error.py
- qiskit/providers/aer/utils/qobj_utils.py
Rename `qiskit.qobj` Qobj classes to the new QasmQobj classes so  the Qobj validator god is happy again.
> Migrating `Qobj` to the new `QasmQobj`

- src/misc/clang_omp_symbols.hpp
- src/misc/gcc_omp_symbols.hpp
We changed some functions behavior by adding `inline` in order to avoid warnings message, but this had side effects and the MacOS builds with GCC where failing at runtime with `unresolved symbols`.
I have modified the clang related files as well for consistency, even though building with clang seemed to work fine (maybe this side effect was not happening due to the way the compiler treats symbols or inlines).
> Fix MacOS unresolved symbols at runtime with GCC

- qiskit/providers/aer/aerjob.py
The `AerJob` previously used `ProcessPoolExecutor` on linux and `ThreadPoolExecutor` on MacOS and Windows. Since we handle all parallelization in Aer on the C++ code side this changes the `AerJob` to use `ThreadPoolExecutor` on all OSes.
> use ThreadPoolExecutor for all systems

- src/simulators/statevector/qubitvector.hpp
This PR improves singel-qubit phase operation in statevector.
`AER::Statevector::apply_gate_phase` calls `AER::Statevector::apply_matrix(reg_t, cvector_t)`, which calls `QV::QubitVector::apply_diagonal_matrix(reg_t, cvector_t)`.
However, `apply_diagonal_matrix(uint_t, cvector_t)` is much better than `apply_diagonal_matrix(reg_t, cvector_t)`.
This PR bridges the both.
> imporve u1 performance in statevector

- src/simulators/statevector/qubitvector.hpp
Adds several fixes to `QubitVector` class:
* `apply_matrix` checks if matrix is single-qubit and if so uses optimized function
* single qubit `apply_matrix` checks if matrix is diagonal and if so uses optimized function
* fixes bug in `apply_matrix2` using row-major order instead of col-major order for matrix
* fixes indexes of lambda function to be const ref instead of copy (which is bad for the unique pointer objects returned by the indexes function and only worked when it could use move-semantics).
> Fixes in qubitvector

- contrib/standalone/qasm_simulator.cpp
Adds additional exit codes to standalone QasmSimulator. Closes #86 @sdague.
EXIT CODES: 
* 0: The Qobj was succesfully executed. Returns full result JSON.
* 1: Command line invalid or Qobj JSON cannot be loaded.  Returns JSON: `{"success": false, "status": "ERROR: Invalid input (error msg)"}`
* 2: Qobj failed to load or execute. Returns JSON: `{"success": false, "status": "ERROR: Failed to execute qobj (error msg)"}`
* 3: At least one experiment in Qobj failed to execute successfully. Returns parial result JSON with failed experiments returning: `{"success": false, "status": "ERROR: error msg"}`
> Add multiple exit codes for standalone simulator

- qiskit/providers/aer/noise/device/models.py
Closes #130 
Adds `gate_error` kwarg to `basic_device_noise_model` that allows ignoring the reported `gate_error` parameter from backend properties so that gate errors will be completely determined by the thermal relaxation parameters (T1, T2, gate time etc).
> Add ability to disable depolarizing error on device noise model

- CHANGELOG.rst
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_state.hpp
Adds support for multi-controller x,y,z,u1,u2,u3 gates to the statevector QasmSimulator, StatevectorSimulator and UnitarySimulator.
These gates have an optimized implementation making them faster to execute than the gate being unrolled into a basis of `cx` and single qubit gates.
Closes #127 
These gates are passed in as (N+1)-qubit qobj instructions such as:
```python
{"name": "mcx", "qubits": [c0, c1,...,cn, target]}
```
where the first `N` qubits are the controls, and the last qubit is the target.
For the controlled `u1,u2,u3` gates the instruction includes the same parameters as for the single qubit gates. Eg:
```python
{"name": "mcu3", "qubits": [c0, c1,...,cn, target], "params": [theta, phi, lam]}
```
TODO:
> Add support for optimized multi-controlled gates

- CMakeLists.txt
- src/third-party/win64/lib/LICENSE
Adds static OpenBLAS library compiled by us for using with Windows builds.
By statically linking OpenBLAS we can create binaries that are more likely to run on every Windows environment, because there's no need for the user to install OpenBLAS as a depedency.
> Improve windows build

- .gitignore
- qiskit/providers/aer/noise/errors/errorutils.py
- qiskit/providers/aer/noise/errors/quantum_error.py
- qiskit/providers/aer/noise/errors/readout_error.py
- test/terra/test_quantum_error.py
* Adds `to_channel` method to `QuantumError` object that can convert quantum errors to `SuperOp` quantum channel objects.
* Fixes bug in `QuantumError.tensor` and `QuantumError.expand`
* Removes `inplace` kwargs from methods in `QuantumError` and `ReadoutError`
> Add to_channel method to QuantumError

- src/simulators/statevector/qubitvector.hpp
`QubitVector<data_t>::probabilities(const reg_t &qubits)` does not have an OMP directive.
This PR adds `omp parallel` to a loop in `QubitVector<data_t>::probabilities(const reg_t &qubits)`.
> add omp to probabilities in qubitvector

- CHANGELOG.rst
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_state.hpp
* add controlled swap gate (Closes #128)
* remove apply_x/y/z and add them as N=1 case of apply_mcx/y/z
* add N=1-4 cases of static indexing to apply_matrix and apply_diagonal_matrix
* rename apply_matrix_lambda to apply_lambda and template parameter and make the type of the last param (previously matrix) a template parameter.
* rename apply_matrix_reduction_lambda to apply_reduction_lambda and make the type of the last param (previously matrix) a template parameter.
* remove single-qubit apply_reduction_lambda
> Add controlled-swap and update static indexing in qubitvector

- src/simulators/qasm/qasm_controller.hpp
Update to use sample measurement function when shot is 1 and no noise. 
Simulation time changes from 25 sec to 5 sec for QV (25qubit/10depth/1shot).
- remove `shots == 1` case in `run_circuit_without_noise ()`
> Use sample measurement when shot is 1 and without noise

- qiskit/providers/aer/noise/errors/errorutils.py
This extends `errorutils.standard_gate_instruction` to convert single-qubit reset Kraus operations to standard qobj reset instructions.
Example: 
kraus reset to 0 or 1:
```python
reset0 = {'name': 'kraus', 'qubits': [0], 'params': [array([[1, 0], [0, 0]]), array([[0, 1], [0, 0]])]}
reset1 =  {'name': 'kraus', 'qubits': [0], 'params': [array([[0, 0], [0, 1]]), array([[0, 0], [1, 0]])]}
```
Then the modified instruction can convert these as:
```
standard_gate_instruction(reset0) -> [{'name': 'reset', 'qubits': [0]}]
standard_gate_instruction(reset1) -> [{'name': 'reset', 'qubits': [0]}, {'name': 'x', 'qubits': [0]}]
```
Note that the comparison is done using the `SuperOp` representation so any Kraus representation equivalent to the reset will be converted, not just the canonical ones.
> Add reset to standard_gate_instruction

- qiskit/providers/aer/backends/wrappers/CMakeLists.txt
Similar to what we have fixed in PR #144 but seems like GCC and Clang disagrees in how to behave for `-flat_namepsace` on MacOS. So I only need to set this flag on GCC but not in Clang, because if I set this in Clang, the the loader loads the symbol from the first loaded library (exactly the same as if I don't set this flag in GCC)... :(
> Fix symbol resolution misbehaior for GCC and Clang on MacOS

- qiskit/providers/aer/noise/errors/errorutils.py
- qiskit/providers/aer/noise/errors/quantum_error.py
- test/terra/noise/test_quantum_error.py
Changes `expand` `tensor` and `compose` of `QuantumError` to combine operations if they contain kraus or unitary qobj instructions. This reduces the number of operations in the composite error objects which should help slightly improve noisy simulation by reducing the number of operations to be executed.
Previously when combining errors the instructions were appended with minimal reduction.
Eg:
```python
error1 = noise.errors.amplitude_damping_error(0.2)
error2 = noise.errors.pauli_error([('X', 0.5), ('I', 0.5)])
error = error1.compose(error2)
print(error._noise_probabilities)
print(error._noise_circuits)
[0.5, 0.5]
[[{'name': 'kraus',
'qubits': [0],
'params': [array([[0.       +0.j, 0.4472136+0.j],
[0.       +0.j, 0.       +0.j]]),
array([[1.        +0.j, 0.        +0.j],
[0. …
```
> optimize compose and tensor of QuantumError

- qiskit/providers/aer/noise/errors/errorutils.py
- qiskit/providers/aer/noise/errors/quantum_error.py
- qiskit/providers/aer/utils/qobj_utils.py
- src/framework/operations.hpp
- src/noise/noise_model.hpp
- src/noise/quantum_error.hpp
- test/terra/backends/qasm_simulator/qasm_extra.py
- test/terra/backends/qasm_simulator/qasm_thread_management.py
- test/terra/backends/test_statevector_simulator.py
- test/terra/backends/test_unitary_simulator.py
- test/terra/noise/test_quantum_error.py
- test/terra/noise/test_standard_errors.py
* Changes snapshot instructions to pass in `"type"` as `"snapshot_type"`, but for now maintains backwards compatibility with instructions that still use `"type"`. This backwards compatibility will be removed in Aer 0.3.
* Changes the unitary qobj instruction format to pass in the matrix as `"param": [mat]` rather than `"params": mat` (which unfortunately was baked into a lot of noise module files and could do with some proper refactoring in the future!).
Should be merged in sync with Terra PR [2164](https://github.com/Qiskit/qiskit-terra/pull/2164)
> change format of unitary qobj params

- src/framework/operations.hpp
Fixes new snapshot field `"snapshot_type"` being parsed in the wrong location when parsing qobj.
> fix snapshot_type not being parsed

- src/base/controller.hpp
- src/simulators/statevector/qubitvector.hpp
Fix a bug in controller to parallelize shots.
The first loop in `json_t Controller::execute_circuit(Circuit &circ)` is not necessary.
```
for (int i = 0; i < parallel_shots_; ++i)
#pragma omp parallel for if (parallel_shots_ > 1) num_threads(parallel_shots_)
for (int j = 0; j < parallel_shots_; j++) {
try {
data[j] = run_circuit(circ, subshots[j], circ.seed + j);
} catch (std::runtime_error error) {
error_msgs[j] = error.what();
}
}
```
> Reduce unnecessary loop for shot-level parallelization

- CHANGELOG.rst
- qiskit/providers/aer/noise/noise_model.py
This PR adds an optional parameter to `NoiseModel.as_dict()` for returning a "dict composed only of types that can be serialized directly using `json.dumps()` without the need for a custom encoder". It is mostly for the needs of `IBMQProvider` - since online simulators can also accept noise models, it allows the serialization to be contained within `Aer` without requiring extra imports or duplication in the other provider.
I went with an approach that hopefully minimizes the impact of this change - by default, the parameter is set to `False` for preserving current behaviour, and relies on the existing AerJSONEncoder` doing a dummy "dump -> load" cycle.
> Allow NoiseModel.as_dict() to return a serializable dict

- test/benchmark/tools.py
Removes the dependency on the Unitary object class from Terra and instead uses the two_qubit_kak function directly to synthesis a 2-qubit unitary in terms of u3 and cx.
Removes dependence of `Unitary` object from quantum volume benchmark circuits as this will likely be renamed/changed in a future Terra PR.
Fixes the quantum volume circuit to use the `two_qubit_kak` decomposition directly to add a random SU4 in terms of `u3` and `cx` gates.
> Remove unitary instruction from quantum volume

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/noise/device/models.py
- test/benchmark/tools.py
Add kraus instruction to QasmSimulator basis gates since it is already supported and will be added to Terra soon.
Adds `kraus` to the `QasmSimulator` basis gates, so that a valid kasm QasmQobjInstruction can be directly simulated from qobj circuit.
The `kraus` qobj format is `{"name": "kraus", "qubits": [q0, q1, ...], "params": [K0, K1, ...]}` where `Kj` are the serialized Kraus matrices of the correct dimension for the number of qubits specified.
```python
import numpy as np
from qiskit import *
from qiskit.providers.aer import QasmSimulator
from qiskit.qobj import QasmQobjInstruction
p = 0.25
kraus = [np.sqrt(p) * np.array([[0, 1], [1, 0]]),
np.sqrt(1-p) * np.eye(2)]
kraus_instr = QasmQobjInstruction(name='kraus',
qubits=[0],
params=kraus)
qr = QuantumRegister(1)
cr = …
```
> adds kraus to QasmSimulator basis_gates

- src/simulators/statevector/qubitvector.hpp
Adds switch statement for static indexing to `QubitVector::norm`. This function is used in the application of Kraus noise and was the cause of recent performance degradation when static indexing was removed.
> Add static indexing to qubitvector norm

- src/simulators/statevector/qubitvector.hpp
Right now in the statevector simulator there were a few for loops that
were using size_t as the loop iterator type. However the type there
should int_t so it's signed. This commit just fixes this issue and
switches the type.
> Fix type on loop iterators in openmp for loops

- CHANGELOG.rst
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
- src/simulators/qasm/qasm_controller.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/statevector_controller.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_controller.hpp
- src/simulators/unitary/unitary_state.hpp
- test/benchmark/quantum_volume_benchmarks.py
- test/benchmark/simple_benchmarks.py
- test/benchmarks/parallelization_test.py
- test/terra/backends/qasm_simulator/qasm_algorithms.py
- test/terra/backends/qasm_simulator/qasm_basics.py
- test/terra/backends/qasm_simulator/qasm_cliffords.py
- test/terra/backends/qasm_simulator/qasm_conditional.py
- test/terra/backends/qasm_simulator/qasm_fusion.py
- test/terra/backends/qasm_simulator/qasm_initialize.py
- test/terra/backends/qasm_simulator/qasm_measure.py
- test/terra/backends/qasm_simulator/qasm_method.py
- test/terra/backends/qasm_simulator/qasm_noncliffords.py
- test/terra/backends/qasm_simulator/qasm_reset.py
- test/terra/backends/qasm_simulator/qasm_thread_management.py
- test/terra/backends/test_qasm_extended_stabilizer_simulator.py
- test/terra/noise/test_noise_model.py
- test/terra/reference/ref_measure.py
- test/terra/reference/ref_unitary_gate.py
* Cleans up some backend options documentation and names
* Updates test to use execute or transpile/assemble instead of compile to remove depreciation warnings
* Closes #157 by changing extended stabilizer measure sampling option to value `"extended_stabilizer_measure_sampling"` with default value of `False` instead of `True`.
* Renames `"chop_threshold"` option to `"zero_threshold"` and changes default value from 1e-15 to 1e-10.
* Renames "max_statevector_memory_mb" to "max_memory_mb" in options
* removes depreciated `"ch_..." option parsing for extended stabilizer simulator
* removes `"inital_statevector"` option from documentation since `initialize` circuit instruction should be used now instead.
> Clean up backend options and fix test depreciation warnings

- CHANGELOG.rst
- qiskit/providers/aer/noise/__init__.py
- qiskit/providers/aer/noise/errors/quantum_error.py
- qiskit/providers/aer/noise/errors/readout_error.py
- qiskit/providers/aer/noise/noise_model.py
- qiskit/providers/aer/noise/utils/__init__.py
- qiskit/providers/aer/noise/utils/noise_remapper.py
- qiskit/providers/aer/noise/utils/noise_transformation.py
- test/terra/noise/test_noise_model.py
- test/terra/noise/test_noise_remapper.py
- test/terra/noise/test_noise_transformation.py
- test/terra/noise/test_quantum_error.py
- test/terra/noise/test_readout_error.py
* Adds a qubit reampper utility function for NoiseModels: `remap_noise_model` (generalizes @nonhermitian function in #181)
* Adds `__eq__` method to `NoiseModel`, `QuantumError`, `ReadoutError`
* Cleans up how errors are stored inside noise model so that errors are composed into a single error rather than stored as a list. This should help with simulation efficiency.
* Adds additional noise model tests
> Remap noise model utility function

- src/base/circuitopt.hpp
- src/base/controller.hpp
- src/simulators/qasm/qasm_controller.hpp
- src/transpile/basic_opts.hpp
- src/transpile/circuitopt.hpp
- src/transpile/fusion.hpp
- src/transpile/truncate_qubits.hpp
This expands operations that TruncateQubits circuit optimization works on. It now works for all non-snapshot operations, and a limited set of snapshots (currently probabilities, creg snapshots, and pauli expectation values). In particular this should improve performance of noisy simulations using a device coupling map as previously Kraus errors were not included in the truncation.
Other organisational changes:
* Moves circuitopts into a seperate `transpile` folder in src.
* Seperates Fusion and TruncateQubit optimizations into separate files
> Improve qubit truncation circuit optimization

- appveyor.yml
This will enable Appveor as our Windows CI.
By merging this PR, all Windows tests will run once every PR or commit is pushed.
> Add appveyor for Windows CI support

- qiskit/providers/aer/noise/errors/errorutils.py
- qiskit/providers/aer/noise/errors/standard_errors.py
- qiskit/providers/aer/noise/noise_model.py
Identity is not the same thing as equality in Python.  We want the latter in these instances.
Use ==/!= to compare str, bytes, and int literals.
$ __python__
```python
>>> id = "i"
>>> id += 'd'
>>> id
'id'
>>> id == 'id'
True
>>> id is 'id'
False
>>> 0 == 0.0
True
>>> 0 is 0.0
False
```
> Identity is not the same thing as equality in Python

- CHANGELOG.rst
- qiskit/providers/aer/aererror.py
- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/noise/noiseerror.py
- src/base/controller.hpp
- src/framework/qobj.hpp
- test/terra/backends/qasm_simulator/qasm_fusion.py
- test/terra/backends/qasm_simulator/qasm_truncate.py
- test/terra/utils/mock.py
Changes the simulator to parse the optional RNG seed from the `"seed_simulator"` field in qobj config rather than `"seed"` field. The old `"seed"` field is still parsed for backwards compatibility, but will be overridden by the new field if both are present.
Closes #206
> Use seed_simulator from qobj

- src/base/controller.hpp
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
Resolves issue #204, where Qiskit-Aer wouldn't catch circuits that were too large for the system memory.
The issue was caused by a `size_t` returned from `Aer::Base::State::required_memory_mb` being cast to `int` with value `0`, causing the memory check to pass erroneously.
> Fix for #204, memory checking

- CHANGELOG.rst
- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/noise/errors/errorutils.py
- qiskit/providers/aer/noise/errors/quantum_error.py
- qiskit/providers/aer/noise/errors/readout_error.py
- qiskit/providers/aer/noise/noise_model.py
- qiskit/providers/aer/noise/utils/noise_remapper.py
- qiskit/providers/aer/noise/utils/noise_transformation.py
- qiskit/providers/aer/utils/__init__.py
- qiskit/providers/aer/utils/helpers.py
- test/terra/noise/test_noise_model.py
Fixes: #227
* Removing deprecation warnings from Terra by using to_dict()
* Deprecating our as_dict() methods in favor of to_dict()
We have changed all our as_dict() methods from the API to keep consitency with Terra, as we needed to change `NoiseModel` at least.
I have created a new Python helper class where we can put our global helper functions.
> Remove deprecated warning from Terra and change our as_dict() to to_dict()

- CHANGELOG.md
- qiskit/providers/aer/noise/device/models.py
- qiskit/providers/aer/noise/errors/standard_errors.py
1. Change `depolarizing_error` parameter to allow values greater than 1 if channel is still CPTP
2. Fix basic_device_noise_model to use correct depol param calculation for n-qubit gate with n>1.
3. Truncate depolarizing error param calculated in basic_device_noise_model to max allowed if gate error is too large (Fixes #241)
The error parameter in depolarizing error was interpreted as a probability with maximum value of 1 corresponding to a completely depolarizing channel. This allows larger values than 1 (so no-longer a probability) which return error channels with a reduced identity component, up to a maximum where there is no identity component. Ie for single-qubit the Pauli error `[(X, 1/3), (Y, 1/3), (Z, 1/3)]`.
In `basic_device_noise_model` when `thermal_relaxation=False` the …
> Fix depolarizing error and basic device noise model

- src/base/controller.hpp
Fixes #232 
`#elif` pre-processor conditional were missing the `defined( x )` keyword.
This will fix the problem.
> Issue 232: Fix #elif preprocessor definitions

- CHANGELOG.md
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/noise/errors/readout_error.py
- src/framework/operations.hpp
- test/terra/noise/test_readout_error.py
Adds missing `to_instruction` method to `ReadoutError` object. This allows directly inserting readout errors into a `QuantumCircuit` for simulation in `Aer` like with `QuantumError` objects which can be directly inserted into circuits as `"kraus"` instructions.
Example: 2-qubit readout error
```python
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, execute
from qiskit.providers.aer import QasmSimulator, noise
roerror1 = noise.errors.ReadoutError([[0.9, 0.1], [0.4, 0.6]])
roerror2 = roerror1.tensor(roerror1)
q = QuantumRegister(2, 'q')
c = ClassicalRegister(2, 'c')
qc = QuantumCircuit(q, c)
qc.x(q[1])
qc.measure(q, c)
qc.append(roerror2, cargs=[c[0], c[1]])
result = execute(qc, QasmSimulator(), shots=10000).result()
result.get_counts(0)
```
> Add to_instruction to ReadoutError

- CHANGELOG.md
- qiskit/providers/aer/aerjob.py
To fix #244.
Add max_workers parameter to ThreadPoolExecutor in AerJob. If this value is not set, AerJob creates threads endlessly.
> Set max_workers parameter to ThreadPoolExecutor in AerJob

- azure-pipelines.yml
In the azure pipelines runs for #258 the jobs are failing for what looks
like a mismatch with the installed aer python package and what should
have been built. Just to rule that out for runs this commit makes 2
changes. First it creates a conda environment/virtualenv with a unique
name for each run. Secondly it runs git clean to remove any old built
wheels (assuming there are any). This turned out not to be the cause
of the failure, but it still doesn't hurt to just rule this out in future builds
anyway. To fix the underlying issue this commit splits the test running
from the aer build into a separate stage in the job. It also changes the
pip command invocation to only install locally and not fallback to use
pypi if a wheel isn't built.
> Avoid reuse in azure pipelines and split build out

- CMakeLists.txt
- src/base/controller.hpp
Non-OpenMP builds are allowed (because not all the possible platforms do support it), but there was a bug in the build system where non-OpenMP builds were failing at compile time.
I have improved messaging while building too
> Fix non-OpenMP builds

- CHANGELOG.md
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- src/framework/utils.hpp
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_state.hpp
- test/benchmark/quantum_fourier_transform_benchmarks.py
- test/benchmark/tools.py
Adds Controlled-U1 (`"cu1"`) to simulator basis gates. This greatly improves performance of ideal circuits with a lot of cu1 gates (like qft circuits).
* Fixes a bug in previous implementation of `mcu1` in terms of `mcu3` in QubitVector, since the phase convention of cu3 didn't give a proper cu1.
* Adds optimized `apply_mcphase` method to `QubitVector` which is used to implement `u1, cu1, mcu1, z, cz, ccz, mcz, s, std, t, tdg`.
* Adds check for optimized implementation of anti-diagonal single-qubit gates to `apply_matrix` in qubit vector. This should slightly speed up the post-measurement/reset state update, and some Kraus errors (such as amplitude damping).
> Add controlled-u1 to basis_gates

- CHANGELOG.md
- src/framework/operations.hpp
When loading qobj json this checks if each instruction type is allowed to be conditional. If an unsupported instruction is set as conditional an exception will be raised.
Adds conditional support to some instructions that were missing (unitary, multiplexer)
Fixes #268 by raising an error for job containing conditional measure instructions.
* adds conditional "unitary" and "multiplexer" gates
* raises exception if qobj conditions conditionals for unsupported instructions: "measure", "reset", "initialize", "bfunc", "barrier", "snapshot", "noise_switch", "kraus", "roerror".
> Add check if ops can be conditionals

- qiskit/providers/aer/noise/noise_model.py
Fixes bug in `NoiseModel.add_nonlocal_quantum_error` where there was a key error if multiple nonlocal errors were added to the qubit and instruction.
> Fix bug in NoiseModel.add_nonlocal_quantum_error

- .mailmap
This commit adds 2 missing entries to the mailmap for users whose github
username was used as the author name. It pulls their full name from
their github profiles.
> Add entries missing entries in mailmap from github user metadata

- test/benchmark/__init__.py
- test/benchmark/quantum_fourier_transform_benchmarks.py
- test/benchmark/quantum_volume_benchmarks.py
- test/benchmark/simple_benchmarks.py
- test/benchmark/tools.py
Transpilation process is not mandatory in simulation, and it can add different optimizations to the circuits over time that will interfere in the results of the benchmarks, so we are removing it from all the benchmarks.
Anyway, I want to make sure that this assumption is correct @chriseclectic  :)
We may notice visible performance peak in the benchmarks right after this PR, that is expected.
> Remove transpiler optimizations from the benchmarks

- CHANGELOG.md
- src/framework/operations.hpp
- src/framework/utils.hpp
- src/simulators/tensor_network/matrix_product_state.cpp
Includes from features from PR #253 to break it up into smaller PRs.
* Adds standard gate superoperator matrices to utils.
* Adds a `"superop"` qobj instruction type
* Allows "superop" and "kraus" instructions to be conditional since these could be used for errors on conditional gates in qiskit circuits.
> Add superoperator utils

- src/simulators/unitary/unitarymatrix.hpp
Adds methods to `UnitaryMatrix` class for computing trace and checking if the matrix is an identity. These are taken from the old identity-checker PR so they can be merged before bit-rotting away, though they are not used as an identity checker (that interface needs to be decided later).
> Add trace and check identity to UnitaryMatrix

- CHANGELOG.md
- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- src/base/controller.hpp
- src/simulators/qasm/qasm_controller.hpp
- src/simulators/statevector/statevector_controller.hpp
- src/simulators/unitary/unitary_controller.hpp
* Moves `library_dir` config parameter for MacOS OpenMP hack to the base AerBackend class
* Adds a user configurable "validation_threshold" parameter to controller classes for validating initial states.
* Lowers default validation threshold parameter from 1e-10 to 1e-8 since it better suits typical precision from Numpy
> Add validation threshold to backend options

- CHANGELOG.md
- src/simulators/tensor_network/matrix_product_state.cpp
- src/simulators/tensor_network/tensor_network_state.hpp
The previous versions of snapshot_matrix_expval and snapshot_pauli_expval in tensor_network_state did not support multiplying the expectation value by the coeff parameter. I added this support now, to make sure we get the same results as provided by the statevector simulation method.
> Fixed coeff in tensor_network_state simulation method

- contrib/standalone/qasm_simulator.cpp
- qiskit/providers/aer/backends/wrappers/qasm_controller_wrapper.pyx
- qiskit/providers/aer/backends/wrappers/statevector_controller_wrapper.pyx
- qiskit/providers/aer/backends/wrappers/unitary_controller_wrapper.pyx
- src/base/controller.hpp
- src/simulators/controller_execute.hpp
- src/simulators/qasm/qasm_controller.hpp
- src/simulators/statevector/statevector_controller.hpp
- src/simulators/unitary/unitary_controller.hpp
- src/transpile/basic_opts.hpp
- src/transpile/circuitopt.hpp
- src/transpile/fusion.hpp
- src/transpile/truncate_qubits.hpp
This PR reworks the controller class so that it doesn't store a single config or noise model.
* The config and noise model is now passed through execute functions so that the noise model or config can be modified in a thread safe way for each different circuit execution. 
* Adds nosie model to circuit optimization framework (though it is currently not used)
* Fixes an issue with the MacOS openmp hack that would cause a segfault if it wasn't loaded before any virtual function of the controller was called. This hack is now loaded by the `execute_controller` cython wrapped function, rather than in the `set_config` method.
> Remove persistent config and noise model from controller

- src/base/controller.hpp
- src/simulators/densitymatrix/densitymatrix.hpp
- src/simulators/densitymatrix/densitymatrix_state.hpp
- src/simulators/qasm/qasm_controller.hpp
- src/simulators/statevector/qubitvector.hpp
- src/simulators/unitary/unitarymatrix.hpp
- test/terra/backends/test_qasm_density_matrix_simulator.py
Adds density matrix simulator method to `QasmSimulator` (closes #39)
Currently this won't every be used automatically. It must be specified with
```
backend_options={'method': 'density_matrix'}
```
TODO in follow up PRs
* Update `DensityMatrix::State` class to support newer gates added in `QubitVector::State` class
* superoperator noise sampling for density matrix simulator
* readout error with density matrix
> Density matrix simulator (ideal only)

- CHANGELOG.md
- src/base/controller.hpp
- src/base/state.hpp
- src/simulators/densitymatrix/densitymatrix_state.hpp
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
- src/simulators/qasm/qasm_controller.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/superoperator/superoperator_state.hpp
- src/simulators/tensor_network/tensor_network_state.hpp
- src/simulators/unitary/unitary_state.hpp
- test/terra/backends/qasm_simulator/qasm_method.py
- test/terra/backends/test_qasm_density_matrix_simulator.py
This enables the density matrix method to be automatically used by the QasmSimulator
It will be enabled for circuit executions satisfying the following conditions:
1. Circuit has a noise model with quantum noise
1. Circuit has no intermediate measurements
1. The density matrix can fit in the available memory
1. Number of shots > 2 ** num_qubits
The last condition is based on the heuristic that applying a single instruction on a density matrix is approx `2 ** num_qubits` times slower than applying to a statevector due to the larger dimension, so the density matrix method should come out ahead when the number of shots exceeds this difference.
> Enable automatic density matrix method in QasmSimulator

- CHANGELOG.md
- qiskit/providers/aer/backends/qasm_simulator.py
- src/simulators/qasm/qasm_controller.hpp
- test/terra/backends/qasm_simulator/matrix_product_state_measure.py
- test/terra/backends/qasm_simulator/matrix_product_state_method.py
- test/terra/backends/test_qasm_matrix_product_state.py
Changed name of simulation method from tensor_network to matrix_product_state.
After the release, we will consider changing the name of the tensor_network_state.hpp file and class, but for now we are only changing the method name.
See issue # 314.
> Changed name of MPS simulation method to matrix_product_state

- src/base/controller.hpp
- test/terra/backends/qasm_simulator/qasm_measure.py
- test/terra/common.py
- test/terra/reference/ref_measure.py
* Fixes #321 
* Adds measure tests for `memory=True`
The `set_config` method of the `Data` accumulator for the base controller class wasn't being called, so any additional data such as `memory=True` was being discarded when accumulated.
> Fix data accumulator not loading config

- src/base/controller.hpp
- src/simulators/statevector/statevector_controller.hpp
- src/simulators/unitary/unitary_controller.hpp
Disables qubit truncation by default for the StatevectorSimulator and UnitarySimulator so that the size of the output isn't changed.
If someone wants to enable truncation on these backends they can still do so using `backend_options={"truncate_enable": True}`.
The recent changes to applying truncation in the base controller before memory requirement calculations had the side effect of truncating the output of the Statevector and Unitary simulators which is a change in behaviour from previous versions.
> Disable truncation by default for non-Qasm controllers

- CHANGELOG.md
- src/simulators/qasm/qasm_controller.hpp
- src/transpile/delay_measure.hpp
- test/terra/backends/qasm_simulator/qasm_delay_measure.py
- test/terra/backends/test_qasm_simulator.py
Follow on from #316 
This adds a circuit optimization pass that pushes measurements to the end of a circuit if no conditional operations, or other operations on the already measured qubits follow.
This is needed for measure sampling to work with the density matrix simulator when there are quantum errors on measure instructions.
> Delay measure circuit optimization

- src/transpile/fusion.hpp
Support fusion of `cu1`
`cu1` is a basic operator since #258, but has not been supported in fusion.
> support cu1 fusion

- .gitignore
- tox.ini
This commit adds support for using tox by adding a tox.ini. This makes
it very simple for users and contributors to run tests and style checks
locally by just using the `tox` command. It will handle building and
installing aer and it's dependencies in a virtualenv to isolate it from
system python for testing. This is also a common tool for python
projects, as many (if not most) other python projects use it. Most of
the other qiskit elements also support using it.
> Add tox.ini to start using tox

- qiskit/providers/aer/noise/device/models.py
- qiskit/providers/aer/noise/device/parameters.py
(Most) Devices now return gate timing information in their properties under the key `"gate_length"`. Previously the device noise model was looking for `"gate_time"` key. This updates the device noise model to use the correct name.
It also renames the kwarg for adding custom gate times to `gate_lengths` and adds a deprecation warning if someone uses the old `gate_times` kwarg
Closes #336
> Update device noise model to use gate_length

- qiskit/providers/aer/noise/utils/noise_transformation.py
In the spirit of https://github.com/Qiskit/qiskit-terra/pull/3156 , it would be great to get `import sympy` out of the list of things that are run by default when `import qiskit` is run (since it takes >500ms). Since Aer is imported by default from qiskit (when installed,) it would be great to remove the top-level `import sympy` from `qiskit/providers/aer/noise/utils/noise_transformation.py`. This PR moves the sympy to function level imports.
> Import sympy lazily.

- .travis.yml
The brew installation of openblas is sometimes taking over 10min to
build and install in the osx travis jobs. To avoid the job timing out
waiting for brew to emit output this commit adds a travis_wait call to
all the brew calls to make the timeout independent from output from the
command.
> Add travis wait to brew installs

- .travis.yml
Remove `libomp` and `openblas` dependencies from MacOS travis builds
The brew bottle for GCC is no longer supplied for MacOS 10.12 (xcode 9.2) this was causing all travis mac builds to timeout because gcc was being built from source (as a dependency for openblas) which can take an hour.
> Update travis xcode build

- CHANGELOG.md
- qiskit/providers/aer/extensions/__init__.py
- qiskit/providers/aer/extensions/snapshot.py
- qiskit/providers/aer/extensions/snapshot_stabilizer.py
- qiskit/providers/aer/extensions/snapshot_statevector.py
- src/simulators/qasm/qasm_controller.hpp
- src/simulators/stabilizer/pauli.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- test/terra/backends/qasm_simulator/qasm_snapshot.py
- test/terra/backends/test_qasm_density_matrix_simulator.py
- test/terra/backends/test_qasm_matrix_product_state.py
- test/terra/backends/test_qasm_simulator.py
- test/terra/backends/test_qasm_stabilizer_simulator.py
- test/terra/backends/test_qasm_statevector_simulator.py
- test/terra/extensions/__init__.py
- test/terra/extensions/test_snapshot_stabilizer.py
- test/terra/extensions/test_snapshot_statevector.py
- test/terra/reference/ref_snapshot_state.py
**EDIT: ** *breaking PR up into multiple smaller ones. This now just covers statevector and stabilizer snapshots.*
Fixes signatures of state snapshots:
Close #301, #302, #369 
* Changes statevector, stabilizer, density matrix snapshot circuit function to not need qubit number since they are always all qubit
* Changes stabilizer snapshot to only return the list of stabilizer generators rather than the full clifford table.
* Changes order of stabilizer string serialization so that it works correctly with terra Pauli class qubit order.
> Snapshot statevector and stabilizer extensions

- CHANGELOG.md
- qiskit/providers/aer/extensions/snapshot_probabilities.py
- test/terra/backends/qasm_simulator/qasm_snapshot.py
- test/terra/backends/test_qasm_density_matrix_simulator.py
- test/terra/backends/test_qasm_simulator.py
- test/terra/backends/test_qasm_stabilizer_simulator.py
- test/terra/backends/test_qasm_statevector_simulator.py
- test/terra/extensions/test_snapshot_probabilities.py
- test/terra/reference/ref_snapshot_probabilities.py
Fixes snapshot probabilities extension to work on any number of qubits.
Adds tests for probability snapshots
Closes #304 
~Blocked by #374~
> Fix snapshot probabilities extension

- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/matrix_product_state/matrix_product_state_internal.hpp
Removes some source code function definitions and enum class members for functionality that isn't implemented yet.
* Removes enum class for snapshots with variance
* Removes Kraus from supported instruction list
* Removes `norm` function from MPS class that is not implemented.
> Remove un-implemented methods from MPS simulation method

- setup.py
This commit fixes an issue with the sdist if you ran in an environment
where scikit-build was not installed. scikit-build is a build time
dependency for installing aer from source, however the sdist treated
the lack of scikit-build as not fatal. Instead it would silently build a
dummy package which would just build an empty package with only
metadata. This leave users attempting to build from sdist very confused
because if they were missing scikit-build for any reason there is no
output regarding that or any errors. But instead when they go to use aer
it's not found because it was not actually installed.
> Fix sdist to always attempt to build

- src/base/controller.hpp
- src/base/state.hpp
- src/framework/results/experiment_data.hpp
- src/framework/results/experiment_result.hpp
- src/framework/results/snapshot.hpp
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/qasm/qasm_controller.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/statevector/statevector_controller.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_controller.hpp
* Adds complex vector and complex matrix additional data containers to the `ExperimentData` class.
* Updates JSON data containers to be `unordered_map<string, json>` so that JSON is only used for the inner data type.
This is a first step for speeding up the statevector and unitary simulators by only converting to JSON at the very end of simulation. Follow up work is to bypass this conversion step entirely and copy the vector and matrix data directly into a numpy array in python for local simulation.
> Improve additional data containers in ExperimentData

- CHANGELOG.md
- src/framework/results/data/pershot_data.hpp
- src/framework/results/data/pershot_snapshot.hpp
- src/framework/results/experiment_data.hpp
- src/framework/results/experiment_result.hpp
- src/framework/results/snapshot.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_state.hpp
Reworks pershot snapshot data containers to have templated data types. Adds standard pershot snapshot containers to `ExpeirmentData` for complex numbers, complex vectors, complex matrices, complex string-maps, and double string-maps, and json.
* Partially fixes #269 
* Depends on #404*
* Will add similar fix for average snapshots in follow up PR
Using fixed datatypes for snapshot storage greatly reduces memory usage and improves simulation time when snapshots are used since they are only converted to JSON during final serialization of the Result object. Eventually this serialization should be bypassed for local simulation and the objects should directly be copied to python objects.
Example of memory usage reduction for 14-qubit statevector snapshot on a noisy simulation with 1024 shots: …
> Improve pershot snapshot data container and performance

- CHANGELOG.md
- src/framework/linalg/almost_equal.hpp
- src/framework/linalg/enable_if_numeric.hpp
- src/framework/linalg/linalg.hpp
- src/framework/linalg/linops/linops_array.hpp
- src/framework/linalg/linops/linops_generic.hpp
- src/framework/linalg/linops/linops_json.hpp
- src/framework/linalg/linops/linops_map.hpp
- src/framework/linalg/linops/linops_matrix.hpp
- src/framework/linalg/linops/linops_unordered_map.hpp
- src/framework/linalg/linops/linops_vector.hpp
- src/framework/linalg/square.hpp
- src/framework/utils.hpp
- test/src/test_utils.cpp
Adds utility functions for `add`, `iadd`, `sub`, `isub`, `mul`, `imul`, `div`, `idiv`, `square` for generic types that support these functions, and specialized functions for `std::array`, `std::vector` `std::map`, `std::unordered_map`, `matrix` and `json` types.
This is needed as a first step for adding improved average snapshot containers with non-JSON data storage types in #407
> Linear algebra operations for STL types

- qiskit/providers/aer/noise/noise_model.py
Improves noise model so that if gate objects are used the label and basis_gates can be automatically inferred when adding quantum errors. This simplifies adding custom noisy gates which can then be used with the transpiler using `NoiseModel.basis_gates` for unrolling.
For example, if we wish to add noise only to a labelled X-gate we can now do the following:
```python
from qiskit.extensions import XGate
from qiskit.providers.aer import noise
noisy_x = XGate(label="x_noise")
error_x = noise.errors.depolarizing_error(0.1, 1)
nm = noise.NoiseModel()
nm.add_all_qubit_quantum_error(error_x, noisy_x)
print(nm)
"""
NoiseModel:
Basis gates: ['cx', 'id', 'u3', 'x']
Instructions with noise: ['x_noise']
All-qubits errors: ['x_noise']
"""
```
> Add automatic label detection to NoiseModel

- CHANGELOG.md
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_state.hpp
* Adds missing supported basis gates to the backend "basis_gates".
* Adds missing "gates" fields information to Aer backend configuration.
Added basis gates that were already supported by simulators include:
* Controlled-u1 gate (name `"cu1"`)
* Controlled-u2 gate (name `"cu2"`)
* Controlled-u3 gate (name `"cu3"`)
* Controlled Swap (fredkin) gate (name `"cswap"`)
* Multi-controlled X gate (name `"mcx"`)
* Multi-controlled Y gate (name `"mcy"`)
* Multi-controlled Z gate (name `"mcz"`)
* Multi-controlled u1 gate (name `"mcu1"`)
* Multi-controlled u2 gate (name `"mcu2"`)
* Multi-controlled u3 gate (name `"mcu3"`)
> Add missing basis gates to backends

- test/terra/backends/test_pulse_simulator.py
Add comment on IQ data for meas level 1.
> Meas level 1 comment in pulse sim tests

- .gitignore
- .stestr.conf
- .travis.yml
- azure-pipelines.yml
- requirements-dev.txt
- tox.ini
This commit switches the test runner for running the aer tests to
stestr. stestr is a unittest compatible test runner that executes tests
in parallel by default. This can provide significant speeds ups for
running a test suite. It also provides a rich set of scheduling [1] and
test selection [2] features which we can use to fine tune how we execute
tests. Based on local testing 2 classes of tests run in parallel already, to
optimize the run time thees need to be scheduled serially so that they don't
compete for resources. This is done using a group_regex [3] which is used
to provide a scheduler hint to keep these tests together.
[1] https://stestr.readthedocs.io/en/stable/MANUAL.html#test-scheduling
[2] https://stestr.readthedocs.io/en/stable/MANUAL.html#test-selection
[3] …
> Switch to running tests in parallel with stestr

- CHANGELOG.md
- src/simulators/stabilizer/clifford.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/statevector/statevector_state.hpp
- test/terra/backends/qasm_simulator/qasm_snapshot.py
The code for the stabilizer probabilities snapshot does not work properly for subsets of qubits. This pull request fixes this.
More details can be found in https://github.com/Qiskit/qiskit-aer/issues/389
> Rewrite stabilizer snapshot_probabilities

- CHANGELOG.md
- src/simulators/unitary/unitary_state.hpp
- test/terra/backends/qasm_simulator/qasm_noncliffords.py
- test/terra/backends/test_statevector_simulator.py
- test/terra/backends/test_unitary_simulator.py
- test/terra/reference/ref_non_clifford.py
* Fixes bug in unitary simulator where `cu3` gate was being applied as a `cu1` gate.
* Adds integration tests for cu3 gate for qasm, unitary, and statevector simulators
Closes #275
> Fix bug in unitary simulator cu3 and add cu3 tests

- qiskit/providers/aer/openpulse/qobj/digest.py
- test/terra/backends/test_pulse_simulator.py
Addresses issue #478 by implementing the suggested changes.
1. The test case `test_persistent_value` was commented out.
2. `digest_pulse_obj` was modified to look for key `'seed'` in `backend_options` and pass this to the pulse simulator. (Code for this already existed, but it was looking in the standard 
pulse `qobj` configuration. I think `backend_options` is a more natural place for this as it is an option for how simulation is done.) The helper functions, `backend_options_1q` and `backend_options_2q`, were updated to include a seed.
> Issue 478 pulsesim test errors

- azure-pipelines.yml
In the past we needed to pin the pip version we used in the ci jobs to
avoid a pip regression introduced in pip 19.0. But that has since been
fixed so pinning is no longer necessary. This commit updates the azure
pipelines configuration to remove the pip pinning so we can use the
latest version.
> Remove pip pin in azure jobs

- constraints.txt
- qiskit/providers/aer/noise/utils/noise_transformation.py
In an effort to unify the versions of pylint run across all the elements
this commit bumps the pinned versions of pylint and astroid to be the
latest and what we are syncing all the elements to use. This should make
working between all the elements easier to do.
Related To: Qiskit/qiskit-terra#3629
> Bump pin to unify lint job versions across elements

- qiskit/providers/aer/backends/pulse_simulator.py
- qiskit/providers/aer/openpulse/qobj/digest.py
As it won't be supported, removed `noise_model` argument from the pulse simulator backend, as well as the `digest` file. It can still be passed and detected through `backend_options`, but an `AerError` will now be raised.
In addition: 
- all reference to `sim_config` has been removed; any options should be passed through `backend_options`
- The warning for PersistentValue pulses has also been changed to an `AerError`
> Removed `noise_model` and `sim_config` as an argument in the pulse simulator

- README.md
IBMQ.get_backend('ibmq_16_melbourne') function should be called by the provider object as per the new update.
> Fixed get_backend selection command

- README.md
The README had a broken link to tutorials for Aer.
I replaced the single broken link with links to the IQX tutorials and the Community tutorials. Please let me know if only one of those is preferred.
Does this change need to be documented in the CHANGELOG or have an issue opened? The CHANGELOG appears to only be used for code changes. 
This is my first (very small) contribution to Qiskit so please forgive me if I have done something incorrectly.
> README > Fix broken tutorials links

- qiskit/providers/aer/noise/utils/noise_transformation.py
Some noise transformations requires cvxpy library to operate.
As cvxpy is a heavy dependency, we send a message to the user if it's needed but not installed.
> Issue 490 - cvxpy needed for noise transformations

- pyproject.toml
- requirements-dev.txt
- setup.py
Since commit 0e184e09c6e1c6f28d4e4b199e9182d262b81520 we've required
pybind to build the python extension for aer. However this was expected
to outside of the install by users and was only listed as a dev requirement
via the requirements-dev.txt file. However, pybind is a build dependency
and will always need to be installed to build and install aer. This
commit updates the install_requires and setup_requires list to make sure
we always have pybind11 installed when installing aer from source or
sdist.
> Add pybind as a requirement

- .travis.yml
With the recent release of pip 20.0.0 and 20.0.1 some packages fail to
pip install correctly (20.0.0 didn't even work at all). Until these
issues are resolved we should just cap the pip we use in CI to avoid
issues. This commit adds a cap to use pip < 20.0.0 until the upstream
issues are resolved. At the same time this commit updates the osx
version we use in CI for the 3.8 job to use 3.8.1 which contains bug
fixes on top of the previous version 3.8.0 we were using prior.
> Pin pip<20.0.0 and bump osx python 3.8 to 3.8.1

- qiskit/providers/aer/backends/unitary_simulator.py
Fixes #497 
The unitary simulator does not support the "initialize" instruction, so it should not be listed in basis gates.
> Remove initialize from unitary_simulator basis gates

- test/benchmark/fusion_benchmarks.py
from qiskit import QiskitError for lines 55 and 110
Lines 55 and 110 have the potential to raise NameError instead of the intended QiskitError because they refer to QiskitError which has not been defined or imported into this file.
> from qiskit import QiskitError for lines 55 and 110

- setup.py
The recently added pulse simulator adds numpy and scipy as build and install dependencies. These were missing from the setup.py causing an error if they weren't already installed on the system.
Pybind is still a remaning issue. As noted in #546, if one tries to install directly in a clean environment (eg `pip install .` or `pip install git+https...`), setup will fail unless Pybind has already been pip installed.
> Fix missing pulse simulator dependencies in setup.py

- qiskit/providers/aer/openpulse/duffing_model_generators.py
- qiskit/providers/aer/openpulse/pulse_system_model.py
- test/terra/openpulse/test_duffing_model_generators.py
- test/terra/openpulse/test_system_models.py
In `PulseSystemModel` changed `control_channel_dict` to a list called `control_channel_labels` and created an automatic construction of this list in the `from_backend` constructor.
1. Had to change `control_channel_dict` to a list as elements of a dict need to be hashable (and therefore can't be anything, as was originally intended). Now the function `control_channel_index` takes an argument called `label`, and is implemented by finding the index in the list. Had to change the duffing model generators, as well as associated tests to correspond to this change.
2. Added a piece to `from_backend` to automatically construct labels for u channels. The format for the auto generated labels is currently cumbersome, but there isn't really a way around it. Given a u channel, it automatically finds …
> Pulse simulator control channel labels from backend

- cmake/cython_utils.cmake
Disable all warnings when compiling Cython generated cpp files
Disable all warnings only for Cython generated cpp files. Other files not automatically generated will still emit warnings. This is related to issue #548.
> Disable warnings when compiling Cython generated CPPs

- CHANGELOG.md
- qiskit/providers/aer/backends/qasm_simulator.py
- src/base/controller.hpp
- src/simulators/qasm/qasm_controller.hpp
- test/terra/backends/qasm_simulator/qasm_thread_management.py
- test/terra/decorators.py
Custom OpenMP parallelization settings were being set correctly with respect to maximum number of threads. This PR corrects the setting and adds several additional integration tests for testing that the default and custom thread setting behavior works as expected.
This PR also adds test decorators for tests that require OpenMP or a multicore CPU so that they will be skipped if run on a system without these.
* By default all available threads will be used for parallel shots and state update, subject to available memory, noise, and measure sampling.
* Parallel experiments will only ever be run if this option is explicitly configured.
* Adds test decorator `requires_omp` which will skip tests if simulator is build without OpenMP
* Adds test decorator `requires_multiprocessing` which will …
> Fix bugs in parallelization thread management and improve testing

- qiskit/providers/aer/openpulse/hamiltonian_model.py
- qiskit/providers/aer/openpulse/qobj/digest.py
- test/terra/openpulse/test_system_models.py
Fixes the following issue:
The pulse simulator implicitly assumes in various places that the drift Hamiltonian is nearly diagonal. One place is (currently) in `HamiltonianModel`, when the drift data is being computed: the eigenstates are being ordered according to their overlap with the computational basis. If two eigenstates have max overlap occurring on the *same* computational basis vector (e.g. a single qubit, with the drift being Pauli X), the current ordering routine will overwrite the first one with the second one, resulting in some eigenvectors not being counted, and ultimately leads to the ordered eigenvalue list containing at least one instance of the 0 vector. This led to situations in which simulator would 'think' the ground state of the hamiltonian is the 0 vector, leading to …
> Fixing pulse simulator eigenstate ordering bug

- .travis.yml
Following on from #553, this PR helps clean up travis build logs and test by adding an extra `compile` stage to the travis tests.
* The compile stage tests building the Python wheels on Linux and MacOS
* The test stage is modified to only run the python unittest scripts so that the full CMake build log isn't returned in the output script.
* Move Python 3.8 MacOS tests to kron job since they are taking too long to run (3-4 x slower than 3.7 tests)
This helps fix issue #548 as we add more build files and more tests files leading to longer and longer logs.
> Add compile stage to travis script

- qiskit/providers/aer/openpulse/qobj/digest.py
- qiskit/providers/aer/openpulse/solver/unitary.py
- test/terra/backends/test_pulse_simulator.py
Updated pulse sim to use new way of specifying `Acquire` commands to eliminate deprecation warnings in tests. Note, at the time of writing, the tests still generate many warnings, but these warnings are a bug in `terra` as described by @lcapelluto, so should go away.
Old way of specifying `Acquire` commands was to specify a single command with a list of `AcquireChannel` objects and a list of `MemorySlot` objects. New way is to specify an acquire command for each qubit individually.
1. Updated digest to not set `can_sample` to `False` if there is more than one acquire command. (Now it only does so if any acquire commands occur before the final time.)
2. Updated `unitary.py` to handle a list of acquire commands occurring at the end of simulation. (It compiles them back into a single list.) …
> Updating pulse simulator to new way of specifying Acquire commands

- qiskit/providers/aer/__init__.py
- qiskit/providers/aer/backends/__init__.py
- qiskit/providers/aer/backends/pulse_simulator.py
- qiskit/providers/aer/openpulse/__init__.py
- qiskit/providers/aer/openpulse/duffing_model_generators.py
- qiskit/providers/aer/openpulse/hamiltonian_model.py
- qiskit/providers/aer/openpulse/pulse_system_model.py
- qiskit/providers/aer/openpulse/qobj/digest.py
- test/terra/backends/test_pulse_simulator.py
- test/terra/openpulse/test_duffing_model_generators.py
- test/terra/openpulse/test_pulse_digest.py
- test/terra/openpulse/test_system_models.py
Closes #433
Closes #500
Adding doc strings for for pulse simulator files `pulse_simulator.py`, `pulse_system_model.py`, `duffing_model_generators.py`.
Changed `qubit_list` to `subsystem_list` in `hamiltonian_model`, `pulse_system_model`, and `digest`, and updated all relevant tests.
Changes are:
1. Added doc strings for relevant classes/functions in above mentioned files.
2. Updated aer `__init__.py` file to put relevant classes/methods in API doc generations: added `PulseSimulator` to the list of backends, and added a section called `OpenPulse` to have `PulseSystemModel` and `duffing_model_generators`.
3. Updated backends `__init__.py` file to import `PulseSimulator`.
4. Updated openpulse `__init__.py` file to import `duffing_system_model` and `PulseSystemModel`.
5. Removed warning for …
> Pulse simulator doc strings and changing naming of `qubit_list`

- qiskit/providers/aer/noise/errors/quantum_error.py
- qiskit/providers/aer/noise/errors/readout_error.py
- test/terra/noise/test_quantum_error.py
- test/terra/noise/test_readout_error.py
Updates QuantumError and ReadoutError to be consistent with changes to `Operator` API that will be introduced in Terra 0.12.
* Add `dot` method to `QuantumError` and `ReadoutError`
* Add operator overloads for *, @, ^ for dot, compose, tensor to
`QuantumError` and `ReadoutError`
* Raise `NotImplementedError` for overloads +, -, /. scalar *, as these aren't
supported for`QuantumError`, `ReadoutError`.
* Deprecate `front=True` kwarg of compose for `QuantumError`, `ReadoutError`
* Remove deprecated `kron` method from `QuantumError`
* Fixes linting errors in the test files for QuantumError and ReadoutError
> Update QuantumError and ReadoutError to match new Terra Operator API

- src/misc/clang_omp_symbols.hpp
- src/misc/gcc_omp_symbols.hpp
When we add support for new versions of the compilers, or when we add code that
uses OpenMP, new symbols can show up and we need to add them to a list of symbols
we hook in order to avoid the multiple initialization constraint of libomp on MacOS.
This time we have added new OpenMP code that internally uses omp_get_num_procs()
function, so we have to add this new symbol to the list.
>  * Add "omp_get_num_procs" symbol to the list of hooks

- .travis.yml
In the recently merged #168 a small oversight was made in the last
revision to that PR. The name of the stage was updated from wheels to
deploy, but the stage listed for the individual jobs was never updated.
This commit corrects the oversight and uses a consistent stage name for
the new jobs.
> Fix incorrect stage name for wheel jobs

- CMakeLists.txt
- cmake/compiler_utils.cmake
Move Muparserx library related things in CMake to Terra-Addon build.
Muparserx libraries are not needed by standalone tool. Moved to Terra addon build as requested by Chris
> Move Muparserx related things to Terra Add-on build

- cmake/compiler_utils.cmake
Fix to make travis work with sdist
Cmake was incorrectly considering the muparserx header dir empty although it was not.
> Small fix in cmake to try make travis work with sdist

- CHANGELOG.md
- src/controllers/qasm_controller.hpp
- src/transpile/fusion.hpp
- test/terra/backends/qasm_simulator/qasm_fusion.py
Enable fusion optimization for all the circuits with 20 or more qubits by default
If a circuit uses 20 or more qubits, fusion works efficiently. 
**Performance of Quantum Volume (Red: Fusion-enabled, Blue: Fusion-disabled)**
**Performance of [QCBM](https://github.com/Roger-luo/quantum-benchmarks) (Red: Fusion-enabled, Blue: Fusion-disabled)**
**Performance of QFT**
Configuration
```
Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz x2, 376G RAM
Ubuntu 18.04.3 LTS, GCC 7.4.0
```
> enable fusion by default for 20 or more qubits

- .travis.yml
- azure-pipelines.yml
We recently pushed out the 0.4.0 release which was our first attempt of
using the wheel automation in production. There were a few issues
identified by the process, first several jobs forgot to add twine to the
install. This was not caught because we never tested the actual wheel
upload during the dry runs. Then for the sdist job we needed to update
the version of pip used in the job to actually be able to install some
of aer's build dependencies. The last oversight was that we never added
the additional trigger for tags to trigger the wheel jobs on azure
pipelines. This meant at release time the jobs never got triggered or
ran. This commit fixes all these issues so for the next release the
process should all work correctly.
> Fix issue with wheel automation from first attempt

- setup.py
It appears that the newly added pulse simulator has an implicit
requirement on having a newer version of numpy installed. We should
encode this minimum in the aer package requirements so people don't
accidently install aer with a version of numpy too old to work.
Fixes #592
> Bump minimum required version of numpy

- .travis.yml
- azure-pipelines.yml
We recently pushed out the 0.4.0 release which was our first attempt of
using the wheel automation in production. There were a few issues
identified by the process, first several jobs forgot to add twine to the
install. This was not caught because we never tested the actual wheel
upload during the dry runs. Then for the sdist job we needed to update
the version of pip used in the job to actually be able to install some
of aer's build dependencies. The last oversight was that we never added
the additional trigger for tags to trigger the wheel jobs on azure
pipelines. This meant at release time the jobs never got triggered or
ran. This commit fixes all these issues so for the next release the
process should all work correctly.
Backported from #589
(cherry picked from commit …
> [Stable] Fix issue with wheel automation from first attempt

- requirements-dev.txt
- setup.py
Installing the qiskit-aer python package always requires terra. This is
primarily because of the package namespacing the qiskit.providers package
doesn't exist outside of terra. But also because the majority of the
python functionality exposed via qiskit-aer depends on terra's api. We
should be enforcing that when you install aer terra is installed (and at
the correct version). Otherwise people could install aer and never get
it working.
> Add terra to the aer requirements list

- setup.py
It appears that the newly added pulse simulator has an implicit
requirement on having a newer version of numpy installed. We should
encode this minimum in the aer package requirements so people don't
accidentally install aer with a version of numpy too old to work.
(cherry picked from commit 12f97c8ba24e733633bc36077e76faf485a4e5eb)
Backported from #594 
Fixes #592
> [Stable] Bump minimum required version of numpy (#594)

- src/open_pulse/numeric_integrator.cpp
- src/open_pulse/python_to_cpp.hpp
It was causing the error: `Cannot import numpy.core.multiarray` only on
older versions of CentOS.
The real error was caused by a failed initialization of numpy, which was throwing this error before:
```
RuntimeError: _ARRAY_API is not "PyCapsule" object
```
The fix was fairly easy actually, even though it took me a while to figure out  why (taking into account that it was working in all other platforms, and in Debug mode!) -- we've just removed `static` initialization of numpy array API. 
We must pay attention to possible performance regressions.
> * Removes static numpy initialization strategy for the Pulse simulator

- .travis.yml
This commit updates the linux wheel compile job to mirror the
configuration we use for building wheels on linux at release time. This
adds 2 additional points of coverage. the first and most importantly is
that python packaging on linux has stringent requitements [1] that
require us to publish wheels in a specific docker image. To make sure
that we don't introduce a change that breaks compilation (since there
have been issues with that in the past) with that limitation we should
build wheels in that environment in CI. The second aspect of additional
coverage here is that it adds compilation of all supported python
versions.
[1] https://www.python.org/dev/peps/pep-0571/
> Switch linux wheel compile job to mirror deploy job

- src/open_pulse/numeric_integrator.cpp
- src/open_pulse/python_to_cpp.hpp
It was causing the error: Cannot import `numpy.core.multiarray` only on
older versions of CentOS.
> [stable] Removes static numpy initialization strategy for the Pulse simulator  (#609)

- .travis.yml
This commit updates the linux wheel compile job to mirror the
configuration we use for building wheels on linux at release time. This
adds 2 additional points of coverage. the first and most importantly is
that python packaging on linux has stringent requitements [1] that
require us to publish wheels in a specific docker image. To make sure
that we don't introduce a change that breaks compilation (since there
have been issues with that in the past) with that limitation we should
build wheels in that environment in CI. The second aspect of additional
coverage here is that it adds compilation of all supported python
versions.
[1] https://www.python.org/dev/peps/pep-0571/
Co-authored-by: Juan Gomez <atilag@gmail.com>
> [Stable] Switch linux wheel compile job to mirror deploy job (#601)

- requirements-dev.txt
- setup.py
Installing the qiskit-aer python package always requires terra. This is
primarily because of the package namespacing the qiskit.providers
package doesn't exist outside of terra. But also because the majority of
the python functionality exposed via qiskit-aer depends on terra's api. We
should be enforcing that when you install aer terra is installed (and at
the correct version). Otherwise people could install aer and never get
it working.
Backported from #593 
(cherry picked from commit 1e086f961147dc4874181943a5a4779395eea096)
> [Stable] Add terra to the aer requirements list (#593)

- cmake/FindMuparserx.cmake
- cmake/compiler_utils.cmake
Search for an already installed muparserx library.
Try to find an already installed muparserx library before uncompressing the distributed one and download code. This is linked to issue #599.
> Find muparserx system library before using distributed one

- src/framework/operations.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/transpile/fusion.hpp
Fixes #604 
1. Fixes bugs in gate fusion transpilation pass where the pass was not checking that unitary gates (`OpType::matrix`) where in the allowed instructions of simulator. This was causing simulations on the stabilizer simulator to fail for example when fusion was enabled automatically.
2. Fixes name of fusion instruction to be "unitary" rather than "fusion", and instead uses "fusion" is as the unitary gate label.
3. Adds exception to MPS simulator if it tries to apply a larger than 2-qubit gate. Previously this was silently ignoring the instruction.
> Fix gate fusion bug

- .travis.yml
- azure-pipelines.yml
- requirements-dev.txt
- setup.py
- src/open_pulse/numeric_integrator.cpp
- src/open_pulse/python_to_cpp.hpp
- tools/verify_wheels.py
It looks like recent changes were made to the stable branch names that deleted work done to backport fixes made since the 0.4.0 release. This commit re-backports all the fixes made to the previous stable branch so that we restore the old state. Ideally this should be rebased and merged or a merge commit used since each commit has been reviewed and is self contained so we should preserve that history as individual commits. If necessary we can directly push this to the stable branch.
Backported from: #589 (originally in #590), #594 (originally in #595), #588 (originally in #596), #609 (originally in #611), #601 (originally in #610) and #593 (originally in #618).
> [Stable] Re-Backport fixes since 0.4.0

- azure-pipelines.yml
- requirements-dev.txt
Since the latest cvxpy release is causing failures on python3.5. This
commit excludes the version so that CI jobs pass. Hopefully the next
release won't have the same failure. At the same time the python 3.5 job
was also failing because the version of pip and setuptools was too old.
This also bumps the version using conda to ensure it's new enough to install
cvxpy.
> Exclude new cvxpy release and update pip via conda on azure pipelines

- .travis.yml
This commit updates the travis configuration so we no longer are relying
on a test PPA of the dev toolchain for ubuntu to get the compiler
version we need. To do this the ubuntu version we're using is upgrade to
bionic which has all the compiler versions we need to build aer already
and is only 2 years old instead of 4. This enables us to stop using the
test ppa to be able to build aer.
These changes are already pending on stable/0.4 as part of the backport
PR #636
> Use bionic for CI and stop using toolchain test ppa

- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/noise/errors/quantum_error.py
- test/terra/noise/test_noise_model.py
[This PR](https://github.com/Qiskit/qiskit-terra/pull/3890) is currently blocked by bugs in Aer. This PR will hopefully fix some of those bugs. 
Currently, Noise Models are being received on the C++ side with probability attributes having (what appears to be) complex types - ~~we have yet to identify why~~ but the existing changes will at least raise a reasonable exception when it does happen. 
Bug was caused by a missing cast from complex type to float type in a QuantumError factory. Thanks @chriseclectic
> Fix QuantumError sometimes casting probabilities to complex

- test/asv.linux.conf.json
By installing Terra first we make sure all dependencies for the python extension (meant to work with Terra) are in place before building. By changing the order of dependencies installation we normalize with all other platforms (MacOS so far) too.
> Fix Linux benchmarks

- qiskit/providers/aer/extensions/snapshot_expectation_value.py
- qiskit/providers/aer/pulse/qobj/digest.py
Starting in Terra 0.13.0 the qobj passed to aer will not undergo type
coercion to be something python's `json.dumps()` natively understands.
This means that input qobj objects will have numpy arrays of complex
numbers instead of `list(list(re, im))`. This should be more efficient for
aer since it doesn't have to undergo a conversion step. However, we were
not handling this input type correctly in the pulse simulator and it
would lead to a failure trying to convert the list format to a numpy
array. This commit fixes this issue by checking if we have a numpy array
in the qobj and just using that directly instead of trying to convert
it.
Additionally, for the snapshot expectation value instruction has to hack around
a terra bug that doesn't allow `list` as a valid type for parameters on an …
> Handle numpy array inputs from qobj

- qiskit/providers/aer/extensions/snapshot_expectation_value.py
- qiskit/providers/aer/pulse/qobj/digest.py
* Handle numpy array of complex numbers in pulse qobj
Starting in Terra 0.13.0 the qobj passed to aer will not undergo type
coercion to be something python's json.dumps() natively understands.
This means that input qobj objects will have numpy arrays of complex
numbers instead of list(list(re, im)). This should be more effecient for
aer since it doesn't have to undergo a conversion step. However, we were
not handling this input type correctly in the pulse simulator and it
would lead to a failure trying to convert the list format to a numpy
array. This commit fixes this issue by checking if we have a numpy array
in the qobj and just using that directly instead of trying to convert
it.
* Add custom assemble method for snapshot expectation value
This commit adds a custom assemble method for …
> [Stable] Handle numpy array inputs from qobj (#656)

- .travis.yml
Currently we run macOS CI on macOS 10.12 which was released ~4 yrs ago.
Terra added a new binary requirement retworkx which builds it's wheels
against macOS 10.13. This means that pip can't find the wheels for macOS
in CI because 10.13 is too new. This commit bumps the macOS/xcode
version we use in the travis jobs to one slightly newer using macOS 10.13
(which is currently the default travis env). This should unblock CI
because we don't need to install retworkx from source with a newer osx version.
> Bump macos version in travis

- azure-pipelines.yml
Right now the azure ci jobs are failing because the env variable checks
used to determine if we're running a job on master vs stable is not
working for jobs post-merge on master. Now that the tests have been
update on aer master have been updated to use a pulse syntax only
available on terra master this has started failing because it
incorrectly fallsback to using terra from release. This commit attempts
to fix the situation by using a substring match instead of full match.
The assumption is that the value of BUILD_SOURCEBRANCH is actually
something like refs/heads/master instead of just master. So matching on
*master* should match any build running on master which is the behavior
we want.
> Use substring match for master in azure config

- src/framework/qobj.hpp
- test/terra/backends/test_parameterized_qobj.py
- test/terra/reference/ref_snapshot_expval.py
Allows specifying a parameterized qobj which will be expanded into multiple circuits when loading the qobj JSON.
qobj paramterizations are specified in the `QobjConfig` as 
`"parameterizations": [exp_0_params, ... ]`
where `exp_k_params = [[[i, j], [val_0, val_1, ....]], ...]`
where `i` is the instruction position in the `k` qobj circuit, `j` is the param position for that instruction, and `val_n` is the value of the n-th parameterization.
For a given exp_param each parameterization instruction must have the same number of parameterization value, however the number of parameterizations can be different for each circuit in the qobj.
If non-empty the length of `"parameterizations"` must match the number of experiments in the qobj or an invalid qobj exception will be raised (if one of the …
> Add support for parameterized qobj

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- src/framework/operations.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/superoperator/superoperator_state.hpp
- src/simulators/unitary/unitary_state.hpp
- test/terra/backends/qasm_simulator/qasm_unitary_gate.py
- test/terra/backends/statevector_simulator/statevector_basics.py
- test/terra/backends/test_qasm_simulator.py
- test/terra/backends/test_qasm_simulator_density_matrix.py
- test/terra/backends/test_qasm_simulator_statevector.py
- test/terra/backends/unitary_simulator/unitary_basics.py
- test/terra/common.py
- test/terra/reference/ref_diagonal_gate.py
Adds explicit support for terras diagonal gate operation. 
Closes #682 
This was previously internally supported through the unitary instruction but now adds an explicit diagonal_matrix op type for diagonal unitaries.
> Add support for terra diagonal gate

- pyproject.toml
- requirements-dev.txt
- setup.py
- src/framework/operations.hpp
- test/terra/decorators.py
- test/terra/noise/test_noise_model.py
- test/terra/reference/ref_algorithms.py
- test/terra/reference/ref_diagonal_gate.py
- test/terra/reference/ref_kraus_noise.py
- test/terra/reference/ref_measure.py
- test/terra/reference/ref_pauli_noise.py
- test/terra/reference/ref_reset_noise.py
- test/terra/reference/ref_snapshot_expval.py
- tools/verify_wheels.py
Fixes some import issues for updating tests to remove deprecation warnings for 0.13, by allowing backwards compatibility with terra 0.12.
> Add backwards compatibility for terra < 0.13

- qiskit/providers/aer/pulse/pulse_system_model.py
As fall out from Qiskit/qiskit-terra#4016 there was a bug in the
to_dict() method of the backend configuration that was resulting in
UChannelLO objects not getting converted to their dict form in the
output of to_dict(). While this is being fixed in
Qiskit/qiskit-terra#4124 this commit side steps the issue by adapting
the access patterns in the pulse system model to rely on class attribute
access and getattr() instead of dict access and get().
This is an alternative to the fix from a combination of #694 and Qiskit/qiskit-terra#4124
> Avoid to_dict() when possible in pulse system model

- src/controllers/controller.hpp
- src/controllers/qasm_controller.hpp
Currently qubit truncation will fail for circuits containing barriers across inactive qubits.
This fixes the order of circuit transpilation passes to apply the remove barrier pass before the qubit truncation pass.
Fixes Terra issue https://github.com/Qiskit/qiskit-terra/issues/2645
> Fix ReduceBarriers to be applied before qubit truncation

- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/releasenotes/notes/validation-opt-in-e43a002f160ddd11.yaml
Currently the aer backends are running jsonschema validation on the Qobj
objects passed in via terra by default. This is unnecessary overhead as
terra is programatically creating these objects and they're extremely
unlikely to be structurally invalid (which is all jsonschema will
catch). Even, if it was this will be caught later when something goes to
use it and the error message from that is more likely to be useful since
the way the json schemas are constructed precludes useful error message.
This commit changes the default value of this to be opt-in on the run()
method to avoid this unnecessary overhead.
> Disable jsonschema validation by default

- releasenotes/notes/automatic-method-930a74f765b9a94c.yaml
- src/controllers/qasm_controller.hpp
Removes the extended stabilizer simulator from automatically selected simulation methods. It must now explicitly be called as with the matrix product state method. If a user attempts to run a non-Clifford circuit with insufficient memory for the statevector method when using the automatic method an exception will be raised rather than trying to use the extended stabilizer method.
This is to avoid issues where the extended stabilizer simulator can return incorrect results if it is not configured correctly depending on the expected distribution of outputs for a given circuit. If an advanced user knows what they are doing they can call this method explicitly, however it shouldn't be used by default unknowingly as it could cause a drastic change in simulator behaviour when the method kicked …
> Remove "extended_stabilizer" from automatic simulation methods.

- releasenotes/notes/controller-transpile-298ea8d76a406648.yaml
- src/controllers/controller.hpp
- src/controllers/qasm_controller.hpp
- src/transpile/fusion.hpp
- test/terra/backends/qasm_simulator/qasm_fusion.py
* Removes the single list `optimize_circuits` from the base Controller class so that transpile passes must be called individually in controllers. This is important as certain passes (such as truncate qubits or fusion) should be called at different points of execution.
* Adds a `transpile_fusion` method to QasmController that returns a fusion pass that may be configured differently depending on the simulation method, circuit, and config. Currently it is set to use the same default values for all statevector and density matrix methods, and to disable fusion for stabilizer, mps and extended stabilizer methods.
Fixes #681. Fusion was causing problems with MPS simulation method so this disables it entirely for this method. This could be re-enabled if benchmarks or config settings are found …
> Update transpilation pass interface in controller

- qiskit/providers/aer/noise/device/basic_device_model.py
- qiskit/providers/aer/noise/device/models.py
- qiskit/providers/aer/noise/device/parameters.py
- qiskit/providers/aer/noise/errors/quantum_error.py
- qiskit/providers/aer/noise/noise_model.py
- releasenotes/notes/device-errors-bb231623712ecda7.yaml
Fixes #703 
Running example code in issue 703 now returns:
```python
Gate Infidelities (relax + depol, depol, relax)
id[0] = [0.00076, 0.00042, 0.00076]
u2[0] = [0.00076, 0.00042, 0.00076]
u3[0] = [0.00152, 0.00085, 0.00152]
id[1] = [0.00041, 0.00041, 0.00014]
u2[1] = [0.00041, 0.00041, 0.00014]
u3[1] = [0.00083, 0.00083, 0.00029]
id[2] = [0.00045, 0.00045, 0.00014]
u2[2] = [0.00045, 0.00045, 0.00014]
u3[2] = [0.0009, 0.0009, 0.00028]
id[3] = [0.00057, 0.00057, 0.0002]
u2[3] = [0.00057, 0.00057, 0.0002]
u3[3] = [0.00115, 0.00115, 0.0004]
id[4] = [0.00061, 0.00061, 0.00036]
u2[4] = [0.00061, 0.00061, 0.00036]
u3[4] = [0.00122, 0.00122, 0.00071]
cx[0, 1] = [0.01053, 0.00789, 0.01053]
cx[1, 0] = [0.01159, 0.00789, 0.01159]
cx[1, 2] = [0.00754, 0.00754, 0.00218]
cx[1, 3] = [0.01122, 0.01122, …
```
> Fix depol error param for device noise model with depol + relaxation error

- releasenotes/notes/fix-diagonal-unitary-check-a726500ffda6c74b.yaml
- src/framework/operations.hpp
- test/terra/backends/qasm_simulator/qasm_unitary_gate.py
- test/terra/reference/ref_diagonal_gate.py
Fixes #705 
Fixes bug where diagonal gates are flagged as non-unitary due to being checked with too high a tolerance.
Adds extra diagonal gate tests
> Fix tolerance when checking if diagonal is unitary

- src/simulators/statevector/qubitvector_thrust.hpp
Fix a bug to leak GPU memory in `qubitvector_thrust.hpp`.
An abstract class to manage host or device memory does not have `virtual` for its desconstructor. 
This fix will resolve #662.
> fix memory leak in gpu simulator

- releasenotes/notes/fix-controller-parallel-shots-d32967c029259790.yaml
- src/controllers/statevector_controller.hpp
- src/controllers/unitary_controller.hpp
> Fix number of parallel shots for statevector and unitary sims

- qiskit/providers/aer/utils/qobj_utils.py
- src/transpile/fusion.hpp
- test/terra/backends/qasm_simulator/qasm_fusion.py
Refactor gate fusion transpilation to use the Unitary state simulator or superoperator state simulator for fusing instructions. This also allows fusion of superoperator instructions in noisy circuits for density matrix simulation.
Partial closes #616
> Improve gate fusion

- qiskit/providers/aer/pulse/controllers/pulse_controller.py
- qiskit/providers/aer/pulse/system_models/hamiltonian_model.py
- test/terra/backends/test_pulse_simulator.py
- test/terra/openpulse/test_system_models.py
Closes #719 
1. Corrected subsystem reduction to not include implicit identities on the subsystems not included in `subsystem_list` for `HamiltonianModel.from_dict` when representing `full()` operators. 
2. Also fixed `HamiltonianModel.get_qubit_lo_from_drift()` so that it works when `subsystem_list` is not `range(k)` for some `k`. 
Associated with the above fixes is a slightly awkward interface issue: when calling `assemble`, the frequencies in `qubit_lo_freq` are assumed to correspond to the frequencies of the drive channels with indices `range(len(qubit_lo_freq))`. I.e. the frequency of `DriveChannel(idx)` is always assumed to be `qubit_lo_freq[idx]` regardless of what `subsystem_list` is. This results in needing to pass in "dummy" values for drive channel frequencies of qubits that …
> Fixing subsystem_list handling in pulse simulator

- docs/conf.py
The latest jupyter-sphinx release deprecated the plugin path we were
using which will now emit a deprecation warning. However because
warnings are marked as fatal with -W this is breaking the docs builds.
This commit updates are jupyter-sphinx usage to use the new path and fix
the warning/failure.
> Unblock ci for new jupyter-sphinx release

- src/simulators/matrix_product_state/svd.cpp
In svd.cpp: replaced all floating point `==` and `!=` to use `Linalg::almost_equal`. This cleans all the warnings out of the compilation of svd.cpp.
This PR addresses issue #468  .
> Changed FP comparisons to use Linalg::almost_equal

- releasenotes/notes/upgrade-measure-sampling-b9bd728e7c90704e.yaml
- src/controllers/qasm_controller.hpp
- src/framework/circuit.hpp
- src/framework/operations.hpp
- src/transpile/basic_opts.hpp
- src/transpile/delay_measure.hpp
- src/transpile/fusion.hpp
Improves how measurement sampling of circuits is checked to prevent circuit instructions being iterated over multiple times unnecessarily.
* Now the basic measurement sampling check of all measure instructions intail is done during construction of Circuit objects.
* Specific tests checking for instructions that prevent sampling is now checked using the circuit OpSet.
> Improve efficiency of checking measurement sampling conditions

- releasenotes/notes/expval_pauli-ec2ce5650dd82c49.yaml
- src/simulators/density_matrix/densitymatrix.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/density_matrix/densitymatrix_thrust.hpp
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/qubitvector_thrust.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitarymatrix_thrust.hpp
- test/terra/backends/qasm_simulator/qasm_snapshot.py
- test/terra/backends/test_qasm_simulator.py
- test/terra/backends/test_qasm_simulator_density_matrix.py
- test/terra/backends/test_qasm_simulator_matrix_product_state.py
- test/terra/backends/test_qasm_simulator_statevector.py
Greatly improves the performance of the Pauli expectation value snapshot instruction for the statevector method, and adds optimized pauli expectation value snapshots to the density matrix simulator.
Some simple benchmark comparisons for snapshots of Hamiltonian operators with N^2 number of N-qubit Pauli terms.
Relative speed up
> Optimize Pauli expectation value performance

- azure-pipelines.yml
- setup.py
Avoid use of numpy prerelease candidate 1.19.0rc1
Azure `Compile: Windows_Wheel_Builds Python35` and `Test: Windows Python35` fail because at some point it tries to install Numpy non-stable version 1.19.0rc1, and for some reason this breaks ([[1](https://dev.azure.com/qiskit-ci/qiskit-aer/_build/results?buildId=13867&view=logs&j=e75d9aed-3891-5f4d-4db6-188bb674529f&t=25841d21-5fa7-5cd2-f4f9-be64287d296a)] and [[2](https://dev.azure.com/qiskit-ci/qiskit-aer/_build/results?buildId=13867&view=logs&j=6cffd7fe-8559-5039-bd0f-14cdd5e20947&t=eb2406f7-5076-5344-3510-a196e012e349)]). In the first case it fails in our own `python ./setup.py` and in the second one when it tries to build one of the dependencies (`scs`).
> Avoid use of numpy prerelease candidate 1.19.0rc1

- qiskit/providers/aer/pulse/system_models/hamiltonian_model.py
- qiskit/providers/aer/pulse/system_models/string_model_parser/string_model_parser.py
- test/terra/backends/test_pulse_simulator.py
- test/terra/openpulse/test_system_models.py
Closes #526 
Closes #530
Changes:
1. Added `AerError` exceptions to `HamiltonianModel` for various hamiltonian string parsing scenarios that result in models that cannot be simulated.
2. Improved handling of `'vars'` when parsing a hamiltonian dict - it is now possible to construct and simulate a Hamiltonian with no variables without error.
3. Added various tests associated to the above changes.
Changes in detail:
- Added exceptions to `HamiltonianModel` construction from dictionary:
- Exception raised if `'h_str'` is empty 
- Exception raised if `'qub'` is empty (gets translated into `subsystem_list`)
- Exception raised if Hamiltonian has no channels in it after parsing (includes the case that a Hamiltonian had channels in it, but they ended up being removed when eliminating some …
> Fix Hamiltonian parsing edge cases in pulse simulator

- src/framework/qobj.hpp
Currently, the simulator seed parameter is ignored if it is smaller than zero. This can lead to intermittent surprises if users choose to set the seed to a negative number e.g. by using python's random.getrandbits(64). The current RNG seems to work with negative seeds.
> Allow Simulator Seeds Smaller Than Zero

- .travis.yml
The travis jobs were installing the qiskit-ibmq-provider from a github
zip link from the stable branch. However, that branch no longer exists
as qiskit-ibmq-provider recently changed there release model to match
the rest of qiskit (using qiskit-bot). While we could just switch to
install from pypi, this commit just removes that step since it was only
listed there as being done to supress the packaging warnings from terra
when the provider is not installed. Since qiskit-terra 0.13.0 there has
been an env variable that lets you do that. This commit adds that env
variable to the generic configuration so we don't emit a warning and
don't try to install from a dead link.
> Stop install ibmq provider as part of travis jobs

- releasenotes/notes/fix-density-matrix-diagonal-bb8ce049e2fa3c64.yaml
- src/simulators/density_matrix/densitymatrix_state.hpp
Fixes two bugs with the density matrix simulation
1. The new Diagonal terra gate was being applied incorrectly using the base statevector method due to a typo
2. The condition for checking conditional gates was not working correctly.
These weren't showing up as test failures due to problems with the tests themselves which are fixed in #765
> Fix bugs in density matrix simulation method for diagonal gates and conditionals

- setup.py
Scipy has dropped support for python 3.5 in their new release: 1.5.0, so we have
to tell setuptools to not try installing this version when building for Python 3.5
https://github.com/scipy/scipy/releases/tag/v1.5.0rc1
Saw the problem here:
https://dev.azure.com/qiskit-ci/qiskit-aer/_build/results?buildId=14320&view=logs&j=e75d9aed-3891-5f4d-4db6-188bb674529f&t=25841d21-5fa7-5cd2-f4f9-be64287d296a&l=1412
> Add scipy constraint on setup.py

- releasenotes/notes/fix-required-memory-check-0a138e0478d8ff32.yaml
- src/controllers/controller.hpp
- src/controllers/qasm_controller.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/statevector/statevector_state.hpp
Fixes issue where memory requirements of simulation were not being checked on the QasmSimulator when using a non-automatic simulation method.
Closes #755
> Fix required memory checks for QasmSimulator with custom method

- cmake/conan_utils.cmake
Nlohmann_json library back to 3.1.1 to avoid compilation errors with nvcc (CUDA).
Fixes #764
> nlohmann_json back to 3.1.1

- MANIFEST.in
- setup.py
The long description field was missing from the pypi package this leads
to the package page on pypi showing "The author of this package has not
provided a project description" instead of any details about the
package. This commit updates the package metadata to use the README as
the long description so that a rendered version will be shown on the
pypi page.
> Add README as pypi long description

- cmake/conan_utils.cmake
If `cmake is not installed in the system or in the `virtualenv, it is not able to find the one installed in the `.eggs directory, failing in case it has to build some package with `cmake.
This PR forces `conan to use the `cmake that has launched it
Our `setup.py` launches `cmake`, which at some point calls `conan`. If `conan` cannot retrieve a binary it has to build it. If the package is built with `cmake`, `conan` will call `cmake` on its own. When the `cmake` executable is installed on the fly in the `.eggs` directory, `conan` is not able to use that `cmake`. 
The solution is to force `conan` to use the `cmake` binary that has launched it.
Fixes #758
> Force conan to use CMake exec from which it has been launched

- src/framework/pybind_json.hpp
- src/framework/results/data/data_container.hpp
- src/framework/results/experiment_data.hpp
Refactor `ExperimentData` class to better handle custom data types
Adds templated `DataContainer` class that contains all methods for storing and combining data of a fixed type. There is still some boiler plate code in the `ExperimentData` class to call the methods for each inherited DataContainer type, but a lot less than before.
> Refactor ExperimentData class

- releasenotes/notes/density-matrix-snapshot-50de5e74c123a122.yaml
- src/simulators/density_matrix/densitymatrix.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/density_matrix/densitymatrix_thrust.hpp
- src/simulators/statevector/indexes.hpp
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/statevector_state.hpp
- test/terra/backends/qasm_simulator/qasm_snapshot.py
~Blocked by #712~
* Adds support for the density matrix snapshot to return the reduced density matrix of specified qubits
* Adds density matrix snapshot support to the statevector method, but returning density matrix sampled from the average of statevectors for each shots
> Add subsystem density matrix snapshots to qasm simulator

- test/terra/openpulse/test_system_models.py
The `PulseSystemModel` test `test_qubit_lo_from_configurable_backend` depends on the `FakeArmonk` backend - and was comparing a derived value from that backend to a hardcoded value. There are some inconsistencies resulting in the test failing occasionally - not sure why but it could e.g. come from changes to `FakeArmonk`. 
Changed the test to directly look at the values in `FakeArmonk` to make it insensitive to changes.
> Fix issues with pulse system model test using FakeArmonk

- qiskit/providers/aer/noise/device/models.py
- qiskit/providers/aer/noise/noise_model.py
The larger devices always have one or more bad gates that trigger warnings.  This allows for suppressing these.
> Allow for suppressing warnings in NoiseModel.from_backend()

- src/framework/matrix.hpp
The matrix class did not have a move constructor or assignment operator. This was causing unnecessary copies being made for things like density matrix snapshots.
> Add move semantics to matrix class

- azure-pipelines.yml
- constraints.txt
This commit fixes an issue in windows CI around the numpy version and
scipy which is tightly coupled to numpy. In #749 a cap was added to
avoid a broken numpy pre-release version that was getting installed
because an old version of pip was used by the default conda py3.5 env.
This was causing CI failures because the pre-release was for 1.19.0
which breaks compat with python 3.5. This pin however is now causing an
issue with scipy (since pip lacks a real dependency solver) because
the latest scipy requires numpy 1.19.0 to work downgrading numpy after
we've installed scipy makes scipy unusable. This commit fixes this by
installing a pinned scipy and numpy prior to building wheels on
windows 3.5 jobs to ensure we keep the versions matched at a version
works with python 3.5.
> Rework numpy cap and ensure scipy and numpy version are matched

- src/controllers/controller.hpp
- src/controllers/qasm_controller.hpp
- src/controllers/statevector_controller.hpp
- src/controllers/unitary_controller.hpp
- src/framework/matrix.hpp
- src/framework/results/data/data_container.hpp
- src/framework/results/data/pershot_data.hpp
2 unnecessary copies of `ExperimentResult` objects were happening during every execution due to lack of a move assignment operator for the class being auto-generated by the compiler.
This PR fixes this by explicitly passing in the result containers as references during the execution functions.
Here is an example comparing memory profiler for a density matrix snapshot.
Before fix (including before #794)
The small spikes are `matrix` copies and `ExperimentData` copies, the 2 large spikes are `ExperimentResult` copies.
After both fixes
The long ramp at the end (from 10-35sec in the above figure) is the Pybind11 `Result` object conversion which we should address in a future PR.
> Remove unnecessary copy of ExperimentResult objects

- contrib/standalone/qasm_simulator.cpp
- releasenotes/notes/improve-ave-snapshots-768767618ff00c2d.yaml
- src/controllers/controller_execute.hpp
- src/framework/results/data/average_data.hpp
- src/framework/results/data/average_snapshot.hpp
- src/framework/results/data/data_container.hpp
- src/framework/results/data/pershot_data.hpp
- src/framework/results/data/pershot_snapshot.hpp
- src/framework/results/experiment_data.hpp
- src/framework/results/experiment_result.hpp
- src/framework/results/result.hpp
Previously the mean and variance were returned as a copy of stored
accumulated data. This allows them to modify the stored data and return
a reference that can be moved into result containers which can help
avoid copies for large data objects like probability and density matrix
snapshots. To make this work it was also necessary to allow JSON conversion of
results to be non const.
Memory profiler comparisons for following circuit:
```py
nq = 14
circ = QuantumCircuit(nq)
circ.snapshot_density_matrix('state')
backend = QasmSimulator()
backend_options = {
"method": "density_matrix",
"fusion_enabled": False,
"truncate_enabled": False,
"max_parallel_threads": 1
}
qobj = assemble(circ, shots=1)
start = time.time()
result = backend.run(qobj, backend_options=backend_options).result()
stop = …
```
> Improve performance of average snapshots

- src/simulators/matrix_product_state/matrix_product_state_tensor.hpp
- src/simulators/matrix_product_state/svd.cpp
- test/terra/backends/test_qasm_simulator_matrix_product_state.py
There were failures in the SVD algorithm on Windows, because of low precision of floating point numbers on Windows. This fix resolves issue #773.
This PR replaces PR#797, which I couldn't merge, because of a CLA problem.
I found two problems when running the SVD algorithm.
1. Some of the computations in the SVD algorithm produce very small fractions (~10^-30). When comparing such a fraction to 0 on Windows, the precision of double floating point is not sufficient to detect that they are not 0. To resolve this, I added a parameter, `zero_threshold = 1e-50` for higher sensitivity of this comparison.
2. There was a validation check at the end of the SVD algorithm that was failing on high numbers of qubits, because the comparison was too sensitive (`1e-9`). I moved the check to `DEBUG` mode, …
> MPS: Fixed bug related to floating-point precision on Windows

- qiskit/providers/aer/pulse/controllers/pulse_controller.py
- src/open_pulse/numeric_integrator.cpp
- src/open_pulse/numeric_integrator.hpp
- src/open_pulse/ordered_map.hpp
- src/open_pulse/pulse_utils_bindings.cpp
- src/open_pulse/python_to_cpp.hpp
In normal ODE solving execution RHS function is called hundred of thousands of times. Conversion of function parameters from python to C++ are quite expensive and take most of the time. In this PR a functor is created to cache the converted parameters to C++ that do not change from call to call within the solver.
Testing with the tutorial [8_pulse_simulator_duffing_model](https://github.com/Qiskit/qiskit-tutorials/blob/master/legacy_tutorials/aer/8_pulse_simulator_duffing_model.ipynb):
- In the first simulation run (section 4.2), execution time goes down from **~10s** to **~2s**.
- In the second simulation (section 5.3, cell 15), execution times goes down from **~17s** to **~3.5s**.
- And finally, in the last simulation (section 5.3, cell 18), time goes down from **~40s** to **~8s**.
> Cache ODE RHS params

- qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py
- src/open_pulse/numeric_integrator.cpp
- test/terra/backends/test_pulse_simulator.py
This handles the first part of issue #736 , adding support/testing for the `Delay`, `ShiftPhase`, and `SetPhase` instructions.
~~This PR depends on the changes in PR #811.~~
- `Delay` didn't require any additional handling, as it doesn't enter the `qobj`. 
- A new test has been added to ensure delays are properly handled.
- Handling of phases in the function `experiment_to_structs` in `digest_pulse_qobj.py` and the function `chan_value` in `numeric_integrator.cpp` has been changed from relative to absolute. 
- Previously the data structure storing phase changes stored relative changes, as the `FrameChange` instruction (which has been replaced by `ShiftPhase`) was relative to the current phase. However, `SetPhase` is an absolute instruction, and therefore requires absolute phase handling. …
> Adding Delay, ShiftPhase, and SetPhase instruction handling to pulse simulator

- setup.py
Since qiskit-terra was added to the install time requirements list
in #593 we've been incorrectly listing qiskit-terra as a build time
dependency. That's because since #547 we've been listing our install
time requirements as also build time requirements (which at the time
that #547 was merged was true). This is still largely true as
qiskit-terra is the only install time requirement that isn't required
for building aer. However, forcing terra as a build time dependency
complicates the build process since it pulls in a large number of
external dependencies which may not be supported in a dedicated build
environment (see piwheels/packages#132 for an example of this). To
simplify the requirements for just building aer and to make it clear
what is actually required for building vs runtime …
> Remove terra from the setup_requirements list

- src/framework/operations.hpp
This allows edge case handling for an expval with zero coefficient. which was previously truncated to be an empty operator resulting in an error. This will now add a single identity Pauli term with zero coefficient so it can be simulated without error (even though this is inefficient as for a zero coefficient the output will always be zero)
> Fix error when passed an expval snapshot with zero coefficient

- requirements-dev.txt
The latest stevedore version 3.0.0 was released on July 10, 2020 and
introduced a new minimum version of importlib-metadata. Stevedore gets
pulled in as a 3rd level transitive dependency from stestr. However,
because of the lack of a pip dependency solver the version of
importlib-metadata is not getting updated. We started running pip check
in #668 to catch issues like this because pip will be introducing a
dependency solver at some point later this year so we wanted to be
prepared for this. To attempt to solve this issue this commit moves
stestr to the top of the requirements list to try and make pip behave
correctly and upgrade importlib-metadata before other dependencies
(which have a lower requirement). If this does not work a follow will
just pin stevedore in the constraints file …
> Move stestr to top of requirements list

- CMakeLists.txt
After merging SIMD support, we broke CUDA build.
This PR fixes the problem
We are adding a constraint -- From now onwards (until #843 is fixed) we have to build CUDA wheels packages with AVX2/FMA (SIMD) support, so users installing it will have to make sure their CPUs support these features (which is only a problem for very old CPUs).
> Adds AVX2/FMA flags to CUDA compilation

- qiskit/providers/aer/utils/noise_transformation.py
- requirements-dev.txt
- test/terra/noise/test_noise_transformation.py
This change addresses issue #779 which caused the Clifford-based transformations to fail, and so crashing a test. Currently there is no known solution to this problem (which might originate in changes in CVXPY) so we have to remove this test for now.
> Remove pin for broken CVXPY and update tests

- CONTRIBUTING.md
fix #845 by asking developers to first install OS-specific dependencies before installing from requirements-dev.txt.
This is intended to solve the potential issue of g++ not being available to build `cvxpy` which is listed in requirements-dev.txt.
- Separated the `dependencies` and `build` sections under each platform for easier linking.
- Reworded instructions so that users are pointed to platform specific instructions first.
> fix #845: restructure contributing.md

- test/terra/pulse/test_system_models.py
test_qubit_lo_from_configurable_backend has started failing recently
because of the fake backends in terra which caused the expectations to
be subtely off from the expected value. This commit reduces the
precision of the assertion between the expected value and the result to
only check 6 decimal places which should be sufficient for testing and
unblock the failure caused by the changes in terra.
> Reduce precision on test_qubit_lo_from_configurable_backend

- src/controllers/qasm_controller.hpp
- src/noise/quantum_error.hpp
- src/simulators/extended_stabilizer/chlib/core.hpp
- src/simulators/matrix_product_state/matrix_product_state_internal.cpp
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/qv_avx2.cpp
Replaced the 1 << to 1ULL << to fix compiler warnings.
Replaced the 1 << uint_t to 1ULL << uint_t, because uint_t is a 64 bit type.
1 << therefore does a shift on a 32 bit number, which then is converted to a 64 bit number.
Only simulation with more than 33 qubits would notice.
> Remove compiler warnings on the 1 shifts when compiling with windows.

- .github/workflows/main.yml
The GPU wheel build job was added in #775, but merged a bit too early.
There was still a test commit merged on the PR branch which was being
used to switch the job to run on every PR and commit and disable the
push to pypi. This commit reverts that test commit so that we're only
running the 2+ hour wheel building job when we tag a release and also
uncomments the section to publish the built wheels to pypi.
> Only run GPU wheel jobs on tags and publish to pypi

- releasenotes/notes/0.6/gate-fusion-4f208fd824ccaf3b.yaml
- src/controllers/statevector_controller.hpp
- src/controllers/unitary_controller.hpp
- test/terra/backends/statevector_simulator/statevector_fusion.py
- test/terra/backends/test_statevector_simulator.py
- test/terra/backends/test_unitary_simulator.py
- test/terra/backends/unitary_simulator/unitary_fusion.py
Adds the gate fusion circuit optimization used by the `QasmSimulator` to both the `StatevectorSimulator` and `UnitarySimulator` backends.
> Add gate fusion to StatevectorSimulator and UnitarySimulator

- releasenotes/notes/fix-statevector-precision-24350e9fd7368c24.yaml
- src/controllers/statevector_controller.hpp
Fixes bug in the StatevectorSimulator that caused it to always run as CPU with double-precision without SIMD/AVX2 support even on systems with AVX2, or when single-precision or the GPU method was specified in the backend options.
The template argument of the StatevectorController which specifies the simulator type was not being used. Instead the default double-precsion CPU qubitvector without AVX was always being used.
> Fix bug in StatevectorSimulator preventing AVX2, GPU, and single-precision simulation

- azure-pipelines.yml
The windows sdist install jobs have started failing on a permission
issue when trying to upgrade pip prior to installing from sdist. This
commit removes the pip upgrade because the base windows azure pipelines
image is now including pip 20.2.1 which is sufficiently new (being >19)
and upgrading isn't explicitly needed. This should avoid the potential
permissions issue replacing the pip.exe file on disk already.
> Remove pip upgrade from windows sdist job

- src/simulators/matrix_product_state/matrix_product_state_internal.cpp
In ``MPS::apply_cu1``, the operation was done on the input qubits instead of on the internal qubits.
This change was made in all other interface function following the change in PR #665.
> MPS: Bug in apply_cu1

- qiskit/providers/aer/version.py
This commit adds support to the aer version file for adding the git
sha1s to dev builds so that users can know which version of the code
they built against. This exists in the other qiskit elements but was
missing from aer.
> Add git sha1 to version string on dev builds

- .travis.yml
- azure-pipelines.yml
- releasenotes/notes/drop-py35-814876e9d7354a39.yaml
- requirements-dev.txt
- setup.py
- tox.ini
This commit drops support for running with python 3.5. It marks the
minimum supported version of the package as python 3.6, removes python
3.5 package pins, removes the 3.5 CI jobs, and removes the warning on
python 3.5. Looking at the PyPI stats since the deprecation period
started the number of users on Python 3.5 has diminished significantly,
but not disappeared. There were 359 downloads with pip from pypi out of
total of 18,980 total pip downloads in the last 30 days. Compared to the
roughly 10% figure when we deprecated Python 3.5.
Merging this means we can not release until after the documented EoL
date for Python 3.5 support of September 13. This shouldn't be a problem
because with Qiskit/qiskit-terra#4767 we will need to coordinate the
release of all the qiskit elements and are …
> Drop support for Python 3.5

- releasenotes/notes/fix-y-expectation-1ad355c31b4c3247.yaml
- src/simulators/stabilizer/stabilizer_state.hpp
- test/terra/reference/ref_snapshot_expval.py
Fix first part of #895.
I think this needs more tests.
~~I will write later.~~
I have written it.
> Fix evaluation y expectation

- cmake/conan_utils.cmake
- conan_settings/settings.yml
Conan won't officially support Apple Clang 12.0 as right now is in beta state. This PR updates 'settings.yml' automatically when building AER to support that version.
Closes #905
> Enable Appleclang 12 to work with Conan

- .github/workflows/main.yml
This commit adds a new job to run the qiskit tutorials in CI. The
tutorials are used as a form of upgrade testing to ensure that for key
examples Qiskit as a whole is N and N+1 releases. This caused friction
during the qiskit 0.20.0 release because the tutorials were never
updated to stop using deprecated code (or in the case of other elements
by merging backwards incompatible changes). To ensure there aren't any
surprises at the last minute when we run the tutorials with a proposed
new metapackage this commit adds a job to CI to ensure that they always
run with terra changes. It means for PRs that change an api (after a
deprecation cycle) the tutorial will need to be updated first. This will
ensure that users will have an upgrade path because CI in
qiskit/qiskit-tutorials runs with the …
> Add tutorials job to CI

- releasenotes/notes/kraus-noise-fusion-5577d4a38862e966.yaml
- src/controllers/qasm_controller.hpp
- src/framework/noise_utils.hpp
- src/framework/operations.hpp
- src/noise/noise_model.hpp
- src/noise/quantum_error.hpp
- src/transpile/fusion.hpp
- test/terra/backends/qasm_simulator/qasm_fusion.py
- test/terra/backends/test_qasm_simulator_density_matrix.py
~Depends on #889~
Adds a Kraus method to NoiseModel and gate fusion that allows applying the gate fusion optimization to noisy statevector simulations with Kraus noise.
Initial benchmarks show this gives a 3-9x performance improvement for noisy statevector simulations using the device noise model for 10-20 qubits.
Benchmarks run on Ubuntu desktop w/ AMD Ryzen 3700X and Geforce 1070.
> Kraus noise gate fusion method

- .github/workflows/main.yml
This commit makes 2 minor changes to the CI configuration to re-enable
building and running tests with the thrust OMP CPU backend. This was lost
in the migration to GHA and means we're not testing the thrust
simulation methods in CI which is a coverage hole. This fixes that
oversight. At the same time this commit adds the
QISKIT_TEST_CAPTURE_STREAMS env variable. Since Qiskit/qiskit-terra#3982
merged the base test class has had support for capturing STDOUT, STDERR,
and python logging as part of the test runs, which is especially
important for our CI configuration where we run tests in parallel. This
just enables this option so we'll have captured output streams
associated with each test method.
> Set OMP thrust method and capture streams in tests

- qiskit/providers/aer/noise/device/parameters.py
While working at a new provider and testing the possibility to use the noise model also for other devices, I found a copy-and-paste error in the value creation for the thermal relaxation routine. The problem is quite obvious when spotted and simply fixed too.
The variable to check for the property `value` should for obvious reasons be `freq_params` instead of `t2_params`. 
I would have changed or added tests, but since this module is not tested at all, starting a test module would be a major change to the code instead of one simple modification of one line of code. I think it could be good to test this part too, but this should be a new issue / PR by itself.
> Fix a copy-paste-error in the noise model> it checks the wrong variable.

- test/terra/backends/statevector_simulator/statevector_basics.py
- test/terra/backends/unitary_simulator/unitary_basics.py
- test/terra/common.py
- tools/verify_wheels.py
A recent Terra PR caused an incorrect global_phase value to be set in qobj headers for some circuits. This was causing tests to fail which tested that output unitary and statevectors were phase equal. This PR changes the failing tests to only check that hte output is equal up to global phase until the Terra issue can be fixed.
Related terra issue: https://github.com/Qiskit/qiskit-terra/issues/5125
> Fix test failures due to qiskit-terra #5125

- .github/workflows/main.yml
- .github/workflows/wheels.yml
- azure-pipelines.yml
This commit is an attempt to start building 32bit binaries in CI for
publishing at release time (and the corresponding wheel compile jobs).
This is primarily an issue for windows were a large number of users are
running with a win32 python binary and aer fails to install from wheel
because there is not 32bit binary available.
> Enable building 32bit binaries in wheel jobs

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/superoperator/superoperator_state.hpp
- test/terra/backends/qasm_simulator/qasm_standard_gates.py
Adds some things missed in #951 
* Adds missing delay to Backend basis gates to simulators
* Adds cy to density matrix and superop simulators
> Add missing basis gates

- test/terra/backends/test_pulse_simulator.py
- test/terra/common.py
- test/terra/extensions/test_snapshot_density_matrix.py
- test/terra/extensions/test_snapshot_expectation_value.py
- test/terra/extensions/test_snapshot_probabilities.py
- test/terra/extensions/test_snapshot_stabilizer.py
- test/terra/extensions/test_snapshot_statevector.py
- test/terra/noise/test_noise_inserter.py
- test/terra/noise/test_noise_transformation.py
- test/terra/pulse/de/test_de_methods.py
- test/terra/pulse/de/test_type_utils.py
- test/terra/pulse/test_duffing_model_generators.py
- test/terra/pulse/test_system_models.py
- test/terra/test_python_to_cpp.py
We're currently facing periodic job timeouts in CI that appear to be
caused by a test method getting stuck and not finishing. To debug this
we first need to figure out which test is getting stuck. This commit
adds a test fixture to the base test class's setUp method. This will
signal to stop the method after 120 secs and raise a TimeoutException.
> Add timeout fixture to test setup

- test/terra/common.py
- test/terra/extensions/test_wrappers.py
This commit fixes a few issues in #955 in the hopes of further debugging
our test job timeouts in CI. The first change made is the timeout
fixture is changed from gentle=True to gentle=False. The true case is
generally preferable because it sets the signal handler to raise an
exception which doesn't interrupt test execution however, if a runner
process is stuck it might not work because the signal handling never
gets invoked. gentle=false will just have the sigalarm kill the process.
Additionally, in #955 one test class was missed and was using
unittest.TestCase instead of QiskitAerTestCase, which meant that the
tests in those classes could still get stuck since the fixture was not
initialized for that class.
> Turn off gentle timeout and use common test class everywhere

- test/terra/backends/qasm_simulator/qasm_delay_measure.py
- test/terra/backends/qasm_simulator/qasm_fusion.py
- test/terra/backends/qasm_simulator/qasm_initialize.py
- test/terra/backends/qasm_simulator/qasm_noise.py
- test/terra/backends/qasm_simulator/qasm_thread_management.py
- test/terra/backends/qasm_simulator/qasm_truncate.py
- test/terra/backends/statevector_simulator/statevector_basics.py
- test/terra/backends/test_qasm_simulator.py
- test/terra/backends/test_qasm_simulator_density_matrix.py
- test/terra/backends/test_qasm_simulator_matrix_product_state.py
- test/terra/backends/test_qasm_simulator_stabilizer.py
- test/terra/backends/test_qasm_simulator_statevector.py
- test/terra/backends/unitary_simulator/unitary_basics.py
- test/terra/reference/ref_multiplexer.py
- test/terra/reference/ref_non_clifford.py
This fixes certain tests were causing the GHA CI tests to fail to complete. 
* Removes some redundant CCX and T gate tests that were slow for the extended stabilzier simulator
* Sets tests to run single threaded (except for thread management tests) to not conflict with thread usage of test library
* Reduces shot number of certain tests that don't use measurement sampling
* Reduces the number of qubits in fusion tests now that they must also be run on the density matrix simulator.
* Changes tests to to use terra circuit library QFT and QV functions instead of custom ones.
> Fix test performance

- .github/workflows/main.yml
- test/terra/extensions/test_wrappers.py
Changes the order of test dependencies in GHA to attempt to reduce bottlenecks. A local pip cache is also added to the job config.
* The `wheel` and `sdist` tests were also set to require the `lint` test to pass
* The `wheel` test was removed as dependencies of the `tests` and `tutorial` actions since these tests takes a long time to run and block other tests running.
> Refactor GHA config and attempt to fix pickle tests

- .github/workflows/main.yml
In #960/#959 we added caching for the local pip cache in the GHA CI
jobs. However it was treating all instances of a job in a matrix as
having a shared cache. This was causing a lower cache hit rate on wheels
because they're often python version specific. This commit attempts to
fix this by adding the python version to the cache key, meaning for jobs
that run on multiple python versions it will only use the cache if its
for the job on the same python version.
> Add python version to GHA pip cache key

- releasenotes/notes/validate-memory-statevector-d1b4fc48b002856f.yaml
- src/controllers/statevector_controller.hpp
- src/controllers/unitary_controller.hpp
Closes #968 
Add missing available memory checks for the StatevectorController and UnitaryController in the C++ code. These throw an exception if the memory required to simulate the number of qubits in a circuit exceeds the  available memory of the system.
This C++ memory check was only run for the QasmSimulator, while the other two simulators did the error checking in Python before running the C++ code. However the python checks are disabled if a qobj is run with `validate=False` which is the default setting.
> Add available memory checks for Statevector and Unitary simulators

- releasenotes/notes/fix-snapshot-copy-54ee685094d1e261.yaml
- src/framework/results/data/average_snapshot.hpp
- src/framework/results/data/pershot_snapshot.hpp
Fixes a bug where snapshot data was always copied from C++ to Python rather than moved where possible. This will halve memory usage and improve simulation time when using large statevector or density matrix snapshots.
> Fix bug where snapshots are returned by copy instead of reference

- qiskit/providers/aer/extensions/snapshot_expectation_value.py
- qiskit/providers/aer/extensions/snapshot_probabilities.py
- releasenotes/notes/deprecate-snapshot-variance-7d02188deacf9a08.yaml
The `variance` kwarg of Snapshot instructions has been deprecated. This function computed the sample variance in the snapshot due to noise model
sampling, not the variance due to measurement statistics so was often
being used incorrectly. If noise modeling variance is required single shot
snapshots should be used so variance can be computed manually in
post-processing.
Deprecation will allow closing #903 in future release.
> Deprecate snapshot variance

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- qiskit/providers/aer/extensions/snapshot_density_matrix.py
- qiskit/providers/aer/extensions/snapshot_expectation_value.py
- qiskit/providers/aer/extensions/snapshot_probabilities.py
- qiskit/providers/aer/extensions/snapshot_stabilizer.py
- qiskit/providers/aer/extensions/snapshot_statevector.py
- qiskit/providers/aer/noise/device/basic_device_model.py
- qiskit/providers/aer/noise/noise_model.py
- qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py
- qiskit/providers/aer/pulse/system_models/hamiltonian_model.py
- qiskit/providers/aer/pulse/system_models/pulse_system_model.py
Qiskit/qiskit-terra#5086 seemd to break pylint testing by preventing the Aer package from being found by pylint without building and installing.
This tries to fix the issue by replacing all absolute imports in Aer with relative module imports. This is a work around until general namespace packaging issues are implemented to move all of Aer into its own namespace.
#979 fixes the issue by building and installing Aer in the lint module, however this means lint passing is dependent on Aer being built via sdist, which is a separate test usually run after linting.
> Alternate try to fix aer lint failure by installing aer 

- azure-pipelines.yml
Azure pipelines recently updated their windows images with a newer
version of conda. This has started causing CI failures when the wheel
jobs run virtualenv to build an isolated python env to test that the
built wheels work for a user without any dependencies pre-installed.
This commit fixes this by abandoning the use of virtualenv and relying
on conda to create an isolated test environment.
A follow up from here will be to investigate abandoning the use of conda
from the CI jobs. It adds needless complexity and was originally added
to ensure we could easily install cvxpy and cvxopt on windows which
hopefully shouldn't be a problem anymore.
> Fix CI failures because of azure image update

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- releasenotes/notes/basis-gates-acbc8a1a52a49413.yaml
- src/noise/noise_model.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/extended_stabilizer/ch_runner.hpp
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
- src/simulators/extended_stabilizer/gates.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/matrix_product_state/matrix_product_state_internal.cpp
- src/simulators/matrix_product_state/matrix_product_state_internal.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/superoperator/superoperator_state.hpp
- src/simulators/unitary/unitary_state.hpp
- test/terra/backends/qasm_simulator/qasm_standard_gates.py
- test/terra/backends/statevector_simulator/statevector_gates.py
- test/terra/backends/unitary_simulator/unitary_gates.py
* Adds `UGate` to basis gate of simulators that support it (Closes #988)
* Adds `SXGate` and `PGate` support to MPS simulator and extended stabilizer simulator, so they now can be run on all simulators except stabilizer.
> Add missing standard gate basis gates

- .github/CODEOWNERS
- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/backends/pulse_simulator.py
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- releasenotes/notes/fusion-threshold-33127b9b4e219640.yaml
- src/controllers/qasm_controller.hpp
- src/controllers/statevector_controller.hpp
- src/controllers/unitary_controller.hpp
- src/transpile/fusion.hpp
- test/terra/backends/qasm_simulator/qasm_fusion.py
- test/terra/backends/statevector_simulator/statevector_fusion.py
- test/terra/backends/test_config_pulse_simulator.py
- test/terra/backends/unitary_simulator/unitary_fusion.py
Changes default gate fusion thresholds for improved performance, and fixes default max qubit size for fusion bugs in density matrix and noise fusion introduced in #927 
This is more of a quick fix for the 0.7 release, and a more complete refactor of fusion logic can be tackled in #986 
* Changes `"fusion_threshold"` backend option to apply fusion when the number of qubits is above the threshold, not equal or above the threshold, to match the behaviour of the OpenMP qubit threshold parameter.
* Changes the default value of "fusion_threshold" from 20 to 14 for the QasmSimulator (statevector) and StatevectorSimulator, and from 10 to 7 for the UnitarySimulator and QasmSimulator (density matrix).
* Allows fusion for MPS if fusion enabled is specified in config. Default for MPS is still fusion …
> Fix fusion thresholds and defaults

- .github/workflows/wheels.yml
In the recent aer 0.7.0 release we noticed that in the migration of CI
jobs to github actions in #881 the job to create and publish and sdist
at release time was lost. This commit corrects this and adds a new job
to create and publish to pypi the qiskit-aer sdist at release time.
> Add missing sdist release job

- releasenotes/notes/basis_gate_error_msg-04862cbd47f5f57f.yaml
- src/framework/opset.hpp
Fixes bug in the error message returned when a circuit contains unsupported simulator instructions. Previously some supported instructions were also being listed in the error message along with the unsupported instructions.
Fixes #1004 
Fixes bug in how sets of unsupported instructions were constructed. The previous method didn't work properly with `std::unordered_set`.
> Fix bug in unsupported instructions error message

- qiskit/providers/aer/aerprovider.py
- releasenotes/notes/aer-provider-instance-38b472f3ea541977.yaml
- test/terra/extensions/test_wrappers.py
Updates AerProvider to return a new backend instance each time `backend` or `get_backend` is called. This is so that if the backend instance is modified with `set_options` it won't persist pass the scope of where that backend object is used.
> Fix Aer provider to return new backend instances with backends/get_backend.

- contrib/standalone/qasm_simulator.cpp
- qiskit/providers/aer/backends/wrappers/bindings.cc
- src/framework/avx2_detect.hpp
Move avx2 needed headers inclusion from qasm_simulator.cpp and bindings.cc to avx2_detect.hpp, where are actually used.
> Refactor where avx2 needed headers are included

- azure-pipelines.yml
A recent change in the disk layout of the azure pipelines windows images
has moved where the pip cache is stored on disk. This breaks the cache
step in the job which tries to upload from the old path to a share cache
between jobs. This commit removes the cache step to unblock CI since
without this all CI jobs are blocked while try to upload the local pip
cache. While this will increase the run time for the job and network
traffic (which means the jobs are more prone to network errors), it is
still better than a non-working CI.
> Remove cache step from azure-pipelines windows jobs

- .github/workflows/main.yml
- pyproject.toml
- requirements-dev.txt
- setup.py
`urllib3` 1.26.0 has been released, causing a dependency when installing conan (coming form `requests` lib).
Here I add `urllib3` add as a dependency and constraint it to <1.26 to avoid this problem.
The issue has been already reported to `Conan` team by some users: https://github.com/conan-io/conan/issues/8041.
Here https://github.com/conan-io/conan/pull/8042 they mention that `requests` lib version 2.25 (to be released ~~today~~ tomorrow: https://github.com/psf/requests/issues/5654) will be compatible with this `urllib3` 1.26. In the meantime we can use this ugly fix.
> Fix conan dependency problem with urllib3

- .github/workflows/wheels.yml
In the recent aer 0.7.0 release we noticed that in the migration of CI
jobs to github actions in #881 the job to create and publish and sdist
at release time was lost. This commit corrects this and adds a new job
to create and publish to pypi the qiskit-aer sdist at release time.
Backported from #998 
(cherry picked from commit cb5f41400f07328b9d4328b39bae3e2d8006f1d7)
> Add missing sdist release job (#998)

- .github/workflows/main.yml
This commit updates the version of the setup-msbuild action we use in
the windows ci jobs. This action is used to setup the compilers in the
windows environment, but the version we were using was relying on a
previously deprecated and now removed feature in github actions and has
now stopped working. By updating the version we should unblock CI.
> Update setup-build action version

- qiskit/providers/aer/backends/backend_utils.py
use `shots=1` to get available methods of qasm simulator
`available_methods` in [`backend_utils`](https://github.com/Qiskit/qiskit-aer/blob/c36dc29c842276d0706f164b56725734a974645e/qiskit/providers/aer/backends/backend_utils.py) uses the default number of shots. It should be `1` from performance perspective.
> use single shot to find available methods

- releasenotes/notes/fix-omp-nested-9d120cd1a08725ab.yaml
- src/controllers/controller.hpp
Fixes bug with nested OpenMP flag getting set to True when it shouldn't have
* The condition was checking parallel shots or parallel state update, when it should have been parallel shots or parallel experiments.
* Explicitly disable nested openmp when the above condition isn't satisfied
> Fix bug with nested omp being applied incorrectly

- src/controllers/controller.hpp
- src/misc/clang_omp_symbols.hpp
- src/misc/gcc_omp_symbols.hpp
On mac and linux use `omp_set_max_active_levels` instead of `omp_set_nested`
OpenMP has deprecated `omp_set_nested` for `omp_set_max_active_levels` which was introduced in OMP 3.0. This means it isn't available on Windows (OMP 2.0) so we still need to use the old function call there.
> Remove deprecated usage of omp_set_nested

- .github/workflows/build.yml
- .github/workflows/deploy.yml
The default version of the manylinux2010 docker images used by
cibuildwheel are trying to use a nonexistent yum repository now that
centos 6 is eol. The latest version of the docker image has been
updated. This commit manually sets the docker image to the latest
version to unblock CI. This PR can be reverted when cibuildwheel
releases a new version that bumps their default manylinux2010 version
(see joerick/cibuildwheel#472 for more details on that).
> Bump manylinux2010 docker image for wheel jobs

- .github/workflows/docs.yml
- qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py
- requirements-dev.txt
- test/terra/backends/test_config_pulse_simulator.py
- test/terra/noise/test_noise_transformation.py
The cvxpy packaging (more specifically scs) is causing issues in CI for
us because since it is incorrectly trying to install numpy from a
pre-release package which does not support python 3.6. The nature of
this issue is difficult to pin because it's not using pip to install
numpy. Since cvxpy is only used in a single place, noise
transformations, instead of trying to workaround these scs packaging
issues this commit just restricts the test requirements on cvxpy to only
match pytho 3.7 or 3.8. If cvxpy is not installed the noise
transformation tests will now skip instead of fail.
Co-authored-by: Daniel Puzzuoli <dan.puzzuoli@gmail.com>
> Restrict cvxpy testing to python 3.7 and 3.8

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/tests_linux.yml
- .github/workflows/tests_mac.yml
- .github/workflows/tests_windows.yml
- azure-pipelines.yml
- releasenotes/notes/add-python3.9-83b3b4e5c3d59571.yaml
- setup.py
- test/terra/common.py
- tox.ini
This commit adds official python 3.9 support to qiskit-aer. This
includes CI, release notes, and package metadata.
Fixes #1067
Upstream dependencies that need Python 3.9 support:
~- [ ] osqp~ (sidestepped by skipping cvxpy tests for py39)
> Add Python 3.9 support

- test/terra/backends/test_qasm_simulator_extended_stabilizer.py
The test `test_sparse_output_probabilities` is failing in some macos runs. As it has a non zero `delta` I assume is non deterministic, so I incremented delta.
> Increase delta in a non deterministic test to avoid CI failing.

- .github/workflows/deploy.yml
For the 0.7.2 release the GPU wheel build failed because of recent
issues around the epel yum repository with centos 6. These issues were
caused by a configuration ordering problem with an older manylinux2010
docker image. Basically we were trying to manually configure EPEL too
late and cuda installation failed, but newer docker images fix the epel
configuration so we no longer need to do it manually. This commit fixes
the gpu wheel jobs by using the latest docker image version and removing
the manual centos 6 epel configuration.
> Fix GPU wheel job

- releasenotes/notes/fix-c-if-large-register-79d6649395e57ff5.yaml
- src/framework/creg.hpp
- src/framework/utils.hpp
- test/terra/backends/qasm_simulator/qasm_conditional.py
- test/terra/backends/statevector_simulator/statevector_basics.py
- test/terra/reference/ref_conditionals.py
Added fix for bug where executing conditional instruction with `c_if` on the `BasicAer` backend  either resulted in a crash or incorrect result for registers larger than or equal to 64-bits. 
Fixes #1077 
The `hex2bin` routine in `util.hpp` used 8 hex-character instead for 16 for the block size to process in 64-bit chunks. Also added check to avoid invoking `std::stoull` with empty string, which was causing the crashes.
In the implementation of `ClassicalRegister::apply_bfunc,` truncated the leading zeros before comparing the masked register value with the target value for the conditional.
> Fix condtional instructions using `c_if` not working for reg of size>=64 on BasicAer backend

- .github/workflows/tests_linux.yml
- .github/workflows/tests_mac.yml
- .github/workflows/tests_windows.yml
Increases timeout of unit tests, adds more time for slower MacOS tests.
* Increase linux and windows timeout from 25min to 30 min
* Increase macos timeout from 25 min to 40 min
> Increase CI test timeouts

- qiskit/providers/aer/noise/noise_model.py
- qiskit/providers/aer/pulse/system_models/pulse_system_model.py
- setup.py
Qiskit/qiskit-terra#5086 introduced v2 provider with new classes `Backend`, `Job`, and `Provider`. `ibmq-provider` is switching to v2 provider interface, and this PR ensures that `Backend` will be accepted in addition to `BaseBackend`.
> Allow v2 provider backends

- qiskit/providers/aer/noise/noise_model.py
- releasenotes/notes/fix-noise-basis-gates-ecdfa43394ff78e3.yaml
Fixes #1107 
Fixes bug in `NoiseModel.from_backend` and `QasmSimulator.from_backend` where `basis_gates` was set incorrectly for IBMQ devices with basis gate set ``['id', 'rz', 'sx', 'x', 'cx']``. Now the noise model will always have the same basis gates as the backend basis gates regardless of whether those instructions have errors in the noise model or not.
> Fix noise model basis_gates when constructing from device

- qiskit/providers/aer/backends/qasm_simulator.py
- releasenotes/notes/fix-backend-noise-model-f22e9d6254d70852.yaml
- test/terra/backends/qasm_simulator/qasm_method.py
Fixes bugs with automatically setting configuration basis gates when using custom configurations (in from backend), methods, and noise models options.
Fixes issue with setting :class:`~qiskit.providers.aer.QasmSimulator`
basis gates when using ``"method"`` and ``"noise_model"`` options
together, and when using them with a simulator constructed using
:meth:`~qiskit.providers.aer.QasmSimulator.from_backend`. Now the
listed basis gates will be the intersection of gates supported by
the backend configuration, simulation method, and noise model basis
gates. If this intersection of the noise model basis gates and 
simulator basis gates is empty a warning will be logged.
> Fix bugs in automatic updates of simulator configuration basis gates

- azure-pipelines.yml
In 0.7.3 we backported the Python 3.9 support PR to include builds for
running Aer on Python 3.9 in that release. However, as was discovered
during that release process the wheels for windows (both 64bit and
32bit) on 3.9 were missing. We never added 3.9 to the version list for
the wheels to build. This commit fixes that oversight so that we ensure
that we're building Python 3.9 wheels on windows too.
> Add Windows Python 3.9 release wheel builds

- qiskit/providers/aer/pulse/controllers/mc_controller.py
Added qutip copyright blurb to the mc_controller file in the pulse simulator.
> adding qutip copyright to mc_controller

- src/open_pulse/python_to_cpp.hpp
- src/open_pulse/test_python_to_cpp.cpp
- src/open_pulse/test_python_to_cpp.hpp
Removed some direct calls to the `numpy C API` by using `Pybind11` instead.
`Pybind11` relies on python buffer protocol and does not depend on
`numpy` headers.
This only fix the problem for master, where all `cython` code has been removed, so it won't solve 0.7.4 issue #1120.
> Fix numpy ABI incompatibility when building with numpy 1.20

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/library/__init__.py
- qiskit/providers/aer/library/save_data.py
- qiskit/providers/aer/library/save_density_matrix.py
- qiskit/providers/aer/library/save_expectation_value.py
- qiskit/providers/aer/library/save_statevector.py
- releasenotes/notes/save-data-instructions-24b127612c9f6502.yaml
- src/framework/operations.hpp
- src/framework/results/data/data.hpp
- src/framework/results/data/mixins/data_cdict.hpp
- src/framework/results/data/mixins/data_cmatrix.hpp
- src/framework/results/data/mixins/data_cvector.hpp
- src/framework/results/data/mixins/pybind_data_cdict.hpp
- src/framework/results/data/mixins/pybind_data_cmatrix.hpp
- src/framework/results/data/mixins/pybind_data_cvector.hpp
- src/framework/results/data/pybind_data.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/extended_stabilizer/ch_runner.hpp
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/matrix_product_state/matrix_product_state_internal.cpp
- src/simulators/matrix_product_state/matrix_product_state_internal.hpp
- src/simulators/state.hpp
- src/simulators/statevector/statevector_state.hpp
- test/terra/backends/qasm_simulator/qasm_save.py
- test/terra/backends/qasm_simulator/qasm_save_density_matrix.py
- test/terra/backends/qasm_simulator/qasm_save_expval.py
- test/terra/backends/qasm_simulator/qasm_save_statevector.py
Adds support for new `SaveStatevector` and `SaveDensityMatrix` instructions as outlined in #1062. These function can be used with the circuit method `save_statevector` (`save_density_matrix`) which are automatically monkey patched when importing the Aer provider.
~Depends on #1101~
By default this instruction saves a single statevector (unlike snapshot_statevector which saves a list by default). For a multi-shot simulation this will be the statevector of the last shot. It also supports 
* saving as a list of statevectors for each simulated shot (`pershot=True`)
* saving a single or list of statevectors conditional on any classical register values from preceding measurements (`conditional=True`)
```python
import qiskit
from qiskit.providers.aer import QasmSimulator
qc = …
```
> Add ``SaveStatevector`` and ``SaveDensityMatrix`` instructions

- setup.py
It seems that when forcing scikit-build to use Visual Studio 2019 through
`CMAKE_GENERATOR` env var, it is always assuming it is building for 64 bits,
even if you are working with `Python` 32 bits. More over, it doesn't honor the
`CMAKE_GENERATOR_PLATFORM` env variable, so no option to use the proper 32 bits
compiler. In this commit we check if we are in a `Win` 32 bit `Python` environment
and pass `CMAKE_GENERATOR_PLATFORM=Win32` directly to `CMake`.
> Pass CMAKE_GENERATOR_PLATFORM thorugh scikit_build in win32 builds

- qiskit/providers/aer/extensions/snapshot.py
- qiskit/providers/aer/library/save_data.py
Add `_directive` attribute to save instructions to make compatible with Terra transpiler/unroller/drawer.
On-hold until Terra PR https://github.com/Qiskit/qiskit-terra/pull/5701 is merged.
> Add _directive attr to Save instruction

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- src/controllers/controller.hpp
Allow Aer to use all the system memory.
This PR fixes #1114.
Currently, Aer uses the half of system memory (`sysconf(_SC_PAGE_SIZE) * sysconf(_SC_PHYS_PAGES) / 2`),  but `BasicAer` allows to use the all (`psutil.virtual_memory()`).
This PR changes the default value of `max_memory_mb` to all the system memory.
> change default max_memory_mb from half to full system memory

- .travis.yml
This commit adds a new CI job to publish precompiled binary wheels for
linux on aarch64 (arm64). Since the latest numpy and scipy releases now
publish wheels for aarch64 we can run CI jobs to do the same since we
won't be spending all our CI time budget compiling upstream dependencies
from source anymore (terra 0.17.0 will be publishing wheels aarch64
wheels too). This enables users running on linux aarch64 systems
to install qiskit without having to compile everything from source
anymore. To build these wheels this commit uses travis, which is the
only CI system that offers non-x86 nodes.
> Add arm64 release wheel jobs

- qiskit/providers/aer/library/__init__.py
- qiskit/providers/aer/library/save_amplitudes.py
- qiskit/providers/aer/library/save_data.py
- qiskit/providers/aer/library/save_density_matrix.py
- qiskit/providers/aer/library/save_expectation_value.py
- qiskit/providers/aer/library/save_probabilities.py
- qiskit/providers/aer/library/save_stabilizer.py
- qiskit/providers/aer/library/save_statevector.py
- qiskit/providers/aer/library/save_unitary.py
- test/terra/backends/qasm_simulator/qasm_save_amplitudes.py
- test/terra/backends/qasm_simulator/qasm_save_density_matrix.py
- test/terra/backends/qasm_simulator/qasm_save_expval.py
- test/terra/backends/qasm_simulator/qasm_save_probabilities.py
- test/terra/backends/qasm_simulator/qasm_save_stabilizer.py
- test/terra/backends/qasm_simulator/qasm_save_statevector.py
- test/terra/backends/unitary_simulator/unitary_save.py
- test/terra/extensions/test_save_amplitudes.py
- test/terra/extensions/test_save_expval.py
Changes order of save instruction args to make the first positional arg `key` into a kwarg `label` with a default string value specific to each save instruction type.
This PR changes the format of the recently added save instructions to make the positional `key` arg a `label` kwarg. It also gives a default label value to each instruction so that they can be used without specifying a label.
This allows use such as `circ.save_statevector()`, which will return result `{"statevector": state_vec}` and `circ.save_statevector(label='psi')` which will return result as `{"psi": state_vec}`.
Note that duplicate labels in a circuit raise an exception on execution, so if two of the same save instruction are used in a circuit non-default labels must be specified in the additional instructions. A note …
> Add default save instruction labels

- src/simulators/statevector/chunk/chunk.hpp
- src/simulators/statevector/chunk/chunk_container.hpp
- src/simulators/statevector/chunk/device_chunk_container.hpp
- src/simulators/statevector/chunk/host_chunk_container.hpp
- src/simulators/statevector/qubitvector_thrust.hpp
- src/simulators/unitary/unitarymatrix_thrust.hpp
Fixes a bug in CopyIn/CopyOut operations where out of bounds array elemets
were accessed.
`QubitvectorThrust` has a number of qubits `num_qubits`. When `move_to_vector` or
`copy_to_vector` functions are called a temporary array or vector of size
(1 << `num_qubits`) is created and passed to chunk_ CopyOut function. There, a number
of elements (1 << `chunk_qubits_`) of the underlying structure are copied to
this array/vector. The problem is that `chunk_qubits_` can be larger that `num_qubits`,
accessing values in the array or vector out of bounds. This is what was making
PR #1132 failing in CI.
`chunk_qubits_` is initialized from maximum number of qubits in a list of circuit whereas `num_qubits` is initilaized as the number of qubits of a given circuit.
> Fix out of bounds array access.

- src/framework/linalg/vector.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/density_matrix/densitymatrix_state_chunk.hpp
- src/simulators/density_matrix/densitymatrix_thrust.hpp
- src/simulators/statevector/chunk/chunk.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/statevector/statevector_state_chunk.hpp
- src/simulators/unitary/unitary_state.hpp
- src/simulators/unitary/unitary_state_chunk.hpp
- src/simulators/unitary/unitarymatrix_thrust.hpp
- src/transpile/cacheblocking.hpp
- The chunk objects hold a shared_ptr to a chunk_container and the chunk_container
holds shared_ptrs to the chunks. This creates a circular reference problem which
avoids the destructions of chunks and chunk_containers.
- Some override warnings fixed
- Set other AER::Vector size to zero when performing moving operations.
> Fix memory_leak due to shared_ptr circular references.

- src/simulators/density_matrix/densitymatrix.hpp
- src/simulators/density_matrix/densitymatrix_state_chunk.hpp
- src/simulators/density_matrix/densitymatrix_thrust.hpp
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/qubitvector_thrust.hpp
- src/simulators/statevector/statevector_state_chunk.hpp
- test/terra/backends/qasm_simulator/qasm_save_expval.py
Somewhere in the refactors since the 0.7 release he way the `expval_pauli` function was removed from the density matrix method leading to incorrect computation of expectation values for noisy circuits. This restores the density matrix specific implementation of the expval_pauli function.
On master expval_pauli was actually computing `Tr[O.rho^2]` instead of `Tr[O.rho]`, so was incorrect unless the simulation was ideal.
This PR also adds some extra tests including noise for testing expvals on the density matrix simulators.
@doichanj can you check the chunk versions still work in the way I updated them?
> Fix density matrix expval_pauli

- src/misc/warnings.hpp
- src/misc/wrap_thrust.hpp
- src/simulators/statevector/chunk/chunk_container.hpp
Thrust headers are included from chunk_container. Not all warnings could
be disabled for gcc with our usual method (because a known issue in
gcc). Thus, I've made a wrapper including all the needed thrust
libraries and set it as system header in the case of gcc, which really
disables all warnings.
> Disable all warnings emitted from thrust headers

- qiskit/providers/aer/backends/qasm_simulator.py
Adds missing `t` and `tdg` basis gates list for extended stabilizer simulator method.
Note that these gates were always supported, but were being unrolled to u1 gates previously due to the name strings being missing from the backends basis gates.
> Fix extended stabilizer method basis gates

- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- qiskit/providers/aer/library/__init__.py
- qiskit/providers/aer/library/save_state.py
- releasenotes/notes/save-data-instructions-24b127612c9f6502.yaml
- src/framework/operations.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/density_matrix/densitymatrix_state_chunk.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/state.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/statevector/statevector_state_chunk.hpp
- src/simulators/superoperator/superoperator_state.hpp
- src/simulators/unitary/unitary_state.hpp
- test/terra/backends/qasm_simulator/qasm_save.py
- test/terra/backends/qasm_simulator/qasm_save_state.py
Adds `SaveState` instruction, with `save_state` circuit method.
This saves the state of the simulator in the appropriate format for the simulation method (ie. statevector, density_matrix, unitary, stabilizer).
Note that for density matrix simulation this is treated as a single data type like for the other simulation methods, rather than average as with the regular `save_density_matrix` instruction. Hence it is always the state of the simulator at the final shot (unless pershot=True and it is a list of states for each shot).
> Add general SaveState instruction

- qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py
- qiskit/providers/aer/pulse/controllers/pulse_controller.py
- qiskit/providers/aer/pulse/controllers/pulse_de_solver.py
- test/terra/backends/test_pulse_simulator.py
- test/terra/pulse/controllers/__init__.py
- test/terra/pulse/controllers/test_pulse_controller.py
- test/terra/pulse/de/test_de_methods.py
- test/terra/pulse/de/test_type_utils.py
Closes #1179
Follows logic as suggested in #1179 by @nkanazawa1989 : a global `qubit_lo_freq` field is populated as before, either from the qobj config or from the Hamiltonian. When simulating a specific schedule, if no `qubit_lo_freq` is present in the schedule config, the global default is used, otherwise the schedule's `qubit_lo_freq` is used.
When each schedule is parsed (in dict format in `experiment_to_struct`) it checks if it has a `'config'` key, and if so, will check for a `qubit_lo_freq` field. If it's there, this will be stored in the "experiment struct" dictionary, otherwise, the `struct['qubit_lo_freq']` is set to `None`. When setting up the RHS function before solving, if `struct['qubit_lo_freq'] is not None`, this value will be subbed in, otherwise the default is …
> Add reading of qubit_lo_freq from pulse Schedule config

- .github/workflows/tests_linux.yml
- .github/workflows/tests_mac.yml
- .github/workflows/tests_windows.yml
- qiskit/providers/aer/backends/aer_simulator.py
- qiskit/providers/aer/backends/aerbackend.py
- src/controllers/aer_controller.hpp
- test/terra/backends/aer_simulator/test_options.py
- test/terra/extensions/test_wrappers.py
* Adds missing `seed_simulator` option to `AerSimulator` default options
* Fixes method name returned in AerController metadata to not include the device as is done with QasmController.
* Adds some basic tests for method, device, and seed_simulator options
> Fix AerSimulator options

- src/controllers/aer_controller.hpp
- src/controllers/controller.hpp
GPU methods are disabled if no device is available. An exception is thrown early in the process if no device is available.
Fixes the deploy failure we had in latest 0.8.0 release.
> Disable GPU methods if no device is available

- releasenotes/notes/fix-initialize-sampling-b6948e39112f6a46.yaml
- src/controllers/aer_controller.hpp
- src/controllers/qasm_controller.hpp
- src/framework/circuit.hpp
- test/terra/backends/qasm_simulator/qasm_initialize.py
If initialize is the first instruction in a circuit, or is defined across the full width of a circuit, it is deterministic and hence is compatible with the measurement sampling optimization
Fixes #1210
> Allow measure sampling with compatible initialize

- releasenotes/notes/fix-normalize-statevector-extended-stabilizer-3811f44e003099f3.yaml
- src/simulators/extended_stabilizer/ch_runner.hpp
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
- test/terra/backends/aer_simulator/instructions/test_save_statevector.py
Fix issue #1196. Since the statevector method of CHSimulator::Runner already computes the inner product with all 2^n computational basis states we can use this information to exactly compute the norm rather than using the fast norm estimation algorithm.
Since the CHSimulator::Runner::statevector does not use the fast norm estimation algorithm anymore it does not need to take the parameters relating to it. This required changes everywhere this method is called which seems to just be in extended_stabilizer_state.hpp.
I don't think this change requires any additional tests unless we want to add a test that that confirms the output of this method is normalized.
> Normalize statevector save and snapshot for extended stabilizer method 

- qiskit/providers/aer/backends/aer_simulator.py
- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/backends/qasm_simulator.py
- releasenotes/notes/basis-gates-perf-aba3fe10a154a19a.yaml
Fixes #1229 
There was a bug with how basis gates were computed in `backend.configuration` with the unintended side-effect of causing the basis gates list to grow larger each time `backend.configuration` was called (eg in transpile or execute). 
Further profiling also showed that a lot of overhead was being spent in set-comparison functions for computing the basis gates as the intersection of method, noise model and backend basis gates. This now greadily computes the basis gates and stores the value each time one of these options is set so that it isn't unnecessarily repeated each time at runtime.
> Fix ``backend.configuration`` performance issue

- releasenotes/notes/fix-stabilizer-expval-8649ee03f4b4b82d.yaml
- src/simulators/stabilizer/clifford.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- test/terra/backends/aer_simulator/instructions/test_save_expval.py
Partially fix for #1227 for the stabilizer simulator method.
Corrects the algorithm used to compute the expectation value in the Clifford class. The new algorithm is also more efficient since it avoids copying the full Clifford table for each Pauli term.
Adds an extra test for previously failing example.
> Fix stabilizer simulator expval function

- releasenotes/notes/bug-fix-multiplexer-qubits-654bb6f8ece25b02.yaml
- src/framework/operations.hpp
- test/terra/reference/ref_multiplexer.py
Solution to https://github.com/Qiskit/qiskit-terra/issues/6208
Terra assumes that qubits in a `multiplexer` gate are `targets + controls` ([L334](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/extensions/quantum_initializer/uc.py#L334)) and Aer assumes the opposite order (i.e `controls + targets`)
> Change qubits order in multiplexer gate

- qiskit/providers/aer/backends/aer_simulator.py
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/library/instructions_table.csv
- releasenotes/notes/ext-stab-expval-b205dcf3a26707d4.yaml
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
Disables the save expectation value instructions for the extended stabilizer method until Issue #1227 can be resolved.
> Disable save expectation value for ext stabilizer

- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/tests_linux.yml
- .github/workflows/tests_mac.yml
- .github/workflows/tests_windows.yml
- BENCHMARKING.md
- CONTRIBUTING.md
- qiskit/providers/aer/version.py
- test/asv.linux.conf.json
- test/asv.linux.cuda.conf.json
- test/terra/common.py
With the recent support added to qiskit-bot for configurable default
branches in Qiskit/qiskit-bot#9 we're able to rename the default branch
for the repository to 'main'. However, when we do that several things
will need to be updated, most importantly the CI trigger was hardcoded
to the previous default branch 'master. This commit fixes these
references and should be merged after we rename the branch to re-enable
CI.
> Prepare for renaming default branch to main

- contrib/standalone/qasm_simulator.cpp
- src/simulators/state_chunk.hpp
Fix compiler errors when using MPI
This commit fixes compiler warnings that were caused by Commit
1a51d273dec6e00f62495d2dca97d7f09e72755f ("Fix various compiler warnings (#1201)").
Fixes: https://github.com/Qiskit/qiskit-aer/issues/1234
----
Sorry for causing this. I'll make sure to configure using `-DAER_MPI=True` and check other options in the future to avoid this.
> Fix compiler errors when using MPI

- CMakeLists.txt
Uses the built-in CMake variable CMAKE_DL_LIBS, see https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html.
No new tests should be needed, I assume the Windows tests will test this.
Creating this PR to test against Windows CI, don't have a dev environment to test this change.
> CMake: Use built-in DL Lib variable

- qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py
- qiskit/providers/aer/pulse/controllers/pulse_controller.py
- qiskit/providers/aer/pulse/system_models/string_model_parser/gen_operator.py
- qiskit/providers/aer/pulse/system_models/string_model_parser/operator_generators.py
- qiskit/providers/aer/pulse/system_models/string_model_parser/string_model_parser.py
- test/terra/backends/test_config_pulse_simulator.py
- test/terra/backends/test_pulse_simulator.py
Closes #1257
As described in the comments in #1257, there was an issue with the way measurement operators were being constructed, which was introduced when switching from using the qutip `Qobj` to using the `qiskit.quantum_info.Operator` class. In particular, the error came from a line in the measurement operator construction function in which a tensor product of `Operator`s is taken. These operators represent "states", but were being stored as "column vectors" (i.e. 2d arrays with shape `(n, 1)`), but the tensor product code produced incorrect results for this case. The problem was solved just be reshaping the initial vectors to be properly 1 dimensional before inputting to the tensor code. 
The existing tests didn't catch this because it seemed to be outputting the correct values when …
> Fixing pulse simulator measurement bug

- qiskit/providers/aer/backends/pulse_simulator.py
- qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py
- qiskit/providers/aer/pulse/controllers/pulse_controller.py
- test/terra/backends/test_config_pulse_simulator.py
Closes #1246
~Depends on #1262 (no direct code dependency but this code was written as a continuation of that for testing purposes)~ (#1262 has been merged now)
Added `parametric_pulses=[]` to the default `PulseSimulator` configuration, as well as an override of `parametric_pulses` to `[]` in the `PulseSimulator.from_backend` method. This ensures that assembly and calling `run` will convert parametric pulses into explicit waveform pulses. Added a check in the pulse digest so that, if a parametric pulse makes it into the pulse simulator, an error is raised.
Added two tests:
1. Instantiates a `PulseSimulator` instance from a fake backend with parametric pulse support, and verifies that a pulse schedule containing parametric pulses still runs.
2. Verifies that the error gets raised if a …
> Configurable backend parametric pulse fix for PulseSimulator

- qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py
- test/terra/backends/test_pulse_simulator.py
Closes #736 
Added explicit checking/error raising for `ShiftFrequency` and `SetFrequency` instructions, along with associated tests.
> Add explicit PulseSimulator errors for ShiftFrequency and SetFrequency instructions

- README.md
There was a **broken link** in the **Next steps** section of **README.md** file.
Hence, the link has been updated to [/qiskit-tutorials/tree/master/tutorials/simulators](https://github.com/Qiskit/qiskit-tutorials/tree/master/tutorials/simulators)
> fixed broken link in README.md - Next steps

- releasenotes/notes/disable_fusion_with_mps-6757cbf8edb510a5.yaml
- src/controllers/aer_controller.hpp
- src/controllers/qasm_controller.hpp
- src/simulators/matrix_product_state/matrix_product_state_internal.hpp
- test/terra/backends/qasm_simulator/qasm_fusion.py
- test/terra/backends/test_qasm_simulator_matrix_product_state.py
Fusion optimization does not work correctly on the MPS simulation method. Therefore should be disabled, even when set in the config.
See failure example in issue #1253.
> Disable Fusion when running on MPS

- releasenotes/notes/bug-fix-in-mps-unitary-835d77b381480fcd.yaml
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/matrix_product_state/matrix_product_state_internal.cpp
- test/terra/backends/qasm_simulator/qasm_unitary_gate.py
Bug in MPS::apply_matrix (aka unitary gate) when qubits are given in non-standard order.
This bug was reported in issue #1256. It was initially thought to be a bug related to using Fusion in MPS.
> Fixed bug in MPS::apply_matrix 

- qiskit/providers/aer/backends/aer_simulator.py
- qiskit/providers/aer/backends/qasm_simulator.py
- releasenotes/notes/pauli_gate-de858933657d7d21.yaml
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
- src/simulators/extended_stabilizer/gates.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/matrix_product_state/matrix_product_state_internal.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/superoperator/superoperator_state.hpp
- test/terra/backends/aer_simulator/instructions/test_pauli_gate.py
Optimized PauliGate support was added last release for the statevector and density matrix simulators. This PR adds non-optimized support for these gates to the remaining simulation methods.
Pauli gates are implemented by iterating over each single-qubit Pauli in the the PauliGate and applying the corresponding single qubit gate in the simulator.
> Add PauliGate support to all simulation methods

- qiskit/providers/aer/extensions/snapshot.py
- qiskit/providers/aer/library/save_instructions/save_data.py
This fix is needed for Algorithm tests using Aer instructions into bass in https://github.com/Qiskit/qiskit-terra/pull/6626.
Adding label to Instruction in that PR is causing default initialization of the parent class to always set Snapshot and Save instruction labels to the default value.
> Fix initialization order of parent Instruction class

- src/simulators/extended_stabilizer/chlib/core.hpp
Previously the phase was unnormalised (indeed had norm sqrt(2)) for odd e. This lead to incorrect outcomes from the Runner::amplitude method 
As far as I can tell this commit fixes issue #1269
> fix phase normalisation issue leading to #1269

- qiskit/providers/aer/noise/errors/quantum_error.py
Fix mistake in documentation of `error_term`
The method returns `return self.circuits[position], self.probabilities[position]`, but the docstring said `(p, circuit)`.
> fix docstring for error_term

- qiskit/providers/aer/backends/pulse_simulator.py
- releasenotes/notes/pulse-sim-circuits-4b4b6f6a9f00dc77.yaml
- test/terra/backends/test_pulse_simulator.py
This commit adds support for the PulseSimulator to run QuantumCircuit
objects. Previously the PulseSimulator only would accept pulse Schedule
objects requiring users to call the scheduler before running circuits on
the pulse simulator. This commit makes it so if you need to do a pulse
simulation but have an input circuit you can pass that circuit to pulse
simulator's run method and it will schedule it (using the default
settings on the pulse scheduler) before executing it.
> Add support for running QuantumCircuits to PulseSimulator

- test/terra/common.py
This commit fixes an issue when trying to run the aer unittests without
setting the QISKIT_TEST_CAPTURE_STREAMS env variable. Since
Qiskit/qiskit-terra#6037 the QiskitTestCase class won't use the full
base test class with fixture support unles you set the env variable to
use it. This commit fixes the parent class to always use the
FullQiskitTestCase since we use fixtures in the aer tests regardless of
the env variable.
> Fix base test class parent

- src/transpile/fusion.hpp
- test/terra/backends/qasm_simulator/qasm_fusion.py
This PR fixes the issue #1289 
Fusion to generate diagonal gates has a bug to look up operations in a circuit and this PR fix this bug.
> fix a bug to generate a diagonal gate in the end of circuit

- releasenotes/notes/config.yaml
- requirements-dev.txt
When we switched to using main as the default branch for qiskit-aer
we encountered a bug in reno that required a branch named master to exist
for traversing the git history. To workaround that issue we temporarily
added back a branch named master while we waited for the fix [1] to be
included in a release. A new reno release has been published [2] and we
can rely on that version and delete the idle master branch now. This
commit makes this change and switches to using reno>=3.4.0 and uses
the new default_branch configuration option added in 3.4.0 to fix the
issue.
[1] https://opendev.org/openstack/reno/commit/ed6bbae82e01edf781534d9e9cce21e0c55a49a6
[2] https://pypi.org/project/reno/3.4.0/
> Bump reno requirement to latest version and set default_branch

- constraints.txt
- requirements-dev.txt
- test/terra/backends/qasm_simulator/qasm_snapshot.py
- test/terra/backends/test_parameterized_qobj.py
- test/terra/common.py
- test/terra/extensions/test_snapshot_expectation_value.py
- test/terra/extensions/test_snapshot_probabilities.py
- test/terra/noise/test_standard_errors.py
- test/terra/pulse/test_duffing_model_generators.py
- test/terra/utils/mock.py
- test/terra/utils/multiplexer.py
In Qiskit/qiskit-terra#6753 the base test classes were fixed to assert
that setUp and setUpClass in the base test class are always called. This
is necessary to ensure that all the warning assertions always work.
However this change had the unintended side effect of causing Aer's CI
to fail because it wasn't calling super().setUpClass(). This commit
makes this change to fix that failure. However, because now we're
running enforcement that tests can't raise unhandled
DeprecationWarnings a few spots in the tests were emitting deprecation
warnings. The deprecated syntax is either fixed or if it's testing
something in Aer that's deprecated an assertion on that warning is added
to fix the failure.
> Fix test deprecation warnings and call parent's setUpClass

- qiskit/providers/aer/utils/noise_model_inserter.py
This commit fixes an issue in the insert_noise function where it was
using a deprecated bit index lookup by accessing the .index attribute of
a Qubit object. Besides fixing the depercation warning this will fix a
potential issue with registerless circuits where the .index attribute
isn't set.
Fixes #1296
> Avoid deprecated bit index lookup in insert_noise

- qiskit/providers/aer/backends/aerbackend.py
- releasenotes/notes/remove-dep-b5a3b0e3f09eb90e.yaml
- src/noise/noise_model.hpp
- Removes deprecated `backend_options` kwarg from `backend.run`. All run options must now be passed as individual kwargs.
- This removes unused code from C++ noise model that was used by a previously deprecated feature.
- Remove deprecated internal `_run_job` method from `AerBackend`.
-
> Remove code deprecated in 0.7.0

- requirements-dev.txt
cvxpy 1.15.0 was recently released [1][2] and it has started causing CI
failures in the noise transformer tests. It fails with an error:
"The objective is not DCP. Its following subexpressions are not:"
(and then lists all the subexpressions which it doesn't like). To
unblock CI this commit caps the cvxpy version we run in CI until this
can be fixed either upstream in cvxpy or in the noise transformer.
[1] https://pypi.org/project/cvxpy/1.1.15/
[2] https://github.com/cvxpy/cvxpy/releases/tag/v1.1.15
> Cap cvxpy version to avoid CI failures

- src/controllers/aer_controller.hpp
- src/controllers/qasm_controller.hpp
- src/controllers/statevector_controller.hpp
- src/controllers/unitary_controller.hpp
- src/noise/quantum_error.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/density_matrix/densitymatrix_state_chunk.hpp
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/state.hpp
- src/simulators/state_chunk.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/superoperator/superoperator_state.hpp
- src/simulators/unitary/unitary_state.hpp
- src/transpile/fusion.hpp
This refactors the simulator `State` C++ classes `apply_ops` method:
* Changes signature of `apply_ops` to use iterators instead of a vector of Ops. This will allow applying pieces of a circuit without first copying all the operations (eg for measure sampling).
* Adds an abstract `apply_op` method class to base State
* Adds a concrete implementation of `apply_ops` that loops over calls to `apply_op`, since all but the extended stabilizer state perform this same loop to apply a sequence of ops.
> Refactor State apply_ops to use iterators

- qiskit/providers/aer/backends/aer_simulator.py
- qiskit/providers/aer/backends/qasm_simulator.py
- releasenotes/notes/fix-extended-stab-pauli-24eab8c4a7c6246c.yaml
- src/simulators/extended_stabilizer/gates.hpp
* Fixes bug in the "extended_stabilizer" simulation method where it
incorrectly treated some multi-qubit Pauli instructions as unsupported
instructions.
* Fixes typo in the `AerSimulator` and ``QasmSimulator`` options for the
``extended_stabilizer_norm_estimation_repetitions`` option.
> Fix bug in extended stabilizer simulator

- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/matrix_product_state/matrix_product_state_internal.cpp
- src/simulators/matrix_product_state/matrix_product_state_internal.hpp
random numbers should be generated before apply_measure in MPS to reproduce results
This PR is to generate random numbers before calling `apply_measure` in a single-thread for sampling.
> generate random numbers before parallel apply_measure in MPS

- qiskit/providers/aer/backends/aerbackend.py
- releasenotes/notes/fix-shots-option-245f6b05ffeb6d78.yaml
- test/terra/backends/aer_simulator/test_options.py
Fixes issue where setting a `shots` backend option was not working the same as setting it as a run option.
Updated behavior
```python
backend = AerSimulator(shots=99)
counts = backend.run(circuit).result().get_counts(0)
```
> Fix shots option

- qiskit/providers/aer/noise/noise_model.py
- releasenotes/notes/deprecate-nonlocal-noise-fb30b2a4c387fe61.yaml
- test/terra/backends/aer_simulator/test_noise.py
- test/terra/backends/aer_simulator/test_truncate.py
- test/terra/backends/qasm_simulator/qasm_noise.py
- test/terra/backends/qasm_simulator/qasm_truncate.py
- test/terra/noise/test_noise_inserter.py
- test/terra/noise/test_noise_model.py
- test/terra/noise/test_noise_remapper.py
Adding non-local quantum errors to a `NoiseModel` has been deprecated due to inconsistencies in how this noise is applied to the optimized circuit. Non-local noise should be manually added to a scheduled circuit in Qiskit using a custom transpiler pass before being run on the simulator.
Closes #1302
> Deprecate non-local quantum errors

- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/backends/pulse_simulator.py
- releasenotes/notes/deprecate-run-qobj-1a88c5bf0d1c0323.yaml
- test/terra/backends/test_parameterized_qobj.py
Deprecate passing qobj directly to `backend.run`
> Deprecate run(qobj)

- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/matrix_product_state/matrix_product_state_internal.cpp
- src/simulators/matrix_product_state/matrix_product_state_internal.hpp
Previously, bond dimensions were printed only for user-defined operations.  Here, we add similar prints after internal swap operations.
> MPS: Added print to log of bond dimension after internal swaps

- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/tests_linux.yml
- .github/workflows/tests_mac.yml
- .github/workflows/tests_windows.yml
This commit adds a concurrency limit for jobs running from a single PR.
This means that on PR updates github actions will cancel any currently
running jobs for that because they exceed the concurrency limit on the
PR.
> Add concurrency limit on GHA jobs for a PR

- setup.py
This commit updates the setup.py setup_requires field to only include
build dependencies. Previously we were a bit aggresive in the set of
packages we specified as build dependencies in the setup.py. This dates
back to early issues building packages from sdist where things were not
properly being installed. However, this results in requiring people have
a working scipy (that setuptools/scikit-build) can find at build time.
This commit updates the setup.py to be more explicit about the packages
it requires for build time and for run time so that when users are
building from source (or sdist) it is more likely to work correctly.
> Adjust setup.py setup_requires to only include build dependencies

- qiskit/providers/aer/backends/aerbackend.py
- test/terra/backends/test_parameterized_qobj.py
This commit fixes an oversight in the handling of the parameter binds
kwarg on backend.run(). To build the parameterizations representation
that aer's c++ code expects we need to iterate over all the instructions
to find any that are parameterized. In this check we were incorrectly
finding gates with ParameterExpressions that were already bound to a
value (and had no unbound parameters). This would often come up from the
transpiler when the basis translator uses a parameter expression to
adjust rotation angles when translating between 1q gates. This commit
fixes this by adding a check for fully bound parameter expressions and
not including them in the set of parameterizations we pass to the inner
simulator code.
Fixes #1346
> Fix handling of bound ParameterExpressions

- releasenotes/notes/fix-empty-circuit-411ff41929d9b28f.yaml
- src/framework/circuit.hpp
- src/noise/noise_model.hpp
- test/terra/backends/aer_simulator/test_noise.py
Fixes #1351
When loading a circuit in C++ the size of an empty circuit was being set to 1 and being populated with a default initialized Op. This caused a crash when this circuit was passed to the noise sampler. This is fixed by correctly initializing an empty to be size 0.
> Fix issue 1351

- test/terra/extensions/test_snapshot_density_matrix.py
- test/terra/extensions/test_snapshot_expectation_value.py
- test/terra/extensions/test_snapshot_probabilities.py
- test/terra/extensions/test_snapshot_stabilizer.py
- test/terra/extensions/test_snapshot_statevector.py
Some of the deprecated snapshot tests had missing `@classmethod` decorators, causing test failures on my machine.  Not 100% sure why they weren't also causing failures in CI, to be honest.
> Add missing classmethod decorators from setUpClass

- qiskit/providers/aer/backends/aer_simulator.py
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
- releasenotes/notes/remove-optimize_ideal_threshold-dba17ef1e0a84fb5.yaml
The last meaningful uses of the optimize_noise_threshold and
optimize_ideal_threshold parameters were removed in #698 (commit
5828c51).  This just removes references to them, since they are no
longer accessed, but had remained in the documentation.
Fix #1359.
> Remove references to unused parameters

- src/controllers/aer_controller.hpp
- test/terra/backends/aer_simulator/test_auto_method.py
When the automatic method detection loop was moved to occur once ahead
of time in #1312 the loop over all circuits there was not tolerant of
any circuits in a job with multiple circuits being invalid for all
simulation methods. This was an unexpected change from the previous
behavior where we would return a partial result and only the circuits
with no matching methods would error and the other results would be
returned. This commit fixes the behavior and restores the partial result
generation and only errors for the jobs where the circuit is not
runnable.
Fixes #1370
> Fix automatic method selection when some circuits have invalid instructions

- qiskit/providers/aer/backends/aerbackend.py
- releasenotes/notes/fix-dask-fe5813daeec259ce.yaml
FIx issue #1364 
DASK can pickle the object stored in a only local variable. If the dask executor is passed to qobj or class variables, dask occurs a serialization error when the first `run()` is called. So we need to store the executor variable to `self._executor` after `submit()` function.
> Fix job mission pickle error for Dask Client executor

- qiskit/providers/aer/noise/errors/standard_errors.py
Fixes issue #1373 
phase_damping_error and amplitude_phase_damping_error had both the same description so I updated the descriptions and remain consistency with the other errors descriptions.
> Fix doc string for phase_damping_error

- releasenotes/notes/mps_normalize_lambda-9d931abbfb6d4d2c.yaml
- src/simulators/matrix_product_state/svd.cpp
The norm of lambda after svd may be slightly off 1 even without truncation. Therefore  always check its norm, and normalize if needed.
Slight errors in the computation of lambda during measurement may build up when many qubits are involved, eventually leading to a segmentation fault.
> MPS: Normalize lambda after every svd

- MANIFEST.in
Since qiskit-aer uses scikit-build instead of setuptools directly we
have not been including our pyproject.toml file in the sdist. This has
the undesired effect of causing pip to not find the setup/build
requirements until it's processing the sdist (and sees the
setup_requires list). While in theory this should be sufficient it's not
because setuptools relies on easy_install instead of pip to install the
packages in the setup_requires list. easy_install doesn't respect the
same options as pip and in environments with custom mirrors (like
piwheels for raspberry pi users) this can cause build dependencies to
needlessly be built from source or not install correctly as easy_install
will unconditionally go to PyPI and try to install everything in the
setup_requires list. Having a …
> Include pyproject.toml in sdist

- qiskit/providers/aer/backends/backend_utils.py
- qiskit/providers/aer/backends/statevector_simulator.py
- qiskit/providers/aer/backends/unitary_simulator.py
The proper name is `qiskit.utils`, but Terra hasn't been issuing very strong deprecation warnings yet.
See also Qiskit/qiskit-terra#7208
> Fix deprecated qiskit.util imports

- src/simulators/statevector/qv_avx2.cpp
This PR fixes wrong memory free in avx2 for diagonal matrix multiplication if a number of shots is less than of cores.
Memory free does not work correctly in avx2. Especially, the following code fails if a number of cores is less than 10, which is a configured `shots`.
```
from qiskit import Aer, transpile
from qiskit.providers.aer import AerSimulator
from qiskit.circuit.library import QuantumVolume
from qiskit.providers.aer.noise import NoiseModel
from qiskit.providers.aer.noise import depolarizing_error
noise_model = NoiseModel()
noise_model.add_all_qubit_quantum_error(depolarizing_error(0.05, 1), ['u'])
qbackend = AerSimulator(noise_model=noise_model, method="statevector")
circ_list = []
circ = transpile(QuantumVolume(num_qubits=15, depth=1), basis_gates=['u','cx'])
circ.measure_all() …
```
> fix wrong memory free in avx2

- src/simulators/statevector/qv_avx2.cpp
https://github.com/Qiskit/qiskit-aer/pull/1384 is not enough to fix all the cases.
This fix will resolve issues related to allocate temporal memory in avx.
The fix of https://github.com/Qiskit/qiskit-aer/pull/1384 is not enough to run following codes.
```
from qiskit import transpile
from qiskit.circuit.library import QFT
from qiskit.providers.aer import AerSimulator
circ = QFT(20)
circ.measure_all()
simulator = AerSimulator()
result = simulator.run([transpile(circ, simulator, basis_gates=['u3', 'cx'])] * 4,
**{'_parallel_experiments': 2,
'_parallel_state_update': 2,
'shots': 10}).result()
```
Because of the structure of codes, temporal memory is allocated and freed in the other OMP blocks in avx codes.
There is no guarantee to use the same set of threads to run these blocks, especially …
> remove threadprivate memaloc in omp

- src/simulators/statevector/qv_avx2.cpp
This PR will fix an issue related to diagonal matrix multiplication with AVX2 and OMP on WIndows.
This PR fixes an issue when WIndows uses OMP and AVX2 for diagonal matrix multiplication.
> fix an issue of AVX2 matrix multiplication with OMP in Windows

- qiskit/providers/aer/noise/noise_model.py
- qiskit/providers/aer/utils/noise_model_inserter.py
- qiskit/providers/aer/utils/noise_remapper.py
Replacing string keys representing qubits used internally in NoiseModel with tuple of integers so to avoid many conversions using `_str2qubits` and `_qubits2str`.
> Replace string qubits with tuple of integers in NoiseModel

- .github/workflows/tests_linux.yml
Terra's main branch which is currently developing the 0.20.0 release has
dropped support for running with Python 3.6 as the recently released
0.19.x is the last release series with 3.6 support. For the upcoming Aer
0.10.0 release we still want to support 3.6 and release artifacts. We
already relaxed our testing of 3.6 to just be linux to reduce our CI
time recently, but those jobs are failing now. This commit addresses
this by installing terra from release instead of main in the 3.6 jobs.
Arguably we should be doing this everywhere as we release aer against
terra on pypi, not it's development branch. But that's something we can
discuss in a future change. For right now this just makes the adjustment
on the 3.6 test job.
> Use terra from release in Python 3.6 job

- .gitignore
- qiskit/providers/aer/backends/aer_simulator.py
- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/backends/backend_utils.py
- qiskit/providers/aer/backends/compatibility.py
- qiskit/providers/aer/library/instructions_table.csv
- qiskit/providers/aer/library/save_instructions/__init__.py
- qiskit/providers/aer/library/save_instructions/save_clifford.py
- qiskit/providers/aer/library/set_instructions/set_stabilizer.py
- releasenotes/notes/result-types-2bdbcccb94d43cfa.yaml
- src/framework/circuit.hpp
- src/framework/operations.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/state.hpp
- src/simulators/state_chunk.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/superoperator/superoperator_state.hpp
- src/simulators/unitary/unitary_state.hpp
- test/terra/backends/aer_simulator/test_pauli_gate.py
- test/terra/backends/aer_simulator/test_save_density_matrix.py
- test/terra/backends/aer_simulator/test_save_state.py
- test/terra/backends/aer_simulator/test_save_statevector.py
- test/terra/backends/aer_simulator/test_save_superop.py
- test/terra/backends/aer_simulator/test_save_unitary.py
- test/terra/backends/aer_simulator/test_set_state.py
- test/terra/backends/aer_simulator/test_standard_gates.py
- test/terra/backends/test_compatibility.py
This updates the returned result to store metadata for the type and subtype of all save instructions.
This metadata is used to convert the raw results into the appropriate qiskit-terra class objects.
Note this depends on https://github.com/Qiskit/qiskit-terra/pull/7277 for several tests to pass.
The types that have changed are
* ``save_statvector`` now returns as a :class:`qiskit.quantum_info.Statevector`
* ``save_density_matrix`` now returns as a :class:`qiskit.quantum_info.DensityMatrix`
* ``save_stabilizer`` now returns as :class:`qiskit.quantum_info.StabilizerState`
* ``save_unitary`` now returns as :class:`qiskit.quantum_info.Operator`
* ``save_superop`` now returns as :class:`qiskit.quantum_info.SuperOp`
* ``save_probabilities_dict`` now returns as a …
> Format results and store save type metadata

- qiskit/providers/aer/backends/aer_simulator.py
- qiskit/providers/aer/backends/pulse_simulator.py
- qiskit/providers/aer/backends/qasm_simulator.py
- qiskit/providers/aer/noise/__init__.py
- qiskit/providers/aer/noise/noise_model.py
- test/terra/noise/passes/test_local_noise_pass.py
- test/terra/noise/passes/test_relaxation_noise_pass.py
The `*Simulator.from_backend` and `NoiseModel.from_backend` assume the input backend is a V1 backend.
This changes these functions to raise an exception if a V2 backend is passed until we can work out how to make them support V2 backends.
This also reworks some of the functionality added in #1391 to be more robust when looking for required backend attributes (like dt, t1, t2)
> Fixes to from_backend for V2

- src/controllers/aer_controller.hpp
Fix recent unstability of CI by allowing run with sampling in parallel
In the refactoring of https://github.com/Qiskit/qiskit-aer/pull/1287, `Controller` runs "simulation with sampling" by using always one thread if `can_sample()` returns `true`. However, before this refactoring, multiple "simulation with sampling" are run in parallel with OMP threads if `parallel_shots_` is more than one. This change is a reason of recent unstability of CI and this PR reverts it.
> allow parallel sampling-run

- qiskit/providers/aer/noise/errors/quantum_error.py
- releasenotes/notes/fix-qerror-assemble-9919a93b210ca776.yaml
- src/controllers/aer_controller.hpp
- src/framework/qobj.hpp
- test/terra/backends/aer_simulator/test_noise.py
- test/terra/backends/aer_simulator/test_truncate.py
- test/terra/noise/test_quantum_error.py
- test/terra/reference/ref_kraus_noise.py
Fixes #1407 #1398 
Fixes issue with QuantumError.to_dict causing a huge performance regression in noisy simulations from its calling of `qiskit.assemble` inside Pybind11 code.
This also fixed an inefficiency in the C++ controller `execute` function where the qobj config was deserialized/parsed twice (which doubled the performance regression in #1407)
> Fix performance regression from QuantumError.to_dict

- qiskit/providers/aer/backends/aer_compiler.py
- qiskit/providers/aer/backends/aerbackend.py
- qiskit/providers/aer/backends/backend_utils.py
- qiskit/providers/aer/jobs/utils.py
This PR complements #1408 to reduce some other possible, but less serious, regressions from Aer 0.10.
This adds checks to avoid transpiling or iterating over circuits for noise model transpilation, quanutm error replacement, qasm3 compiling, and qobj splitting if the required instructions are not in the circuits. This is done by collecting sets of all instructions in each circuit in advance, and using that set for checks before running the other transpilation/compilation steps.
> Reduce unnecessary circuit iteration

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/tests_windows.yml
Github actions recently changed the image used for the windows-latest
image tag from windows server 2019 to windows server 2022. Unfortunately
it looks like upstream C++ projects we're leveraging via conan do not
have precompiled versions available on the conan center with the msvc
version bundled in the new windows image. The fallback to building them
from source is not functioning either. Until we can resolve this issue
this commit just pins the windows ci jobs to explicitly use the windows
server 2019 image that worked before. Once we solve the issues building
aer in the new windows version we can revert this and go back to
following the latest release.
> Pin windows CI image to Windows Server 2019

- releasenotes/notes/fix_parallel_diag_fusion-a7f914b3a9f491f7.yaml
- src/transpile/fusion.hpp
- test/terra/backends/aer_simulator/test_fusion.py
fusion to generate a diagonal matrix has a bug when transpilation is in parallel
If a number of gates exceeds `fusion_parallelization_threshold`, fusion transpiler divides the sequence of gates into sub-sequences and multiple threads run transpilation for each sub-sequence. A thread can fuse gates only in a sub-sequence. However, current diagonal-fusion searches gates across sub-sequences and can produce wrong results. This PR prevent from a thread not to fuse gates across sub-sequences.
> Fix diagonal fusion in parallel transpilations

- .mailmap
This change is to avoid my name appearing in two different forms in `Qiskit.bib` upon the next Aer release, now that #1424 has been merged.
> Update garrison's name in .mailmap

- qiskit/providers/aer/noise/passes/relaxation_noise_pass.py
- releasenotes/notes/delay-pass-units-a31341568057fdb3.yaml
- test/terra/noise/passes/test_relaxation_noise_pass.py
Fixes #1453
RelaxationNoisePass assumes all instructions have dt unit durations. This fix changes it to check the specified unit for each op and convert non-dt units to seconds correctly.
> Fix unit handling in RelaxationNoisePass

- qiskit/providers/aer/noise/passes/local_noise_pass.py
- releasenotes/notes/fix-local-noise-pass-f94546869a169103.yaml
- test/terra/noise/passes/test_local_noise_pass.py
Fixes #1447 
IF the local noise pass function returns a QuantumCircuit instead of an instruction or operator this composes the circuit into the DAG so that it is unrolled, rather than added as an opaque circuit instruction.
> Fix LocalNoisePass for circuit returns from noise func

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- pyproject.toml
With recent changes to the upstream numpy and scipy packaging our CI
build jobs are spending most of their time build numpy and/or scipy from
source to test the built wheels function correctly. This is unecessary
as there are compatible wheels available on pypi. To correct this issue
this commit updates the cibuildwheel config used in the wheel build jobs
(both for ci and release artifacts) to only use binary wheels for numpy
and scipy before testing.
> Only install numpy and scipy from wheels in build jobs

- tox.ini
stop installing qiskit-terra from source in tox
This changes installation of qiskit-terra in tox.
Recent commit of #1448  changed installation of qiskit-terra to use pypi in most CI workflow, but not tox.
> stop installing qiskit-terra from source in tox

- .github/workflows/deploy.yml
The aer gpu package wheel job for python 3.10 builds in the manylinux2014
container image, while for the older Python versions it uses the
manylinux2010 image. The manylinux2014 image is based on Centos 7 while
the manylinux2010 image is based on Centos 6. During the qiskit-aer
0.10.3 release the gpu wheel job failed because when running the py3.10
build we installed the cuda package for centos 6 in the manylinux2014
centos 7 based image. This caused the job to fail when nvcc was called
because it was not installed properly. To fix this issue the Python 3.10
build is split out into a separate job. This separate job will install
the same cuda version but for centos 7 which is appropriate for the
manylinux2014 image.
> Split out gpu Python 3.10 wheel build

- releasenotes/notes/density-multi-chunk-fix-e9effc67d0365418.yaml
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/qubitvector_thrust.hpp
- src/simulators/statevector/statevector_state.hpp
- src/transpile/cacheblocking.hpp
- test/terra/backends/aer_simulator/test_chunk.py
- test/terra/backends/aer_simulator/test_noise.py
This is fix for issue #1479 
A test case to test Kraus noise on QFT with cache blocking (in` test_noise.py`)
Also this PR fixes issue #1483 that was found when adding the test case. 
superop was missing in `CacheBlocking::can_reorder` function so recognize it by calling `CacheBlocking::is_blockable_operation`
I could not make separate PR for issue #1483 because `test_noise.test_kraus_gate_noise_on_QFT_cache_blocking` fails if we separate PR.
For issue #1483,
` QubitVectorThrust<data_t>::norm()` originally returns sum of norm for all chunks. 
This causes incorrect measurement result when qubit is out of chunk qubits.
I changed ` QubitVectorThrust<data_t>::norm()` returns norm for one chunk if ` QubitVectorThrust<data_t>::enable_batch_` is not set. ` sample_measure` only uses batched sum of …
> Fix: cache blocking transpiler for density_matrix with noises

- constraints.txt
The 3.1 release of Jinja breaks some part of the Sphinx/nbsphinx
pipeline, causing tutorial jobs to fail.  The jinja2 developers consider
this a Sphinx bug, so we need to pin Jinja until a new version of Sphinx
or the nbsphinx extension is released to fix the issue.
See also Qiskit/qiskit-terra#7815
> Pin jinja2 in CI

- CONTRIBUTING.md
- releasenotes/notes/support_for_cuQuantum0.40-566391cc42be2341.yaml
- src/simulators/statevector/chunk/cuStateVec_chunk_container.hpp
This is the fix to support the latest cuQuantum (ver. 0.40).
Compilation failed with cuStateVec support because some cuStateVec APIs' name and parameters are changed from the previous version. This PR follows the latest cuStateVec.
Also cuQuantum 0.40 newly supports memory pool mechanism to allocate work space inside cuStateVec APIs.
Qiskit Aer now use memory pool instead of allocating static work buffer if the version of CUDA installed on the system supports it.
> Fix for the latest cuStateVec APIs

- pyproject.toml
- test/terra/noise/test_standard_errors.py
In the recently released terra 0.20.0 release the minimum python
packaging spec supported is manylinux2014 now. On the main branch we
bumped the manylinux base image we use for wheel jobs to manylinux2014
in #1498. However, on the stable 0.10.x branch we don't want to do that
since we probably should not drop support for older environments on a
stable release. This commit updates the wheel job config to instead
install terra from a compatible binary wheel instead of using the latest
release. This should hopefully avoid the CI failure but still enable us
to run without building terra from source or dropping support for
manylinux2010.
> Only install terra from binary for wheel jobs

- qiskit/providers/aer/noise/noise_model.py
- qiskit/providers/aer/pulse/system_models/pulse_system_model.py
The BaseBackend class in qiskit-terra (along with the rest of the legacy
provider interface) is deprecated and being removed soon in
Qiskit/qiskit-terra#7886. To avoid potential compatibility issues or
deprecation warnings we shouldn't be using this class anymore. This
commit removes the last 2 uses of these legacy classes to avoid issues
moving forward.
> Stop using deprecated BaseBackend class

- src/simulators/statevector/chunk/cuStateVec_chunk_container.hpp
`BaseContainer::stream_` is of type `cudaStream_t` (opaque pointer), cannot be used as an array.
This caused a compile error when enabling cuStateVec.
This is potentially a fallout from this commit https://github.com/Qiskit/qiskit-aer/commit/ce6c733bd8da4a4a3d7d6126cc6cedbe098a350e where `BaseContainer::stream_` was refactored from a vector to a value.
> Fixed a compile error when enabling cuStateVec

- qiskit/providers/aer/noise/errors/quantum_error.py
- test/terra/noise/test_noise_model.py
Currently, a `pauli` instruction can not be deserialized from `dict` in `NoiseMode.from_dict()`. This PR adds its support.
Resolve #1505.
Note that this PR fixes issues in deprecated function from 0.11.
> Support `pauli` instructions in `NoiseModel.from_dict()`

- releasenotes/notes/allow_multiplexer_without_control_qubits-f5cb8bdbe6302e55.yaml
- src/framework/operations.hpp
- src/simulators/statevector/statevector_state.hpp
- test/terra/backends/aer_simulator/test_multiplexer.py
- test/terra/reference/ref_multiplexer.py
Apply multiplexer to statevector even if no control qubit exists.
Currently, multiplexer needs control qubits to apply matrices to target qubits.
However, as reported in #1503, control-qubits may not exist.
This fix allows multiplexer to apply updates without control qubits.
> Apply multiplexer to statevector even if no control qubit exists

- releasenotes/notes/make_random_seed_reproducible-a7abdfc09ec67bd8.yaml
- src/framework/qobj.hpp
- test/terra/backends/test_parameterized_qobj.py
Fix #1511 and a potential issue without `seed_simulator`
Currently, a circuit is copied for each parameter set, including `seed_simulator` (if `seed_simulator` is specified as a run option, different seeds are set to circuits). Also, if `backend.run()` simulates multiple circuits without `seed_simulator`, a seed of each circuit is randomly generated and make users to reproduce simulation difficult.
This PR sets seeds deterministically based on the seed of the first circuit in multi-circuit simulation. For example, `res1` and `res2` are identical:
```
res1 = backend.run(circuit, shots=shots, parameter_binds=parameter_binds).result()
res2 = backend.run(circuit, shots=shots, parameter_binds=parameter_binds, seed_simulator=res1.results[0].seed_simulator).result()
```
> Generate seeds deterministically based on seed of the first circuit in multi-circuit simulation if seed_simulator is not set

- src/simulators/state_chunk.hpp
- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/qubitvector_thrust.hpp
Reduce dependency to `ClassicalRegister` to construct `AER::QV::QubitVector` objects.
`qubitvector.hpp` is not self-sufficient. This PR adds some include-statements for some header files to the file.
Additionally, `ClassicalRegister` becomes not referred. This odd dependency is added for batch-execution on GPU noise optimization and it is not necessary in `AER::QV::QubitVector`. This PR reduces this dependency by templating the class.
With this change, the following code will be compiled successfully.
```
#include <iostream>
#include "simulators/statevector/qubitvector.hpp"
int main() {
AER::QV::QubitVector<double> qv(21);
qv.initialize();
std::cout << qv[0] << std::endl;
return 1;
}
```
> Reduce dependency to ClassicalRegister from AER::QV::QubitVector

- qiskit/providers/aer/noise/errors/standard_errors.py
Same with https://github.com/Qiskit/qiskit-aer/pull/1295
> Fix import path for deprecated Pauli

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- cmake/conan_utils.cmake
llvm-openmp in conan is built for macosx_11
The reason why recent CI encounters errors in build of mac is that generated wheel file is for macosx_11 though OS target is 10.9.
Binaries of llvm-openmp in conan were for macosx_11 and then skbuild generates a wheel for 11.
With this PR, CI builds llvm-openmp from source in conan. The built library files are for 10.9 and then skbuild generates a wheel for 10.9.
> Make CI to build OpenMP from source through conan for mac

- docs/apidocs/parallel.rst
- releasenotes/notes/remove-deprecated-u1-calls-from-examples-04d092002966617e.yaml
Fixes #1532 by replacing usage of the `U1Gate` with usage of the `PhaseGate`.
> Removing usage of the deprecated U1Gate from parallel processing examples.

- qiskit/providers/aer/backends/aer_simulator.py
- releasenotes/notes/fix_cacheblocking__multi_control_gates-f6a7fca4f3db2f61.yaml
- src/controllers/aer_controller.hpp
- src/simulators/density_matrix/densitymatrix.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/density_matrix/densitymatrix_thrust.hpp
- src/simulators/state_chunk.hpp
- src/simulators/statevector/chunk/chunk.hpp
- src/simulators/statevector/chunk/chunk_container.hpp
- src/simulators/statevector/chunk/chunk_manager.hpp
- src/simulators/statevector/chunk/cuStateVec_chunk_container.hpp
- src/simulators/statevector/chunk/device_chunk_container.hpp
- src/simulators/statevector/chunk/host_chunk_container.hpp
- src/simulators/statevector/chunk/thrust_kernels.hpp
- src/simulators/statevector/qubitvector_thrust.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_state.hpp
- src/transpile/cacheblocking.hpp
This is fix for issue #1522 
Cache blocking transpiler did not support multi-control gates with large number of control qubits (larger than `blocking_qubits` ) that causes segmentation fault for MPI simulator.
Now cache blocking transpiler only blocks target qubits inside `blocking_qubits` to parallelize circuits for multi-GPU or MPI. 
But it still does not support unitary matrix whose qubits is larger than `blocking_qubits` in this case program will abort (WIP)
I also added number of GPUs used for simulation if cacheblocking is enabled or batched multi-shots optimization is enabled.
> Fix cache blocking parallelization to support large multi-control gates 

- .github/workflows/docs.yml
In Qiskit/qiskit-tutorials#1337 the theme used for the sphinx builds of
the tutorials changed to use the qiskit theme package. This is breaking
CI because we didn't have the package installed. This commit fixes this
failure by swapping out the theme package.
> Add qiskit-sphinx-theme to tutorial job

- qiskit/providers/aer/backends/aerbackend.py
- test/terra/backends/test_parameterized_qobj.py
Fix #1530
To use Aer's parameterized qobj, all `Parameter` must be resolved.
Originally, parameters were resolved with `assemble` by setting all pairs of parameters specified for circuits.
However, `assemble` will raise an error if unrelated parameters are specified.
This PR changes parameter resolving outside of `assemble` by calling `bind_parameters` directly.
> fix issues from mismatch of binding specs in assemble and backend of aer

- .github/workflows/neko.yml
This commit adds a new CI job to run the Qiskit Neko test suite. Qiskit
Neko is an integration suite that's designed to validate backwards
compatibility for end user workflows and between different components in
Qiskit. This test job will hopefully eventually replace the role that
the tutorials CI job is playing for backwards compatibility testing.
Right now the test suite is still fairly small but it covers some
examples of terra, aer, experiments, nature, and machine learning. The
test suite will continue to grow and improve our coverage for testing.
This test job will install qiskit-neko and aer from main, while
the other qiskit components (nature, aer, machine learning, and
experiments) will be installed from release. This will enable us to
check that a proposed PR does not regress …
> Add qiskit-neko integration test job

- docs/conf.py
Since Sphinx 5, `language = None` is a warning that defaults to "en".
Fixes failing CI.
> Set Sphinx language to explicitly English

- releasenotes/notes/terra-version-bump-68eac37136428805.yaml
- setup.py
- test/terra/backends/test_config_pulse_simulator.py
- test/terra/backends/test_pulse_simulator.py
- test/terra/pulse/test_system_models.py
In Qiskit/qiskit-terra#8121, we triggered deprecation warnings for `qiskit.test.mock`, preferring the new location (since Terra 0.20).  The only uses in Aer are in the tests, but it still technically requires a version bump in the requirements.  It's pretty likely that something else will need/use features of Terra 0.20/0.21 before the Aer 0.11 release anyway.
> Remove deprecated use of `qiskit.test.mock`

- test/terra/backends/aer_simulator/test_standard_gates.py
- test/terra/backends/aer_simulator/test_truncate.py
- test/terra/noise/test_noise_model.py
terra 0.22 started deprecation of qiskit.test.mock
existing wrong usages of rccx and rcccx are now in error
This PR changes some tests to use `qiskit.providers.fake_provider` instead of `qiskit.test.mock`.
Existing tests specify float numbers as labels of rccx and rcccx gates. 0.22 raises errors in this situation.
> Use qiskit.providers.fake_provider instead of qiskit.test.mock and correct rccx and rcccx usages in tests

- releasenotes/notes/fix-seed-generation-MPI-ee1f0ad44e913d4f.yaml
- src/controllers/aer_controller.hpp
This is fix for issue #1557 
Each MPI process had different seed numbers when `seed_simulator` is not set.
So I added MPI_Allreduce to average seed numbers for each circuit so that all the process has the same seed.
> avaraging seed of cirucits among all MPI processes

- test/terra/reference/ref_multiplexer.py
https://github.com/Qiskit/qiskit-terra/pull/8231 breaks transpilation to generate `multiplexer`. https://github.com/Qiskit/qiskit-terra/pull/8454 will fix the error by producing no `multiplexer` gate.
`test_multiplexer_without_control_qubits` needs `multiplexer` gate and this PR generates it by manually calling `uc()`.
[multiplexer_no_control_qubits](https://github.com/Qiskit/qiskit-aer/blob/8ca389a53314cf0f5d921277006ebf1795a51697/test/terra/reference/ref_multiplexer.py#L287-L296) generates a circuit with `multiplexer` gate by transpiling inversed `isometry` gate. However, `isometry` gate does not produce `multiplexer` gate correctly.
```
qc = QuantumCircuit(1,1)
vector = [0.2, 0.1]
vector_circuit = QuantumCircuit(1)
vector_circuit.isometry(vector / np.linalg.norm(vector), [0], None) …
```
> Avoid using inversed isometry gate in multiplexer test

- CONTRIBUTING.md
- releasenotes/notes/MPI_chunk_fixes-1ea74548cd3c3515.yaml
- src/simulators/state_chunk.hpp
- src/transpile/cacheblocking.hpp
This is fix for issue #1565 
Non-gate operations such as save_statevector are not recognized correctly in cache blocking transpiler that causes error if there are full-qubits operations.
The  save_statevector operation only returns statevector to the 1st MPI process previously. Now all the process receive statevector.
Also this PR included fix for global chunk indexing for Thrust implementations.
> Fix for save_statevector and fix for global indexing for Thrust

- src/simulators/statevector/qv_avx2.cpp
Fixing intermittent Segfault crashes in `apply_diagonal_matrix_avx` when building without OpenMP.
The temporary double array of size 4 needed for `_mm256_load_pd` should be allocated with `posix_memalign` on Linux platforms. It is accidentally wrapped within `_OPENMP` switch; hence causing the default `malloc` to be used in all cases when that compiler flag is not defined. This may cause Segfault when `_mm256_load_pd` is called on Linux builds. It occurs intermittently, especially in DEBUG builds (no optimization).
The need for `posix_memalign` should not depend on OpenMP. I think this bug was first introduced when we varied the size of the temporary array depending on the number of threads. I suppose when that logic was implemented, the else code path (`_OPENMP` is not defined) should …
> Fixed crash (SegFault) in apply_diagonal_matrix_avx

- qiskit/providers/aer/noise/errors/quantum_error.py
In [the `QuantumError` class API reference documentation](https://qiskit.org/documentation/stubs/qiskit.providers.aer.noise.QuantumError.html#qiskit.providers.aer.noise.QuantumError), there is a small error that looks like this:
This PR converts the box into a [Sphinx warning box](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/notes_warnings.html#warnings), which looks like this:
> Sphinx warning box broken in `QuantumError` docstring

- CMakeLists.txt
- qiskit/providers/aer/backends/wrappers/CMakeLists.txt
FreeBSD has CMAKE_HOST_SYSTEM_PROCESSOR=amd64.
> Treat CMAKE_HOST_SYSTEM_PROCESSOR=amd64 same as AMD64

- releasenotes/notes/new-namespace-9c3b9fd73ed504e6.yaml
In the recently merged #1526 we moved the qiskit-aer package to move
it's python namespace from qiskit.providers.aer to qiskit_aer. However,
in that PR a release note was missing. This commit adds the missing
release note to document the upgrade implications about the change. We
should also mention this in the release notes prelude section, but that
will occur in the release PR.
> Add release note for namespace migration

- qiskit_aer/backends/aer_simulator.py
This adds the Terra control-flow instructions to the custom instructions lists for the simulator methods that support them.  This is likely to be a temporary measure; as classical-processing descriptions are expanded in Terra, this method of describing them feels like it will become unworkable, but for now, this is sufficient to allow `qiskit.transpile(qc, AerSimulator(...))` to work as expected when there is control flow.
I mostly just added these gates to the simulator methods that could run a test circuit:
```python
import qiskit
from qiskit.providers.aer import AerSimulator
qc = qiskit.QuantumCircuit(2, 2)
qc.x(0)
qc.measure(0, 0)
with qc.if_test((qc.clbits[0], True)):
qc.x(1)
with qc.for_loop((0, 1)):
qc.x(1)
```
`unitary` and `superop` seem to clearly not work with classical …
> Add control-flow instruction names to basis gates

- releasenotes/notes/fix_bug_in_tail_while-6a9201d1ad6ba6e8.yaml
- src/framework/circuit.hpp
- test/terra/backends/aer_simulator/test_control_flow.py
This fixes a bug of simulation of while loops.
while_loop is translated to mark and jump instructions. However, some of instructions are truncated before simulation runs. This PR is to always leave mark and jump instructions.
> fix an issue of while_loop at the tail of a circuit

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Build packages for qiskit-aer-gpu was failed
mainlinux2014 needs recent GCC versions for qiskit-aer-gpu. Downgrading to mainlinux2010 introduces build of qiskit-terra from source codes, which producing another errors in tests of cibuildwheel.
This PR changes to
- Use mainlinux2010
- Skip tests in cibuildwheel (`CIBW_TEST_SKIP: "cp*"`)
> Use mainlinux2010 skip CIBW tests to release packages for GPU

- releasenotes/notes/0.11/fix-for-loop-no-parameter-aa5b04b1da0e956b.yaml
- releasenotes/notes/0.11/support_initialize_with_label-bc08f29928d3e3f3.yaml
The qiskit-aer release notes for 0.11 say that the release moves away from `qiskit.providers.aer`.  However, some of the other release notes for this release actually use this soon-to-be-deprecated import location, including one that is displayed before the one about the new namespace.  This fixes that awkwardness by using `qiskit_aer` uniformly throughout the 0.11 release notes.
> Move away from `qiskit.providers.aer` in 0.11 release notes

- releasenotes/config.yaml
There is currently no reno configuration in Aer, so it defaults to basing release notes off the `master` branch, which doesn't exist.  This updates it to correctly look at `main`.
> Add reno branch configuration

- qiskit_aer/quantum_info/states/aer_statevector.py
- test/terra/states/test_aer_statevector.py
This PR fixes typos.
`random_statevector` returns `qiskit.quantum_info.Statevector`. So, an `AerStatevector` instance must be created as the next process.
Also, the documentation has been modified since the current specification is that an `AerStatevector` cannot be created directly from a `Statevector`.
I would like to add that I have already discussed this modification with @hhorii.
> Use AerStatevector in unittests

- qiskit_aer/noise/device/models.py
- qiskit_aer/noise/noise_model.py
- releasenotes/notes/fix-vervose-warnings-efbbbfcb4b65a2a5.yaml
- test/terra/noise/test_noise_model.py
Fixes #1631 by removing verbose warnings when truncating parameters during the creation of a noise model from a backend.
As reported in #1631, verbose user warnings were shown up when creating a noise model from a backend that reports un-physical device parameters such as T2 > 2*T1 due to statistical errors in their estimation. This commit removes such warnings because they are not actionable (so useless) for users in the sense that there are no means other than truncating them to the theoretical bounds as done within `noise.device` module.
> Remove verbose warnings on parameter truncations when creating noise model from backend

- releasenotes/notes/fix_GPU_statevector-715da5ead0a59fb5.yaml
- src/controllers/aer_controller.hpp
- src/simulators/statevector/chunk/device_chunk_container.hpp
This is fix for issue #1646 and issue #1647 
Aer tried to allocate chunks fit in the free memory on GPU, but it caused memory allocation error.
This fix allocates 80% of free memory of GPU and rest of chunks are allocated on CPU memory.
Another fix is allocation of matrix buffer on GPU.
For noise sampling, maximum matrix size was not correct (was set by using original circuit before noise sampling)
> Fix for GPU simulator, memory allocation

- qiskit_aer/primitives/estimator.py
Sorry, my bad.
Estimator had transpiled circuits twice.
> Remove unnecessary transpile in Estimator

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/tests.yml
- pyproject.toml
- releasenotes/notes/add-python-311-support-027047fb389116dd.yaml
- requirements-dev.txt
- setup.py
- tools/install_openblas_i686.sh
- tox.ini
Python 3.11.0 was released on 10-24-2022, this commit marks the start of support for Python 3.11 in qiskit. It adds the supported Python version in the package metadata and updates the CI configuration to run test jobs on Python 3.11 and build Python 3.11 wheels on release.
> Add support for Python 3.11

- qiskit_aer/backends/aer_compiler.py
- qiskit_aer/library/control_flow_instructions/jump.py
- qiskit_aer/library/control_flow_instructions/mark.py
- releasenotes/notes/fix-topological-control-flow-e2f1a25098004f00.yaml
- test/terra/backends/aer_simulator/test_control_flow.py
During the inlining of control-flow into jump/mark instructions, the data-flow graph was losing information.  The tree-like form within `QuantumCircuit` implicitly creates a basic-block structure, which groups the whole control-flow body into a single block that must be executed atomicly (as seen by the outer circuit).  When inlining the body, this is no longer the case, and we have to take more care to ensure that topological iteration through the data-flow graph does not accidentally move jump/mark instructions into incorrect places, nor allow unrelated instructions to appear between jump/mark pairs if they were no originally in that control-flow block.
There are two components here; the former is solved by ensuring the jump/mark instructions span the full data width including clbits, …
> Fix data-flow analysis in control-flow jump/mark

- qiskit_aer/noise/device/models.py
- releasenotes/notes/fix-device-noise-models-2eca2f9c9dc25771.yaml
- test/terra/noise/test_device_models.py
Fixes #1648 by updating device noise models not to have excessive quantum errors on non-gate instructions such as measures and resets when creating them from BackendV2.
This commit fixes `qiskit_aer.noise.device.models.basic_device_gate_errors` not to generate `QuantumError`s (neither depolarizing nor relaxation) for `Measure` instruction and not to generate depolarizing errors for other non-Gate instructions when `Target` object is supplied.
> Fix device noise model from BackendV2 not to have excessive quantum errors on measures/resets

- contrib/runtime/aer_runtime.cpp
- qiskit_aer/backends/wrappers/bindings.cc
- qiskit_aer/quantum_info/states/aer_state.py
- qiskit_aer/quantum_info/states/aer_statevector.py
- releasenotes/notes/fix_aer_statevector_mps-c3dd40b936700ff4.yaml
- src/controllers/state_controller.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- test/terra/states/test_aer_statevector.py
Solve #1640 and #1641 by updateing `_aer_evolve_instruction`.
MC* instructions were mainly used in `AerStatevector`. However, these instructions are not supported in some methods, such as `matrix_product_state`, and an exception is thrown if they are called. This PR fixes this bug by using `X`. `Y`, `Z`, `CX`. `CY`, `CZ`, `H` and `U`.
> Use more gates for AerState to call state_controller

- qiskit_aer/noise/device/models.py
- releasenotes/notes/fix-temperature-a9c51c4599af3a49.yaml
Fix a bug in computation of the excited population from qubit frequency and temperature that can be used in noise model construction. 
As reported in #1638, there was an incorrect exponential factor of 2 and hence the excited population was incorrect (almost squared). This fix will affect users who generate a noise model using `NoiseModel.from_backend` with `temperature` option while it won't affect users of the default noise model that assumes no excitation (temperature=0).
> Fix incorrect computation of excited state population

- qiskit_aer/backends/wrappers/bindings.cc
- qiskit_aer/quantum_info/states/aer_state.py
- qiskit_aer/quantum_info/states/aer_statevector.py
- releasenotes/notes/set_seed_for_each_in_aerstatevec-ef5fcac628dec63b.yaml
- src/controllers/state_controller.hpp
- test/terra/states/test_aer_state.py
- test/terra/states/test_aer_statevector.py
Previously seed is not initialized in AerStatevector and then sampled results are always same. With this commit, a seed is initialized for each sampling and sampled results can be vary.
Previously, sampled counts are always same in multiple calls because `AerStatevector` uses the same seed to generate random values which are used in processing `sample_counts()`. More specifically, `_seed` is not initialized in `state_controller` if `seed_simulator` is not set. For example, following two sampled values `count0` and `count1` are the same.
```
circ = QuantumVolume(5, seed=1111)
state = AerStatevector(circ)
shots = 1024
counts0 = state.sample_counts(shots, qargs=range(5))
counts1 = state.sample_counts(shots, qargs=range(5))
```
Even if `seed_simulator` is set, the value is reused to …
> Set different seed for each sampling in AerStatevector

- qiskit_aer/__init__.py
- releasenotes/notes/deprecate-37-b3ec705b9f469b0b.yaml
This commit deprecates Python 3.7 support. During the deprecation window we will continue to fully support Python 3.7 and test it in CI, but it will emit a warning that we will be removing support for 3.7 in the future to inform users to upgrade to Python 3.8 or newer. The removal will occur during a future release at some point over the summer as the upstream Python EoL date is in June 2023. [1]
[1] https://devguide.python.org/versions/
> Deprecate Python 3.7 support in Qiskit Aer

- qiskit_aer/backends/backend_utils.py
- qiskit_aer/backends/qasm_simulator.py
- qiskit_aer/noise/noise_model.py
- src/framework/linalg/matrix_utils/matrix_defs.hpp
- src/framework/linalg/matrix_utils/smatrix_defs.hpp
- src/framework/linalg/matrix_utils/vmatrix_defs.hpp
- src/simulators/density_matrix/densitymatrix.hpp
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/superoperator/superoperator_state.hpp
- src/simulators/unitary/unitary_state.hpp
- test/terra/backends/aer_simulator/test_standard_gates.py
This commit adds support for the ECR (echo cross resonance) gate as described in [1] and [2] to aer. This is an entangling gate used on some IBM backends and being able for aer to simulate is import to be able to simulate those backends. Support for the gate is added to the density matrix, statvector, super operator, and unitary simulators.
[1] https://arxiv.org/abs/2008.08571
[2] https://qiskit.org/documentation/stubs/qiskit.circuit.library.ECRGate.html
TODO:
> Add ECR gate support to aer simulators

- qiskit_aer/primitives/sampler.py
- releasenotes/notes/fix-split-cregs-5b5494a92c4903e7.yaml
- test/terra/primitives/test_sampler.py
Fix the bug where the Sampler fails if the input circuit has multiple classical registers.
Fixes https://github.com/Qiskit/qiskit-aer/issues/1679
> Fix `Sampler` with multiple classical registers

- qiskit_aer/__init__.py
Previously the root of the qiskit_aer we were exporing certain modules and objects using relative imports to do this. However, the qiskit package sets up a metaimporter to redirect imports from qiskit.providers.aer to qiskit_aer (for backwards compatibility with the old aer name) the source package for these relative imports can get confused on subsequent imports if something also uses the legacy name (which qiskit itself does on it's optional imports to aer, so that it supports >1 version). While all the code functions correctly in this case Python emits a warning saying the package __spec__ doesn't match anymore. The simplest way to address these warnings is to use an absoulte import with the package name in it so there is no ambiguity in the source package on imports.
This commit makes …
> Switch from relative to absolute imports in root qiskit_aer

- .github/workflows/tests.yml
- CONTRIBUTING.md
- releasenotes/notes/remove-setup_requires-751a406e2782885e.yaml
- setup.py
- tox.ini
Executing manual `pip install` commands from within `setup.py` is somewhat frowned upon from a Python packaging perspective.  By far the preferred mechanism now is to clearly state the build dependencies in a non-code format (`pyproject.toml`), and let a PEP-517-compatible builder handle virtual-environment isolation and dependency management.
We already had the dependencies declared statically, this commit just removes the residual code in `setup.py`.
Fix #1688.
> Remove setup_requires and forced pip installs in setup.py

- qiskit_aer/backends/aer_simulator.py
- qiskit_aer/backends/qasm_simulator.py
Fixed #1633 
Replaced IBMQ with IBM Quantum in the documentation of aer_simulator and qasm_simulator.
Fixed the issue 1633
> Replace IBMQ with IBM Quantum in Aer documention.

- test/terra/backends/aer_simulator/test_truncate.py
- Remove the import statement of the deprecated module in test.
- The use of `qiskit.test.mock` is deprecated.
> Remove deprecated module import

- releasenotes/notes/fix_tensor_network_not_installed-a23b8ef65e6e643e.yaml
- src/controllers/aer_controller.hpp
- src/simulators/tensor_network/tensor_net.hpp
- test/terra/backends/simulator_test_case.py
Fix two issues:
Build error occurs when disabling cuQuantum for GPU enabled simulator. 
Also tensor network test cases run and fail even though tensor network method is not available.
Preprocessor to test cuQuantum is enabled was not correct.
Methods to be tested in test cases was not selected from available methods.
> Fix errors when disabling cuQuantum for GPU simulator

- qiskit_aer/backends/aer_simulator.py
- qiskit_aer/backends/backend_utils.py
- releasenotes/notes/support_break_and_continue_gates-bf30316fcacd4b6b.yaml
- test/terra/backends/aer_simulator/test_control_flow.py
Resolve #1706 by adding `break_loop` and `continue_loop` as basis gates.
Now terra supports transpilation of control-flow. This PR adds two basis gates `break_loop` and `continue_loop` to work Aer as a backend of `transpile()`.
> support break_loop and continue_loop

- releasenotes/notes/optimized_stabilizer-f696742e7f881d0d.yaml
- src/framework/pybind_casts.hpp
- src/simulators/stabilizer/binary_vector.hpp
- src/simulators/stabilizer/clifford.hpp
- src/simulators/stabilizer/pauli.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
This PR improves performance of stabilizer simulator.
This PR changes data layout of stabilizer/destabilizer bit register, this will improve memory access of bit wise operations. Now most of operations can be written as 64-bits integer logical calculations. This layout change will be effective for GPU implementation (future work)
Also measure operation is improved by implementing 2-bits integer adder to calculate phase. 
This graph shows simulation time comparison using surface code for 10000 shots.
> Optimization of stabilizer simulator

- .github/workflows/tests.yml
- qiskit_aer/primitives/estimator.py
- releasenotes/notes/add-grouping-fcc4fad69ccdac26.yaml
- test/terra/primitives/test_estimator.py
- tox.ini
https://github.com/Qiskit/qiskit-aer/issues/1700
Benchmark code:
```python
ansatz = RealAmplitudes(num_qubits=num_qubits, reps=1)
observables = [SparsePauliOp("".join(pauli_str)) for pauli_str in product("IZ", repeat=num_qubits)]
parameter_values = list(np.random.rand(1, ansatz.num_parameters))
estimator = Estimator(abelian_grouping=abelian_grouping)
start = time()
result = estimator.run(circuits=[ansatz]*len(observables), observables=observables, parameter_values=parameter_values*len(observables)).result()
elapsed_time = time() - start
```
Benchmark result:
> Add abelian_grouping to Estimator

- qiskit_aer/aerprovider.py
- qiskit_aer/backends/aerbackend.py
- qiskit_aer/backends/pulse_simulator.py
- releasenotes/notes/deprecate-pulse-simulator-27cde3ece112c346.yaml
- test/terra/backends/test_parameterized_qobj.py
This commit deprecates the PulseSimulator backend for qiskit aer. For the past several releases development on the pulse simulator has mostly been frozen as the combined efforts for improving pulse level simulation have been working on Qiskit Dynamics instead. This commit marks the legacy PulseSimulator as deprecated and points existing users to Qiskit Dynamics instead.
Closes #1722
> Deprecate PulseSimulator backend

- qiskit_aer/quantum_info/__init__.py
- qiskit_aer/quantum_info/states/__init__.py
- qiskit_aer/quantum_info/states/aer_densitymatrix.py
- releasenotes/add-aer-densitymatrix-959c261c954fa60e.yaml
- test/terra/states/test_aer_densitymatrix.py
This is a PR to implement AerDensityMatrix, which is a fine-tuned version of #1676.
When this PR is approved, #1676 should be closed at the same time.
> Implement AerDensityMatrix

- qiskit_aer/quantum_info/__init__.py
- qiskit_aer/quantum_info/states/aer_densitymatrix.py
#1732 added `AerDensityMatrix` but its docs are not maintained.
This PR adds docs that sphnix can include this class in Aer's docs.
`AerDensityMatrix` included the same description with `DensityMatrix` for the same method. Because `AerDensityMatrix` inherits `DensityMatrix`, such description is not necessary.
In addition, `qiskit_aer/quantum_info/__init__.py` did not list `AerDensityMatrix` and this PR adds it.
> Add documentation for density matrix

- .git-blame-ignore-revs
- CONTRIBUTING.md
This commit adds a new file with the SHA1 of commits to ignore when running git blame. This is important because of the recent adoption of black and clang-format as our code formatting tool in #1630 we caused a large amount of code churn to change the code formatting. However, using the ignore file is a local opt-in feature for git and not something we can enable globally by default. To facilitate this a section is added to the bottom of the contributing guide to document how this file can be used.
> Add git blame ignore file

- releasenotes/notes/fix-cuStateVec_enable-0936f2269466e3be.yaml
- src/simulators/state_chunk.hpp
Currently it seems the cuQuantum support version of Qiskit Aer cannot be built.
This PR fixes the build error.
I attach a Dockerfile to build a fixed Qiskit Aer with cuQuantum support for reference: [Dockerfile.zip](https://github.com/Qiskit/qiskit-aer/files/11007658/Dockerfile.zip)
This PR branch is cloned and CUDA Compute Capability of 7.5 which is compatible with NVIDIA T4 is used. The Docker image should be approximately 10.7 GB in size.
Example codes used inside a container to verify the operation are as follows:
```python
>>> from qiskit import QuantumCircuit
>>> from qiskit_aer.quantum_info import AerStatevector as Statevector
>>> qc = QuantumCircuit(2)
>>> qc.h(0)
>>> qc.cx(0, 1)
>>> sv = Statevector(qc, device='gpu', custatevec_enable=True)
```
> Fix how to reference to config.cuStateVec_enable

- releasenotes/notes/use_omp_set_max_active_levels-7e6c1d301c4434a6.yaml
- src/controllers/aer_controller.hpp
Fix #1751
This PR uses `omp_set_max_active_levels` instead of `omp_set_nested` which shows warnings in some environment.
> use `omp_set_max_active_levels` instead of `omp_set_nested`

- qiskit_aer/backends/aerbackend.py
- test/terra/backends/aer_simulator/test_metadata.py
The PR https://github.com/Qiskit/qiskit-terra/pull/9849 proposes that `QuantumCircuit.metadata` should always be a ``dict``, rather than a ``dict`` or ``None``. This is a matching PR to ensure that aer does not manually set it to ``None``, which that PR deprecates.
> Ensure QuantumCircuit.metadata is always a dict

- qiskit_aer/primitives/estimator.py
- releasenotes/notes/estimator-variance-type-2b04ff7bcd305920.yaml
- test/terra/primitives/test_estimator.py
> Fix #1764 (variance type in Estimator)

- qiskit_aer/backends/aer_compiler.py
- qiskit_aer/backends/wrappers/aer_circuit_binding.hpp
- releasenotes/notes/fix_param_binding_for_pram_circuit-50e64efbedaec8fd.yaml
- src/framework/circuit.hpp
- src/framework/operations.hpp
- test/terra/backends/test_parameterized_qobj.py
`AerCircuit` is created from a circuit by iterating its instrucitons while skpping barrier. This leads inconsistency with positions of parameter bindings. This commit adds barrier instruction to the class and keeps positions of parameter bindings.
This fixes #1774 
`AerCircuit` is created while skipping barrier instructions. However, skipping barrier instructions makes positions of parameter bindings wrong. This fix use `barrier()` a new method of `AerCircuit` and then keeps positions of parameter bindings consistent.
> Fix wrong set of parameters in circuits with barriers

- cmake/FindPybind11.cmake
- pyproject.toml
Remove `REQUIRED` to find `PythonLibs` in FindPybind11
As @henryiii mentioned [here](https://github.com/Qiskit/qiskit-aer/pull/1786#issuecomment-1526151867), `REQUIRED` is not necessary to find `PythonLibs`. By removing this, Aer's CI will be back from the following error:
```
Could NOT find PythonLibs (missing: PYTHON_LIBRARIES) (found version "3.7.15")
```
> Remove REQUIRED to find PythonLibs in FindPybind11

- .github/workflows/docs.yml
- qiskit_aer/primitives/sampler.py
- test/terra/primitives/test_estimator.py
I forgot to remove the method.
Fix #1803
> Remove Sampler.close, assert DeprecationWarning of opflow, and update dependency

- releasenotes/notes/fix_mpi_procs-68b76c11fe7a6b8e.yaml
- src/controllers/aer_controller.hpp
This fix sets MPI processes and ranks correctly to enable MPI parallelization.
Because qobj is not used, `Aer::Controller::execute` function with qobj is not called and MPI processes and ranks are not set correctly.
So this fix calls `MPI_Comm_size` and `MPI_Comm_rank` in another `execute` function.
> Fix setting MPI processes and ranks

- qiskit_aer/noise/device/models.py
- qiskit_aer/noise/noise_model.py
- releasenotes/notes/fix-none-handling-in-noise-model-34fcc9a3e3cbdf6f.yaml
- test/terra/noise/test_device_models.py
- test/terra/noise/test_noise_model.py
Fixes `NoiseModel.from_backend` not to fail when calling it with a V2 backend having faulty qubits such that T1 and T2 are None in the `target.qubit_properties`. Fixes #1779 and #1815.
Previously, `NoiseModel.from_backend`  had no handling of None case for T1 or T2 value defined in a `target.qubit_properties` and raised a `TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'` as reported in #1779 and #1815. This commit updates `basic_device_gate_errors` function and `NoiseModel.form_backend` method so that both handle None for T1 or T2 without failure. After this commit, in the case when T1 and T2 values are None for a qubit, an identity QuantumError (i.e. effectively no thermal relaxation error) will be added to the qubit for all gates acting on qubits including the qubit.
> Fix handling of None in noise model construction from BackendV2

- qiskit_aer/backends/aer_simulator.py
- qiskit_aer/backends/qasm_simulator.py
- Fix to https://github.com/Qiskit/qiskit-aer/issues/1611 (wild '~')
- Add missing aer_simulator options with description
> Fix typos in aer_simulator, qasm_simulator docs

- qiskit_aer/primitives/estimator.py
- releasenotes/notes/primitives-grouping-index-bug-56f69afbdc3e86a0.yaml
- test/terra/primitives/test_estimator.py
Fix #1837 
I misunderstand the order of list of operators from `PauliList.group_commuting`, so the indices are incorrect.
> Fix the grouping index bug in Estimator

- qiskit_aer/backends/aerbackend.py
- releasenotes/notes/remove_aer_circuit_from_metadata-e4fe09029c1a3a3c.yaml
- test/terra/backends/aer_simulator/test_circuit.py
Since #1772, results of C++ library include `AerCircuit` as metadata to identify a template circuit. This metadata is internally delivered to users by calling `backend.run().result()`. If a user copies the metadata, errors are happened because `AerCircuit` is not serializable.
Remove `AerCircuit` objects from any results of `backend.run()`
> Remove `AerCircuit` from result of `backend.run()`

- setup.py
Until https://github.com/Qiskit/qiskit-terra/pull/10309 is included in terra's release, Aer CI needs numpy with lower version than 1.25.
`product` is deprecated since numpy 1.25. https://github.com/Qiskit/qiskit-terra/pull/10309 replaced it with `prod` but is not released yet. Until the next terra is released, Aer needs lower version than numpy 1.25.
> pin numpy version lower than 1.25

- qiskit_aer/library/default_qubits.py
- releasenotes/notes/save_statevector_for_qasm3_circ-642ade99af3ff0d2.yaml
- requirements-dev.txt
- test/terra/backends/aer_simulator/test_save_statevector.py
Resolve #1793.
Dedup `Qubits` from return value of `default_qubits()`.
> Support save_statevector for QuantumCircuit from QASM3 string

- contrib/runtime/aer_runtime.cpp
- contrib/runtime/aer_runtime_api.h
- releasenotes/notes/fix_aer_state_initialize_api-0c2c237a606648ef.yaml
`aer_state_initialize()` needs to take an argument `handler` to be initialized.
`aer_state_initialize()` in C API does not take any arguments. However, the function is to initialize a state (`handler`) created by `aer_state()` and needs to take `handler`. Actually, example codes pass `handler` to the function (interestingly C compiler allows its compilation).
This PR changes `aer_state_initialize()` from 
```
void* aer_state_initialize();
```
to
```
void aer_state_initialize(void* state);
```
> Fix an issue in `aer_state_initialize()` of C API

- README.md
The citation file has moved from the metapackage to the Terra repo. The current link in the README leads to a 404.
The new location is https://github.com/Qiskit/qiskit-terra/blob/main/CITATION.bib.
> Fix link to Qiskit's bib-file

- tools/deploy_documentation.sh
Follow up on https://github.com/Qiskit/qiskit-aer/pull/1748
The documentation is correctly deployed to https://qiskit.org/ecosystem/aer/ and the redirect is working. So, no need to upload to `/documentation` anymore.
> remove deploy documentation to /documentation/aer

- releasenotes/notes/correct_measure_in_state_controller-a92692fd7083c476.yaml
- src/controllers/state_controller.hpp
`measure` in libaer.so was wrong.
In libaer.so, measured `i`-th qubit stores in `N-i-1`-th memory slot. Therefore, to read measured value, libaer.so must read `N-i-1`-th memory slot. Originally, it reads `i`-th memory slot wrongly.
> correct bit ordering in measure of state_controller

- releasenotes/notes/skip-cuda-requirements-927ddce79b9e7108.yaml
- setup.py
Define environment variable to allow Qiskit-Aer to be built without CUDA requirements
It is convenient to sometimes be able to leverage an existing system CUDA installation as opposed to load redundant python CUDA packages that provide the same functionality. This enables having smaller footprint in the Qiskit-Aer installation and facilitates development and testing with CUDA. This PR enables an environment variable to control this at build time.
> Define environment variable to allow Qiskit-Aer to be built without CUDA requirements

- qiskit_aer/backends/backend_utils.py
- releasenotes/notes/stabilizer_rotation-8ce2effd9578ee0a.yaml
- src/simulators/circuit_executor.hpp
- src/simulators/stabilizer/stabilizer_state.hpp
- src/simulators/state.hpp
- test/terra/backends/aer_simulator/test_rotation.py
- test/terra/primitives/test_estimator.py
- test/terra/primitives/test_sampler.py
- test/terra/reference/ref_rotation.py
This PR adds rotation gates (rx, ry and rz gates) to stabilizer if input theta is multiple of pi/2.
#1928 
stabilizer method is automatically selected by `method=automatic` when all the input thetas of rotation gates are multiple of pi/2. Or if `method=stabilizer  is set, Aer raises and exception when invalid thetas are passed.
> Add rotation gates to stabilizer

- qiskit_aer/noise/device/models.py
- releasenotes/notes/fix-excitation-population-6af281a61f659dda.yaml
- test/terra/noise/test_device_models.py
- tox.ini
Fixed a bug where thermal relaxation errors with incorrect excited state population are created when building a noise model from BackendV2 with non-zero temperature.
Fixed #1937 .
Fixed an oversight in the handling of frequency units when building a noise model from BackendV2. For that, as suggested in #1937, I changed the `qiskit_aer.noise.device.models._excited_population` to expect the frequency argument in Hz (from GHz) so that the path for BackendV2 works correctly without any updates, and, instead, updated the path for BackendV1.
> Fix incorrect excited state population when building noise model from BackendV2

- qiskit_aer/primitives/sampler.py
- releasenotes/notes/sampler-performance-81e1649ec4657aad.yaml
Same idea with https://github.com/Qiskit/qiskit-aer/pull/1840
Benchmark code:
```python
import numpy as np
from qiskit.circuit.library import EfficientSU2
from qiskit_aer.primitives import Sampler
rng = np.random.default_rng(15)
qc = EfficientSU2(3)
qc.measure_all()
num_circuits = 1000
sampler = Sampler()
parameter_values = rng.random((num_circuits, qc.num_parameters))
circuits = [qc] * num_circuits
%timeit sampler.run(circuits, parameter_values).result()
```
0.12.2: 716 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
This PR: 534 ms ± 4.33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> Improve performance of sampler experiment

- qiskit_aer/primitives/estimator.py
- releasenotes/notes/estimator-order-bug-a341d82075f47046.yaml
- test/terra/primitives/test_estimator.py
When I implement https://github.com/Qiskit/qiskit-aer/pull/1935, I found a bug in estimator.
This is not a problem in most cases, but if user passes the circuits in a strange order as shown below example, an error will occur until 0.12.2.
```python
job = estimator.run([qc1, qc2, qc1, qc1, qc2], ["Z"] * 5, [[], [1], [], [], [1]])
```
This PR fixes it.
> Fix the order bug in Estimator

- releasenotes/notes/fix_omp_nested_performance-a3d55f3e85366a5b.yaml
- src/controllers/aer_controller.hpp
- src/simulators/statevector/qubitvector.hpp
- src/simulators/unitary/unitarymatrix.hpp
- src/transpile/fusion.hpp
OpenMP nested parallel simulation for parallel experiments + parallel state update was very slow when using gate fusion.
This occurs when using parameter binding for 15 or more number of qubits.
Inside gate fusion, unitary simulator is called to calculate fused matrix and uses omp region frequently that waste thread resource for nested parallelism. This fix removes parallel regions for gate fusion.
> Fix nested parallel performance

- qiskit_aer/backends/backend_utils.py
- test/terra/backends/simulator_test_case.py
- test/terra/decorators.py
- test/terra/noise/test_noise_model.py
- test/terra/noise/test_quantum_error.py
- test/terra/reference/ref_algorithms.py
- test/terra/reference/ref_kraus_noise.py
- test/terra/reference/ref_measure.py
- test/terra/reference/ref_pauli_noise.py
- test/terra/reference/ref_reset_noise.py
- test/terra/reference/ref_save_expval.py
- tools/generate_qobj.py
- tools/verify_wheels.py
Qiskit/qiskit#10797 deprecates `QuantumCircuit.i` in favor of `QuantumCircuit.id` (along with another bunch of duplicated gate methods), so this PR updates the usage. 
Also `QuantumCircuit.iden` doesn't exist since quite some time, so that usage is also removed.
It might be good to hold off merging this until Qiskit/qiskit#10797 has gone through, to be sure there aren't any last minute changes.
> Update usage of ``QuantumCircuit.id``

- docs/_templates/autosummary/class.rst
Moved all the methods and attributes into class pages to speed up the building process of the documentation with the new ecosystem sphinx theme. This change unblocks this [PR](https://github.com/Qiskit/qiskit-aer/pull/1946).
See https://github.com/Qiskit/qiskit/pull/10455 for more information.
> Move methods into class pages for docs

- qiskit_aer/backends/backend_utils.py
- releasenotes/notes/support_switch_transpilation-67e16241b94faa86.yaml
- test/terra/backends/aer_simulator/test_control_flow.py
Resolve #1960
``switch_case`` operations are not in basis gates. This PR adds it to basis gates of several methods.
In addition,  tests for control flow with `stabilizer` method are added.
> support transpilation of switch_case

- qiskit_aer/primitives/estimator.py
- test/terra/primitives/test_estimator.py
Deprecate approximation option. `approximation=True` will be the default in the future.
If users want to use `approximation=False`, they should use `BackendEstimator` instead.
> Deprecate approximation option in Estimator

- docs/_templates/autosummary/class_no_inherited_members.rst
This PR creates another template for the classes without inherited members simplifying the `class.rst` template file.
Also, In the original `class.rst`, we have two consecutive for, one for all methods, and another one for only the inherited_members. With this two for, we are duplicating the entries of the inherited methods (they appear two times in the page). In a previous [pull request](https://github.com/Qiskit/qiskit-aer/pull/1958), I added an extra if but that removed the inherit_members that we had before. This PR fixes that problem.
> Fix templates documentation

- .github/workflows/deploy.yml
This is a fix for deploy of release 0.13.0
GPU build did not skip Python 3.12
> Add skip Python 3.12 for GPU build

- releasenotes/notes/fix_initialize_with_global_phase-56d529cd9c09c2fa.yaml
- src/simulators/circuit_executor.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/state.hpp
- src/simulators/statevector/statevector_executor.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/tensor_network/tensor_net_executor.hpp
- src/simulators/tensor_network/tensor_net_state.hpp
- test/terra/backends/aer_simulator/test_initialize.py
This PR is fix for issue #1977 
The global phase variable was not multiplied after `initialize` operation, this fix multiplies the global phase to the state in `initialize` operation.
Also `matrix_product_state` method did not use global phase, so this PR adds support of global phase in MPS method
> Applying global phase multiplication to initialize operation

- qiskit_aer/primitives/estimator.py
- test/terra/primitives/test_estimator.py
I deprecated approximation option in Estimator https://github.com/Qiskit/qiskit-aer/pull/1963.
But the argument should not be deprecated because users cannot turn off the warning message.
This PR reverts one deprecation message from the PR.
> Revert too many deprecations in Estimator

- qiskit_aer/primitives/estimator.py
- releasenotes/notes/remove-opflow-estimator-a3b64cfe8a4fd6b3.yaml
- test/terra/primitives/test_estimator.py
This PR removes the only `opflow` dependency in Aer (supporting `PauliSumOp` as an input to the Estimator). The `opflow` module was deprecated and is on its way of being removed from Qiskit, which means it will no longer be available for downstream projects (see https://github.com/Qiskit/qiskit/pull/11111). Once the linked PR is merged, importing `opflow` in the Aer primitives will break the neko integration tests (see https://github.com/Qiskit/qiskit/actions/runs/6848167193/job/18617803285?pr=11111#step:2:1073), so if I am not mistaken, the optimal path would be to remove the use of opflow first in Aer and then in Qiskit.
I have added an upgrade release note documenting the removal of the supported type.
> Remove use of opflow in `Estimator`

- qiskit_aer/backends/aer_compiler.py
- releasenotes/notes/fix_transpiler_lvl_for_dynamic_circuit-4ead3b497bbcc632.yaml
This PR fixes issue #1997 
id gate was removed by transpiler called from aer_compiler without optimization_level for dynamic circuits.
adding optimization_level=0 to avoid removing id gates
> Add optimization_level=0 to transpiler for compiling dynamic circuits

- releasenotes/notes/fix_stabilizer_ry_gate-07538d8a2462c09d.yaml
- src/simulators/stabilizer/stabilizer_state.hpp
This is fix for issue #1999 
The implementation of ry gate of stabilizer method was wrong, conversion of ry(PI/2) and ry(3PI/2) to Clifford gates was inverted
> Fix ry gate for stabilizer

- qiskit_aer/backends/backend_utils.py
- qiskit_aer/backends/statevector_simulator.py
- qiskit_aer/backends/unitary_simulator.py
- releasenotes/notes/psutil-added-ffb2a4b5956fa03d.yaml
- setup.py
Currently Aer is using Qiskit's local_hardware_info() function which to determine the total amount of system memory which is used to compute the largest statevector the system can build. However, this function wasn't really intended to be used outside of Qiskit and also Qiskit is looking to remove the memory reporting (see: Qiskit/qiskit#11254). This commit just pivots to using psutil directly which is what qiskit is doing internally.
> Directly use psutil to get total system memory

- releasenotes/notes/fix_sample_measure_roerr-747b955aa2bf778c.yaml
- src/simulators/batch_shots_executor.hpp
- src/simulators/circuit_executor.hpp
- src/simulators/multi_state_executor.hpp
This PR fixes order of applying read out error in sampling measures in the circuit executor classes,
that causes different results from older version of Aer.
The order to apply read out error in sampling measure was reverse ordering by popping from back of vector in older version of Aer. So this fix reorder loop to apply consistent random values to read out error as older version.
This PR fixes failure of Qiskit's test case `test.python.primitives.test_backend_estimator.TestBackendEstimator.test_layout`
Also this PR includes fix of checking if batch execution on GPU can be applied or not.
> Reverse ordering to read out error in sampling measure

- releasenotes/notes/fix_extstabilizer_thread_safety-c85e926c7ecb8dfb.yaml
- src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
Fixes issue #1932. Extended stabilizer simulator was sharing a random number engine between states in ``apply_ops_parallel``, leading to thread safety issues.
Now, a new random number engine is provided for each state in parallel, so results should be consistent with the same initial random seed.
> Fix extended stabilizer thread safety in apply_ops_parallel

- src/framework/utils.hpp
The unistd.h API that had been used for both Linux and macOS is not always available in macOS environments, for example when building with upstream clang rather than AppleClang.
Closes https://github.com/Qiskit/qiskit-aer/issues/1923
> Use Apple-specific API to determine system memory on macOS

- qiskit_aer/backends/aer_compiler.py
- qiskit_aer/backends/name_mapping.py
- qiskit_aer/library/default_qubits.py
- qiskit_aer/library/save_instructions/save_amplitudes.py
- qiskit_aer/library/save_instructions/save_data.py
- qiskit_aer/library/save_instructions/save_expectation_value.py
- qiskit_aer/library/set_instructions/set_density_matrix.py
- qiskit_aer/library/set_instructions/set_matrix_product_state.py
- qiskit_aer/library/set_instructions/set_stabilizer.py
- qiskit_aer/library/set_instructions/set_statevector.py
- qiskit_aer/library/set_instructions/set_superop.py
- qiskit_aer/library/set_instructions/set_unitary.py
- qiskit_aer/noise/errors/quantum_error.py
- qiskit_aer/noise/errors/standard_errors.py
- qiskit_aer/noise/noise_model.py
- test/terra/extensions/test_save_amplitudes.py
- test/terra/extensions/test_save_expval.py
- test/terra/noise/test_noise_transformation.py
- test/terra/noise/test_quantum_error.py
The ``qiskit.extensions`` module has been pending deprecation since Qiskit 0.45. It is deprecated for 0.46 and removed in 1.0.
This is blocking Qiskit/qiskit#11488 and Qiskit/qiskit#11498.
This removal concerns the import location of ``UnitaryGate`` and the usage of the ``ExtensionError``. The first is easily fixed, whereas for the latter I tried using ``ValueError`` or ``TypeError``, which seemed to cover the error meanings. Technically, this is a breaking change and we could introduce an intermediary class that inherits from the deprecated ``ExtensionError`` and the new choice of error. However, since we will soon be changing to 1.0 and we also skipped this in Qiskit Terra (as we thought it highly unlikely that users are actually relying on this error type) it might be fine to just …
> Remove usage of ``qiskit.extensions``

- .github/workflows/unit-tests-latest-qiskit.yml
- releasenotes/notes/fix_for_daily_tests-3fa9df70fb3e53ee.yaml
- test/terra/noise/test_device_models.py
- test/terra/states/test_aer_statevector.py
This PR is collections of fixes for the latest Qiskit
Removed deprecate function test in test.terra.states.test_aer_statevector.TestAerStatevector.test_number_to_latex_terms
Sorted the output properties in test.terra.noise.test_device_models.test_basic_device_gate_errors_from_target_and_properties to compare correctly.
> Fixes of tests for the latest Qiskit

- .github/workflows/deploy.yml
For the previous few releases the GPU wheel builds have failed to upload. The root cause of this issue was that an earlier CI stage was deleting on the locally cached docker images to free up space for installing CUDA and all the GPU build requirements in the test VM. Removing these docker images prevented the upstream action we run to publish the wheels from working as it relied on having a docker image available that couldn't be fetched from the default image repository. This commit fixes this issue for future releases by ensuring we don't delete the local docker cache in the GPU publish jobs. For the 0.13.2 releases this was manually applied and run to publish the wheels and this PR is applying the fix for future releases.
> Fix GPU wheel builds on release

- releasenotes/notes/fix_test_for_Qiskit0.45.2-e0544949be8e77fb.yaml
- test/benchmark/vqe_application.py
- test/terra/backends/aer_simulator/test_truncate.py
- test/terra/common.py
- test/terra/reference/ref_diagonal_gate.py
This is fix of test cases for update on the latest Qiskit
Removed unnecessary `from qiskit import Aer `
Using `circuit.library.Diagonal` instead of deprecated `QuantumCircuit.diagonal`
<s>Replace unittest.TestCase to testtools.TestCase to remove warmings on Python 3.12</s> reverted because  testtools.TestCase does not have subTest
> Fix test cases for Qiskit 0.45.2

- test/terra/backends/aer_simulator/test_conditional.py
- test/terra/reference/ref_diagonal_gate.py
- test/terra/reference/ref_multiplexer.py
- test/terra/states/test_aer_state.py
- test/terra/states/test_aer_statevector.py
This PR removed remaining diagonal, isometry and uc that causes test failure with the latest Qiskit
Removed `circuit.diagonal` used in test cases and replaced to `circuit.append(DiagonalGate(), [])`
Replacing isometry and uc as well
> Remove remaining diagonal, isometry and uc

- qiskit_aer/primitives/estimator.py
- qiskit_aer/primitives/sampler.py
- test/terra/primitives/test_estimator.py
https://github.com/Qiskit/qiskit/pull/11051 removed some private attributes from `Sampler` and `Estimator` in the process of streamlining the API. This PR adds them back in because super() no longer does so.
> Add private primitive attributes removed by qiskit

- .github/workflows/deploy.yml
This commit changes the configuration of the deploy workflow to install the sdist last. Publishing the sdist first causes disruption for downstream projects that are using qiskit aer in CI as pip will eagerly try to download the latest version even if only an sdist is present for it. To avoid disruption for downstream users this updates the sdist job to run only after we've uploaded the wheels for the tier 1 platforms to pypi (which is what most people are running in CI).
> Only run sdist build after wheel builds are uploaded

- qiskit_aer/backends/aer_simulator.py
- qiskit_aer/backends/wrappers/aer_controller_binding.hpp
- releasenotes/notes/fix_mps_required_memory_estimation-75a9bb739701046c.yaml
- src/controllers/aer_controller.hpp
- src/framework/config.hpp
- src/simulators/circuit_executor.hpp
- src/simulators/matrix_product_state/matrix_product_state.hpp
- src/simulators/matrix_product_state/matrix_product_state_size_estimator.hpp
This PR fixes estimation of required memory size for MPS method #2056 
Estimated too large required memory because memory size was increased by all the 2-qubit gates.
Also this PR adds option to ignore check of required memory vs input circuit if `max_memory_mb=-1` is set
> Fix required memory estimation for MPS

- .github/workflows/build.yml
- pyproject.toml
- qiskit_aer/library/save_instructions/save_data.py
- tox.ini
This PR fixes error of lint test
> Fix qiskit-aer/library/save-instructions/save_data.py

- pyproject.toml
numpy C bindings are handled through pybind11 which does not depend on numpy. numpy is otherwise only a runtime dependency of qiskit-aer. This change just saves a download during build.
> Remove unnecessary numpy build dependency

- qiskit_aer/backends/aer_compiler.py
- qiskit_aer/backends/aerbackend.py
- releasenotes/notes/fix_noise_dynamic_circuits-59c6cf0061e956a8.yaml
This is fix for issue #2091 
This issue was caused by transpiler called inside AerCompiler to build circuit with control flow ops, that translates some gates into unnecessary gate and some labels for noise were dropped. 
To prevent this, this fix uses custom pass manager only with Decompose jump and mark ops
> Fix AerCompiler to use custom pass manager to decompose control flow ops

- docs/conf.py
- releasenotes/notes/switch_source_links_to_link_directly_to_github-bc554dee4f145c7b.yaml
- tox.ini
This is a follow-up to https://github.com/Qiskit/qiskit/pull/11851 and addresses https://github.com/Qiskit/documentation/issues/517 by switching out the sphinx.ext.viewcode for the sphinx.ext.linkcode extension which allows our GitHub links in the documentation to be linked to the specific lines of code, not just the file. This was tested successfully in https://github.com/Qiskit/qiskit_sphinx_theme/pull/589 so now we want to implement it in the qiskit, runtime, and provider repos.
Example links generated in this PR build:
a class definition https://github.com/Qiskit/qiskit-aer/blob/main/qiskit_aer/backends/aer_simulator.py#L40-L1046
a method https://github.com/Qiskit/qiskit-aer/blob/main/qiskit_aer/noise/noise_model.py#L849-L910
a function …
> Use sphinx.ext.linkcode for more precise source code links

- src/framework/operations.hpp
- src/noise/noise_model.hpp
- src/simulators/batch_shots_executor.hpp
- src/simulators/multi_state_executor.hpp
- src/simulators/shot_branching.hpp
- src/simulators/statevector/statevector_executor.hpp
- src/simulators/tensor_network/tensor_net_executor.hpp
- src/transpile/fusion.hpp
This PR is fix for noise sampling with shot-branching
Runtime noise sampling used for shot-branching/batch execution on GPU has issue when noise is applied on labeled gates.
[WIP] There is issue remaining in shot-branching + runtime parameter binding with noises
> Fix noise sampling on shot-branching

- test/terra/backends/aer_simulator/test_chunk.py
- test/terra/primitives/test_sampler_v2.py
- test/terra/states/test_aer_densitymatrix.py
- test/terra/states/test_aer_statevector.py
This is fix of test cases fails with the latest Qiskit
The test case with chunk parallelization fails, because qiskit.transpiler returns circuit with large unitary gates from QuantumVolume circuit that can not be cache blocked for chunk parallelization. So for this test I set basis_gates without unitary gate not to be fused by transpiler.
Also modified some tests for the latest Qiskit
> Fix tests for the latest Qiskit

- releasenotes/notes/fix_enabling_cuStateVec-1a2f1d3e35f3129d.yaml
- src/simulators/density_matrix/densitymatrix_state.hpp
- src/simulators/parallel_state_executor.hpp
- src/simulators/statevector/chunk/cuStateVec_chunk_container.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/unitary/unitary_state.hpp
This PR is fix for issue #2144 `cuStateVec_enable=True` was not correctly set to the simulators
`cuStateVec_enable` option was only enabled on parallel simulators since CircuitExecutor classes were implemented.
This fix sets this option correctly before allocating the simulator states.
> Fix cuStateVec_enable option

- test/terra/backends/test_parameterized_qobj.py
- test/terra/states/test_aer_densitymatrix.py
There are some test failures due to random seed. This PR fixes them.
https://github.com/Qiskit/qiskit-aer/actions/runs/9281302491/job/25537198379?pr=2150
The main branch fails the same test too.
https://github.com/Qiskit/qiskit-aer/actions/runs/9280081728/job/25533923381
> Fix random seed of unit tests

- qiskit_aer/backends/aerbackend.py
- releasenotes/notes/fix_AerBackend_set_max_qubits-fee8f0e104580e33.yaml
- test/terra/primitives/test_sampler.py
This is fix for PR #2084 again
Setting method option to Sampler overwrote `n_qubits` of configuration.
So this fix set `n_qubits` by using _`set_configuration_option` function to overwrite again.
I added test case to test all supported methods
> Fix AerBackend.set_max_qubits

- qiskit_aer/backends/aerbackend.py
- qiskit_aer/noise/errors/base_quantum_error.py
- qiskit_aer/noise/errors/quantum_error.py
- qiskit_aer/noise/noise_model.py
- test/terra/noise/test_noise_model.py
This refactors QuantumError to inherit from a `BaseQuantumError` class, and `NoiseModel` to allow adding BaseQuantumErrors rather than only QuantumErrors.
~Depends on #2158~
This is a pre requisit for adding the optimized PauliLindbladError and PauliError operators proposed in #2154 
On its own this PR should have no visible changes to current users.
> Add `BaseQuantumError` class

- qiskit_aer/backends/aer_compiler.py
- releasenotes/notes/fix_inline_in_compiler-6ecdfcf38e2fa0c9.yaml
- test/terra/backends/aer_simulator/test_control_flow.py
Resolve #2171 
Qubit mapping is not correctly resolved in control flow since cf510a2. This PR is to fix this issue.
In `AerCompiler`, all of instructions are inlined. Qubits and clbits of a sub-circuit may be different from of its parent. Therefore, previously, they are inlined by using decomposition of trranspiler and transpiler coordinates correct qubits and clbits. However, in cf510a2, decomposition is implemented in `AerCompier` and mapping of qubits and clbits may be broken.
With this PR, qubits and clbits of top-parent are always used in the inlined circuits.
> fix bit mapping inconsistency in inline of AerCompiler

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/neko.yml
- constraints.txt
- pyproject.toml
- requirements-dev.txt
- src/simulators/statevector/chunk/thrust_kernels.hpp
This PR is fix for recent CI failures
- Fix cvxpy issue on MacOS
- Fix yum install issue caused by CentOS EOL
- Fix version of CUDA (also merged #2174 )
- Use scipy 1.13.1 to avoid failure of neko temporary
> Fixes for recent CI failures

- qiskit_aer/backends/aer_compiler.py
- qiskit_aer/backends/backend_utils.py
- qiskit_aer/noise/errors/quantum_error.py
- qiskit_aer/utils/noise_model_inserter.py
Using Terra's `CircuitInstruction` like a tuple is a legacy access pattern.  The pattern of using named access attributes was introduced about two years ago, and the legacy format is about to be deprecated. This fixes up the last couple of uses.
Terra 1.2 will likely deprecate this.
> Fix legacy accesses of `CircuitInstruction`

- qiskit_aer/backends/aer_simulator.py
- qiskit_aer/primitives/estimator_v2.py
- qiskit_aer/primitives/sampler_v2.py
- releasenotes/notes/fix_from_backend-a885d43caf390873.yaml
This PR fixes `EstimatorV2.from_backend` and `SamplerV2.from_backend` to use pre-defined AerSimulator for simulation
With this fix, user can define specific simulator object with backend options instead of passing options for V2 primitives.
for example, following script can use AerSimulator with statevector simulation and with noise model
```
sim = AerSimulator(method="statevector", noise_model=noise_model)
estimator = EstimatorV2.from_backend(sim)
```
This PR fixes `from_backend` that initialized backend object by calling `AerSimulator.from_backend` but  when input backend is AerSimulator just copy it.
> Fix from backend of V2 primitives to use existing AerSimulator

- test/terra/backends/aer_simulator/test_noise.py
- test/terra/backends/aer_simulator/test_shot_branching.py
This is a follow-up to #2179.  This PR provides similar fixes in two tests.
> Fix legacy accesses of `CircuitInstruction` in tests

- .github/workflows/tests.yml
- test/terra/backends/test_parameterized_qobj.py
- test/terra/backends/test_runtime_parameterization.py
Recently CI fails in MacOS-13 due to `pip check` fail. This PR takes the command.
`pip check` identifies broken dependencies but they can be detected in Linux/Win env, also.
Until `pip check` is back in Mac, CI of Mac should run without the command.
> Reduce `pip check` in CI test on Mac

- qiskit_aer/backends/aer_compiler.py
- qiskit_aer/backends/aerbackend.py
Rewrite some codes to avoid the following deprecation warning of Qiskit 1.2
> DeprecationWarning: Treating CircuitInstruction as an iterable is deprecated legacy behavior since Qiskit 1.2, and will be removed in Qiskit 2.0. Instead, use the operation, qubits and clbits named attributes.
> Rewrite `CircuitInstruction` as iterable to avoid deprecation warning of Qiskit 1.2

- qiskit_aer/primitives/sampler.py
This change is in accordance with the following warning that is triggered by the Qiskit 1.2 rc:
> qiskit_aer/primitives/sampler.py:69: DeprecationWarning: The class ``qiskit.primitives.base.base_sampler.BaseSampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. The `BaseSampler` class is a type alias for the `BaseSamplerV1` interface that has been deprecated in favor of explicitly versioned interface classes. It is recommended to migrate all implementations to use `BaseSamplerV2`. However, for implementations incompatible with `BaseSamplerV2`, `BaseSampler` can be replaced with the explicitly versioned `BaseSamplerV1` class.
> Derive from `BaseSamplerV1` rather than `BaseSampler`

- src/framework/operations.hpp
- src/simulators/matrix_product_state/svd.cpp
- src/simulators/parallel_state_executor.hpp
- src/simulators/statevector/statevector_state.hpp
- src/simulators/superoperator/superoperator.hpp
- src/simulators/tensor_network/tensor_net_state.hpp
- src/simulators/unitary/unitary_state.hpp
- src/transpile/fusion.hpp
I tried to suppress all warnings on my mac environment.
- Apple clang version 15.0.0 (clang-1500.3.9.4)
- macOS 14.6.1
> Suppress Clang++ warnings on macOS

- qiskit_aer/backends/aerbackend.py
- qiskit_aer/noise/noise_model.py
- qiskit_aer/primitives/estimator_v2.py
- qiskit_aer/primitives/sampler_v2.py
- releasenotes/notes/update-primitive-v2-metadata-bd7f5609e55ef2e7.yaml
- test/terra/primitives/test_estimator_v2.py
- test/terra/primitives/test_sampler_v2.py
Updates metadata of SamplerV2 and EstimatorV2 to be compatible with that of IBM Quantum devices.
- `version` and `circuit_metadata` are added for `SamplerV2` and `EstimatorV2`
- `shots` is added for `SamplerV2`
port of https://github.com/Qiskit/qiskit/pull/12784
> Update metadata of Primitives V2

- qiskit_aer/backends/backendconfiguration.py
- test/terra/backends/test_assemble.py
> Add `open_pulse` entry to `AerBackendConfiguration`

- .github/workflows/docs.yml
- .github/workflows/tests.yml
- qiskit_aer/noise/passes/local_noise_pass.py
- releasenotes/notes/fix_tests_0.15-dccf0acb3cf10571.yaml
- requirements-dev.txt
Fixing tutorial build and tests for Qiskit 1.0.0rc1
tutorial build running on Python 3.8 upgrades to 3.9
remove unused tutorial builds
Qiskit 1.0.0rc1 should be upgraded to 1.3.0b1
Fix noise/passes/local_noise_pass.py, added conversion from tuple to list
> Fix tests Aer 0.15 in the latest environments

- releasenotes/notes/fix_mps_size_estimator-0dcf387fd870f5e5.yaml
- src/simulators/matrix_product_state/matrix_product_state_size_estimator.hpp
This is fix for SIGSEGV on MPS simulator #2220 
In size estimator of MPS, SIGSEGV raised at `std::set.find()` if unsupported gates are passed to MPS simulator.
This fix checks return of `std::set.find()` to avoid SIGSEGV
> Fix MPS size estimator

- .github/workflows/deploy.yml
This is fix for deploy for aarch64 and ppc64le
EPEL 7 had been EOL, so we have to get packages from archive
> Change EPEL url for aarch64, ppc64le

- qiskit_aer/backends/aer_compiler.py
- releasenotes/notes/fix_infinite_run_on_empty_conditional-d9e6d31ffa1c3bc3.yaml
- test/terra/backends/aer_simulator/test_conditional.py
This PR fixes a bug where using a conditional with an empty body causes an infinite loop when running the simulator.
Fixes #2230 
When using a conditional with an empty body, e.g. 
```
with main_circ.if_test((creg_0[0],0)) as else_1:
pass
with else_1:
pass
```
The simulator gets stuck in an infinite loop.
It seems the underlying cause of the problem is that when a conditional command has an empty body, it has empty `qargs` list as well. This means that the `jump` and `mark` commands generated by `Aer` will have empty `qubits` list and hence after a transpiler pass they may be relocated nondeterministically to any part of the circuit (they are usually placed between two barriers, but without qubits the DAG-to-circuit algorithm will not consider the barriers part of their topological …
> Fixes a bug causing infinite run when using conditional with empty body

- releasenotes/notes/fix_mps_save_without_memory_limit-64d927c4b4e1e2d4.yaml
- src/simulators/circuit_executor.hpp
- test/terra/backends/aer_simulator/test_save_matrix_product_state.py
Fixes a bug preventing MPS runs when the estimated memory usage is too big, even if memory limit is disabled.
Fixes #2246 
When `max_memory_mb=-1` the maximum memory amount check for MPS should be disabled; however, `Executor<state_t>::get_max_parallel_shots` still uses the estimated memory in its computation, which might result in the value `0`, disabling the run of the engine altogether. To prevent this, `get_max_parallel_shots` results to the `mem==0` case if the maximum memory amount check is disabled.
> Fixed MPS save failure when memory limit is ignored

- qiskit_aer/backends/aer_compiler.py
- releasenotes/notes/fix_controlled_gate_compile-c94fb7c41fa961db.yaml
- test/terra/backends/aer_simulator/test_circuit.py
Fixes a bug in the compilation of controlled gates resulting in X gates added in incorrect positions.
Fixes https://github.com/Qiskit/qiskit-aer/issues/2252
When adding a gate with control qubits, a control state string determines whether the control qubit should be 1 or 0. In the case of `0`, compilation adds an X gate before and after the application of a standard, controlled-by-1 gate. The code for adding the X gates is
```
for i in range(len(qubits)):
if (ctrl_state >> i) & 1 == 0:
qubits_i = [qubits[len(qubits) - 1 - i]]
aer_circ.gate("x", qubits_i, params, [], conditional_reg, aer_cond_expr, label if label else "x")
```
The code goes over the qubit list in reverse order, which does not correspond to the way the control string is interpreted in `Qiskit`, and the loop goes over all …
> Fix for a bug in the compilation of controlled gates

- .github/workflows/deploy.yml
- .github/workflows/docs.yml
- .github/workflows/neko.yml
This PR fixes an error in the github action for `deploy` preventing wheels from being uploaded.
When using `actions/upload-artifact@v4` a unique name should be given for separate jobs, otherwise the name clash results in `Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run`.
This PR adds a unique name to the action.
> Adds unique name for upload-artifact jobs

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/tests.yml
- pyproject.toml
- releasenotes/notes/add_support_for_python_313-a92b1656dcc23576.yaml
- requirements-dev.txt
This PR adds Python 3.13 support for building wheels and removes Python 3.8 which was dropped by qiskit version 1.3.
The version of cibuildwheel was updated to the latest 2.22 to ensure support for Python 3.13.
> Add Python3.13 support and remove Python 3.8 support

- src/simulators/statevector/qubitvector.hpp
- src/simulators/statevector/qubitvector_thrust.hpp
Fixes a bug where `QubitVector::check_dimension` attempted to access non-existing fields.
Fixes #2284 
Originally, `QubitVector::check_dimension` was defined as
```cpp
template <class data_t>
void QubitVector<data_t>::check_dimension(const QubitVector &qv) const {
if (size_ != qv.size_) {
std::stringstream ss;
ss << "QubitVector: vectors are different shape ";
ss << size_ << " != " << qv.size_;
throw std::runtime_error(ss.str());
}
}
```
In 502ffcd01d9c515d47f72da7d4cefd95ce4bba4c this was changed to
```cpp
template <typename data_t>
void QubitVector<data_t>::check_dimension(const QubitVector &qv) const {
if (data_size_ != qv.size_) {
std::string error = "QubitVector: vectors are different shape " +
std::to_string(data_size_) + " != " +
std::to_string(qv.num_states_);
throw …
```
> Fix QubitVector::check_dimension to use only the data_size_ field

- qiskit_aer/library/control_flow_instructions/jump.py
- qiskit_aer/noise/errors/quantum_error.py
In Qiskit 2.0 the Instruction.condition attribute will be removed following it's deprecation in 1.3.0. This attribute has been superseded by the IfElseOp which covers the use case but offers more functionality. The removal is pending in Qiskit/qiskit#13506 and the use of qiskit-aer in Qiskit's tests is blocking progress on that PR. This commit makes the usage of .condition optional to maintain compatibility with Qiskit<2.0 but also work in >=2.0 with the attribute removed.
> Adjust QuantumError.to_dict() to handle lack of Instruction.condition

- docs/conf.py
- docs/getting_started.rst
- qiskit_aer/primitives/__init__.py
- releasenotes/notes/0.14/support_backend_v2-9eeb4690199b01d1.yaml
The documentation source of truth is moving to https://quantum.cloud.ibm.com/.
> Update intersphinx mapping and others URLs pointing to IQP Classic

- releasenotes/notes/fix_parameter_bind-bf49a0bfb3c3a4de.yaml
- src/controllers/controller_execute.hpp
This is fix for issue #2367
The ops between measures are remapped when `Circuit::set_params` is called.
So This fix binds parameters before calling `Circuit::set_params`
> Bind parameters before truncation
