Qiskit/qiskit-aer

README.md

Updating the readme with stackoverflow and removing some white spaces

---

src/base/controller.hpp

Fix a typo in the comment

---

CHANGELOG.rst

Updating CHANGELOG for the new patch release: 0.1.1

CHANGELOG updated

---

README.md

add Qiskit citation info to README

---

src/framework/creg.hpp
src/framework/operations.hpp

Fixing bugs in `apply_bfunc` for applying the new type of conditionals from the qobj spec.

fix apply_bfunc

---

src/base/controller.hpp
src/simulators/qasm/qasm_controller.hpp
src/simulators/qubitunitary/unitary_controller.hpp
src/simulators/qubitvector/statevector_controller.hpp
test/terra/test_qasm_simulator.py
test/terra/utils/qasm_simulator/qasm_thread_management.py
test/terra/utils/ref_qvolume.py

Simplify logic to determine parallelism.

Refactor thread management

---

src/simulators/stabilizer/clifford.hpp

Fixes #62 
Move `unsigned` to `signed` variables in all the loops we want to parallelize with OpenMP pragmas.

Issue 62 - Fix OpenMP compilation on Windows

---

.travis.yml
qiskit/providers/aer/backends/wrappers/CMakeLists.txt

- Change destination directory to be site/dist-packages agnostic
- Fix travis tests by installing Terra before passing all the tests
Fixes #66
We have changed the CMakeLists.txt in order to install in the project directory, independently of the inner directory nomenclature (Debian has it's own `dist-packages` instead of `site-packages`).
We have included a fix for the tests to pass again, related to a recently Terra change.

Issue 66 fix wheel for debian

---

qiskit/providers/aer/noise/noise_model.py

This fixes failing travis tests due to recent changes to Terra compilers default basis gates set.
Rather than have U,CX as implicit basis gates we now have `u3,cx` as the default basis gates and `u1` and `u2` gates will unroll to `u3` if not in the basis gates set.

Update noise basis_gates to alwayas have cx, u3

---

qiskit/providers/aer/noise/device/models.py

p_depol = (dim) * gate_error / (dim-1) should not be instead
p_depol = (dim-1) * gate_error / dim ? 
I changed it but the other formulas should be also corrected

Comment derivation depolarising probability from gate error

---

src/simulators/qasm/qasm_controller.hpp

Fix typos in comments

---

src/misc/hacks.hpp

Fix Windows build

---

qiskit/providers/aer/backends/aerbackend.py
qiskit/providers/aer/noise/errors/errorutils.py
qiskit/providers/aer/noise/errors/quantum_error.py
qiskit/providers/aer/noise/errors/readout_error.py
qiskit/providers/aer/noise/errors/standard_errors.py
qiskit/providers/aer/noise/noise_model.py
test/terra/test_quantum_error.py
test/terra/test_readout_error.py
test/terra/test_statevector_simulator.py
test/terra/test_unitary_simulator.py
test/terra/utils/qasm_simulator/qasm_algorithms.py
test/terra/utils/qasm_simulator/qasm_cliffords.py
test/terra/utils/qasm_simulator/qasm_noncliffords.py

* Updates `QuantumError` class to interface with the new `QuantumChannel` classes in qiskit-terra `qiskit.quantum_info.operators.channel` package.
* Updates `QuantumError` and `ReadoutError` to have similar methods to `QuantumChannel` (compose, tensor, extend behave the same way as in QuantumChannel, kron is depreciated).
* Updates noise model basis gates to return list instead of string for new compiler/transpiler.

QuantumChannel integration with noise

---

qiskit/providers/aer/noise/errors/quantum_error.py
qiskit/providers/aer/noise/errors/standard_errors.py

Fixes change in quantum channel file name from terra PR 2078 that is causing tests to fail

fix quantum channel import path

---

src/noise/noise_model.hpp
src/simulators/qasm/qasm_controller.hpp
test/terra/test_qasm_simulator.py
test/terra/test_statevector_simulator.py
test/terra/utils/qasm_simulator/qasm_initialize.py
test/terra/utils/qasm_simulator/qasm_measure.py
test/terra/utils/qasm_simulator/qasm_reset.py
test/terra/utils/ref_initialize.py
test/terra/utils/ref_reset.py

This is a continuation of #117

Initialize gate

---

qiskit/providers/aer/backends/wrappers/CMakeLists.txt

Attempting to fix failing build while Juan is sleeping. Something is wrong with setting link flags on Travis from the MacOS fix recently merged.

Fix cmake build failing for travis/linux

---

.github/CONTRIBUTING.md

One of the links in the Contributing guidelines wasn't working due to a typo.

Fixed a typo in the Contributing guidelines

---

qiskit/providers/aer/noise/errors/errorutils.py
test/terra/backends/qasm_simulator/qasm_basics.py
test/terra/backends/test_statevector_simulator.py
test/terra/utils/mock.py

* Use `assemble` instead of `assemble_circuits`
* QuantumChannel uses `qargs` instead of `qubits` for compose

update failing tests for changes in terra api

---

qiskit/providers/aer/backends/qasm_simulator.py
qiskit/providers/aer/backends/statevector_simulator.py
qiskit/providers/aer/backends/unitary_simulator.py
src/framework/operations.hpp
src/framework/utils.hpp
src/simulators/statevector/qubitvector.hpp
src/simulators/statevector/statevector_state.hpp
test/terra/backends/qasm_simulator/qasm_cliffords.py
test/terra/backends/qasm_simulator/qasm_noncliffords.py
test/terra/reference/ref_2q_clifford.py
test/terra/reference/ref_non_clifford.py
test/terra/utils/multiplexer.py

This includes all of the changes to enable multiplexer.  Had to be done in a new pull/push because of clutter in Git.
This was passing all of the tests last night (assuming I caught all of the deltas, which I believe I did).

Multiplexer work re-instantiated to fix creeping gitrot

---

test/benchmark/simple_benchmarks.py

Fix import error in simple_benchmarks

---

.travis.yml

This will enable our testing framework to run in all our supported platforms/environments (except Windows) through CI (Travis) running via cron.
Every commit and PR will run Linux/MacOS tests for Python 3.7.
Also, we will enable Travis cron jobs to run the tests in all supported platforms (except Windows, that will run through Appveyor CI).

Enable testing in all of our supported environments via CIs (Travis)

---

.github/CONTRIBUTING.md

This commit documents are policy for the stable branch, how it's used
what we need to evaluate when looking at potential changes, and the
priorities for the stable branch.
This is a straight copy and paste from
Qiskit/qiskit-terra#2358

Add stable branch policy to CONTRIBUTING.rst

---

src/simulators/statevector/qubitvector.hpp
src/transpile/fusion.hpp
test/benchmark/tools.py
test/terra/backends/qasm_simulator/qasm_fusion.py

The current fusion has a critical bug in matrix generation
`QubitVector<data_t>::expand_matrix` is wrong to merge 2-qubit operations.

fix a critical bug in fusion and add tests

---

qiskit/providers/aer/noise/utils/noise_transformation.py
test/terra/noise/test_noise_transformation.py

Noise transformation qubit extension

---

README.md

Updated the links for Code of Conduct and Contribution Guidelines
Issue #246

Fixed README.md broken links 

---

README.md

Fixing one more broken link I missed on the first round!
Issue #246

Fixing Contributing Guidelines broken link 

---

src/simulators/qasm/qasm_controller.hpp
test/terra/backends/qasm_simulator/qasm_measure.py
test/terra/reference/ref_measure.py

This PR fix issue #268.
Sampling should not work if a measure is conditional.

fix sampling bug in qasm simulator

---

CHANGELOG.md
src/simulators/qasm/qasm_controller.hpp
test/terra/backends/qasm_simulator/qasm_reset.py
test/terra/reference/ref_reset.py

Fixes bug introduced in #270 where checking for conditionals should have used `OR` not `AND`.
Close #279

Fix bug in measure sampling

---

test/terra/utils/mock.py

Passing `coupling_map` as a backend configuration, as Terra requires.

* Terra now requires to pass a coupling_map

---

src/simulators/qasm/qasm_controller.hpp
test/terra/backends/qasm_simulator/qasm_measure.py
test/terra/backends/test_qasm_density_matrix_simulator.py
test/terra/backends/test_qasm_extended_stabilizer_simulator.py
test/terra/backends/test_qasm_simulator.py
test/terra/backends/test_qasm_stabilizer_simulator.py
test/terra/backends/test_qasm_statevector_simulator.py
test/terra/backends/test_statevector_simulator.py
test/terra/reference/ref_measure.py

* Adds result metadata `"measure_sampling": True/False` to indicate whether measure sampling optimization was used during simulation.
* Updates measure tests to check if sampling opt was applied or not applied correctly
* Updates the multi-qubit measure tests to use proper qiskit circuit `Instruction` objects rather than hacking qobj.

Update multi-qubit measure tests

---

qiskit/providers/aer/backends/qasm_simulator.py

Added tensor_network to the doc string of QasmSimulator

---

CHANGELOG.md

This PR adds two items to CHANGELOG for 0.3 release.
#222, #286, and #315

added change logs for supports of single-precision and readout-error sampling

---

qiskit/providers/aer/extensions/snapshot_expectation_value.py

Linter fixing

---

contrib/standalone/qasm_simulator.cpp
src/framework/circuit.hpp

Fix spelling typos.

---

src/base/controller.hpp
src/simulators/qasm/qasm_controller.hpp
src/simulators/stabilizer/clifford.hpp

Fix some grammatical and spelling errors.

---

test/terra/backends/test_qasm_density_matrix_simulator.py
test/terra/backends/test_qasm_extended_stabilizer_simulator.py
test/terra/backends/test_qasm_matrix_product_state.py
test/terra/backends/test_qasm_simulator.py
test/terra/backends/test_qasm_stabilizer_simulator.py
test/terra/backends/test_qasm_statevector_simulator.py

Adds fixed value for `seed_simulator` for qasm simulator tests.

Add fixed simulator seed for qasm simulator tests

---

setup.py

missing import of `sys` in exception block added
necessary if `scikit-build` not installed

add sys to imports in exception block

---

qiskit/providers/aer/openpulse/solver/opsolve.py

Fixed ordering for meas level 2 with the open pulse sim

---

qiskit/providers/aer/noise/utils/noise_transformation.py
qiskit/providers/aer/openpulse/qobj/opparse.py
qiskit/providers/aer/openpulse/solver/monte_carlo.py

Fixing linter for OP

---

qiskit/providers/aer/openpulse/cy/channel_value.pyx

fix indexing error in FC

---

qiskit/providers/aer/backends/qasm_simulator.py
qiskit/providers/aer/backends/statevector_simulator.py
qiskit/providers/aer/backends/unitary_simulator.py
qiskit/providers/aer/noise/utils/noise_transformation.py

Fixed the following errors:
- 3 `no-name-in-module` errors from importing cpython functions
- fixed by disabling this error for the relevant import only
- 1 `bad-option-value` coming from an invalid `pylint` option
- just removed this line from `noise_transformation.py`, and there were no further errors

fixed pylint errors

---

src/transpile/fusion.hpp
test/asv.linux.conf.json
test/benchmark/fusion_benchmarks.py

* Quantum Fourier Transformation
* Randomly generated benchmarks
To improve the coverage o the ASV benchmarks, we added two benchmarks as described above
N/A

Added Benchmarks for Fusion Optimization

---

qiskit/providers/aer/openpulse/qobj/digest.py

Added warning messages to alert users that they have specified pulse simulations with untested features, as per issue #462. 
Warnings are issued in `digest_pulse_obj` for:
- PersistentValue pulses
- Oscillator-type systems
- Noise models
These warnings do not halt execution; they just let the user know that the outcomes are not necessarily reliable.

Added warning messages for Pulse Simulator untested features

---

cmake/FindPybind11.cmake

Small bug in build scripts for Pybind interface - causing `pip install .` to fail in some environments where it should not be failing.

[WIP] Fixed bug in FindPybind.cmake affecting certain environments

---

src/simulators/stabilizer/clifford.hpp
src/simulators/stabilizer/stabilizer_state.hpp

Replaced the stabilizer Pauli expectation value code with code that works directly on the tableau, instead of using the probability snapshot. The new code has polynomial run time, without imposing further constraints.

Rewrote stabilizer Pauli expectation value

---

CMakeLists.txt

Add the install option for the standalone tool.
Add the install option, so that the standalone executable will be installed in the standard locations according to SO (e.g /usr/local/lib/ in MacOS ). This is related to issue #233.

Install added to standalone build

---

cmake/compiler_utils.cmake

Fix submodule update behaviour
- Fixed submodule directory emptiness check. 
- Now submodules are updated individually instead of the whole bunch.

Fix is_dir_empty check. Get git submodules individually

---

tools/verify_wheels.py

Closes #584
Added a small test for the pulse simulator in `tools/verify_wheels.py`
The test makes a single qubit model, constructs a schedule for doing a pi pulse, and verifies that the output state vector is correctly in the |1> state.
Backported from #588
(cherry picked from commit b0e254cab46fa838176a56a9c5671cd4e87222f4)

[Stable] Added test in verify_wheels.py for pulse simulator (#588)

---

docs/apidocs/qiskit_aer.rst

This PR fixes the heading of the landing page of API docs.

Update the heading of the landing API docs page

---

qiskit/providers/aer/backends/qasm_simulator.py
src/controllers/qasm_controller.hpp

Add recent changes of GPU into qasmsimulator's docstring
Added gpu's `method`s into the header.

add comment of gpu options

---

CONTRIBUTING.md
requirements-dev.txt

Improving CONTRIBUTING guide

---

qiskit/providers/aer/pulse/qutip_lite/cy/sparse_routines.pxi
qiskit/providers/aer/pulse/qutip_lite/cy/sparse_utils.pyx
qiskit/providers/aer/pulse/qutip_lite/cy/spmath.pyx
qiskit/providers/aer/pulse/solver/codegen.py
src/open_pulse/numeric_integrator.cpp

Fixing compilation issue on Power systems with RedHat of PyDataMem_NEW_ZEROED.
I replaced PyDataMem_NEW_ZEROED to PyDataMem_NEW with hand written zero clear loop 
to compile on Power environment that does not support PyDataMem_NEW_ZEROED

#578 replace PyDataMem_NEW_ZEROED to PyDataMem_NEW

---

.travis.yml
azure-pipelines.yml

The travis config on master will eventually become the stable branch of
the future. To simplify our config between stable/* and master this
updates the config on master to run tests using terra from master and
for other branches it uses the latest terra release. This mirrors the
config changes made on stable/0.4 in #633 so that for the next stable
branch we'll not have to manually update the config.

Copy config for using terra release on stable branch CI

---

qiskit/providers/aer/backends/aerbackend.py
test/asv.linux.conf.json
test/asv.macos.conf.json

There have been a lot of improvements in the build system, so I'm updating the benchmark frameworks for detecting performance regressions. 
I'm removing static compilation, not forcing the platform name for MacOS, and using `-j` so the `Make` subsystem choose the better parallel strategy depending on the underlying architecture.

Update Benchmark framework

---

CONTRIBUTING.md
README.md

* Add instructions for all the officially supported Linux distributions
* Add git installation instructions
Adding GPU installation instructions to README and updated the contributing guide with installation instructions for Red Hat, Fedora and CentOS distributions.
Fixes #597 and #625

* Add GPU installation instructions

---

test/terra/backends/test_pulse_simulator.py
tools/verify_wheels.py

Closes #675 
Updates `pulse.Schedule` construction in `test_pulse_simulator.py` and `verify_wheels.py` to the new style in `terra`.

Update pulse simulator tests to reflect updates in terra

---

src/framework/circuit.hpp
src/framework/qobj.hpp
src/noise/noise_model.hpp

* Remove unused methods
* Add sets for qubits and clbits used in circuit
Code cleanup of circuit class
* Removes unused methods.
* Adds sets to circuit for qubits and clbits that are used in circuit ops.
* Fixes noise model to correctly update circuit opset after sampling noise.

Refactor circuit

---

src/framework/stl_ostream.hpp
src/framework/types.hpp

Code cleanup.
Refactor of `types.hpp` to move the stl printing to its own file
I'm breaking up things in #671 into smaller separate PRs because I was getting some runtime errors with that PR.

Move stl ostream to seperate_file

---

src/simulators/stabilizer/stabilizer_state.hpp

adding cy to stabilizer

---

releasenotes/notes/rng-engine-8235ed6278c23765.yaml
src/framework/rng.hpp

Code cleanup
Refactor of `rng.hpp` so that it uses int/float templates for its functions to work with different precision/width numbers.
Note: I'm breaking up things in #671 into smaller separate PRs because I was getting some runtime errors with that PR.

Add templates to RngEngine class

---

releasenotes/notes/fix-reduce-barrier-7b1dfeb4a9389516.yaml
releasenotes/notes/stabilizer-cy-200773f25da609d3.yaml

Add missing release notes for #701 and #693

Add missing release notes

---

test/terra/backends/qasm_simulator/qasm_unitary_gate.py
test/terra/reference/ref_unitary_gate.py

Fix broken tests from changes to Terra Numpy RNG generator.
Update unitary tests to test 1-4 qubit unitaries

Fix broken unitary tests

---

qiskit/providers/aer/utils/noise_model_inserter.py
test/terra/noise/test_noise_inserter.py

Modify `insert_noise` to also include local errors and nonlocal quantum errors.
Currently `qiskit.providers.aer.utils.insert_noise` only takes into account `noise_model._default_quantum_errors`, as discussed in issue #711. This PR makes it also consider `noise_model._local_quantum_errors` and `noise_model._nonlocal_quantum_errors`.
Closes #711

Implemented local and nonlocal errors for noise inserter

---

qiskit/providers/aer/pulse/qutip_extra_lite/dimensions.py
qiskit/providers/aer/pulse/qutip_extra_lite/qobj.py
qiskit/providers/aer/utils/noise_transformation.py

Fix some codestyle errors that have appeared due to new pycodesyle version 2.6, which make CI fails.

Fix code style errors due to new pycodestyle version 2.6

---

test/terra/decorators.py

Fixes the decorator for skipping tests for unavailable methods.
Now it actually checks if the returned error message states the simulator method is unavailable before skipping the test, and will return the test as a failure if the method should be available but the test was unsuccessful. Previously any failure was causing the test to be skipped as unavailable even if the test should have been passing.

Update decorator for not-installed simulation methods

---

src/simulators/density_matrix/densitymatrix_thrust.hpp

Fixes a bug introduced in #760

Fix bug in DensityMatrixThrust apply_y

---

CONTRIBUTING.md

Add GPU build instructions to CONTRIBUTING guide

---

README.md

Added valid Slack link.
Valid Slack link (https://qiskit.slack.com/join/shared_invite/zt-fybmq791-hYRopcSH6YetxycNPXgv~A#/) has been added in README.md.

Valid Slack invite link

---

.pylintrc
.travis.yml
BENCHMARKING.md
CMakeLists.txt
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE.txt

Speling and grammer mistakes are improved
Spelling and grammer mistakes are improved

Spelling_and_grammer_mistakes

---

.travis.yml
azure-pipelines.yml

This PR serves 2 purposes the first is to verify if our build publish jobs still work with the recent changes in packaging. The second is to bump the cibuildwheel version we're using to the latest to keep up to date.

Update cibuildwheel version

---

CONTRIBUTING.md

Update contribution guide
* (Re)adding instructions for openblas, given that we cameback to the old approach in #862 
* Removing libomp installation instructions on macos as there is no need to install it manually (conan takes care of it)

Update contribution guide: openblas and libomp

---

src/misc/common_macros.hpp

Add missing license to common_macros.hpp

Add missing license

---

releasenotes/notes/0.6/0.6.0-release-1560059e0b322560.yaml

Adds missing release note on adding Conan to build system.

Add conan to release notes

---

qiskit/providers/aer/extensions/snapshot_expectation_value.py
src/controllers/controller.hpp
src/controllers/qasm_controller.hpp
src/framework/circuit.hpp
src/framework/operations.hpp
src/simulators/statevector/statevector_state.hpp
src/transpile/truncate_qubits.hpp
test/terra/backends/qasm_simulator/qasm_measure.py
test/terra/backends/qasm_simulator/qasm_snapshot.py
test/terra/backends/test_qasm_simulator.py
test/terra/backends/test_qasm_simulator_density_matrix.py
test/terra/backends/test_qasm_simulator_matrix_product_state.py
test/terra/backends/test_qasm_simulator_statevector.py

typos fixes

---

src/simulators/matrix_product_state/matrix_product_state_internal.cpp
src/simulators/matrix_product_state/matrix_product_state_tensor.hpp
src/simulators/matrix_product_state/svd.cpp

Removed three unnecessary lines and fixed some spacing.

Small cosmetic changes to MPS

---

setup.py

Most other qiskit elements are updating their email from qiskit@qiskit.org to hello@qiskit.org, since the former is invalid. While qiskit@us.ibm.com is valid, it's nice to have a single email address for all elements.

Update email in setup.py

---

releasenotes/notes/add-openblas-lapack-67ad654d1148a309.yaml

Add openblas+lapack release note

Add openblas+lapack release note

---

CMakeLists.txt

Fix build error when setting AER_THRUST_BACKEND trough an environment variable

Fix THRUST build error

---

.github/CODEOWNERS

Adding Victor to code owners

---

src/framework/opset.hpp

Fix opset difference

---

qiskit/providers/aer/backends/qasm_simulator.py
releasenotes/notes/fix-basis-gates-3b5c64c3bbfee1c7.yaml
src/simulators/matrix_product_state/matrix_product_state.hpp
src/simulators/matrix_product_state/matrix_product_state_internal.cpp
src/simulators/matrix_product_state/matrix_product_state_tensor.hpp
test/terra/backends/qasm_simulator/qasm_standard_gates.py

As explained in #1021, because of a bug in the tests, some tests were not running until now. This PR fixes the bug. Then, some of the now running tests fail. This PR fixes the bugs that cause this failure.
The fixes:
- A fix in the test, as described in #1021.
- Added `sx` to the list of gates for MPS, solving a test that fails while complaining that `sx` is invalid for MPS.
- Fixed places where function parameters were not passed correctly.

Fixed the tests and the revealed bugs

---

test/terra/backends/qasm_simulator/qasm_fusion.py

Fix tests due to bad input to assemble function

Fix tests due to bad input to assemble function

---

src/simulators/matrix_product_state/matrix_product_state_internal.cpp
src/simulators/matrix_product_state/matrix_product_state_internal.hpp

Especially removing unused variables

Small cleaning in the MPS simulator

---

azure-pipelines.yml

Updating wheel with pip fails in azure sdist_builds. Installing it with Conda works.

Fix CI problem when updating wheels

---

test/terra/pulse/test_system_models.py

Remove unused imports making tests fail

---

CMakeLists.txt

DISABLE_CONAN env variable didn't have any effect in build process. This PR solves that.
Fixes #1079

Honor DISABLE_CONAN environment variable

---

src/controllers/qasm_controller.hpp
src/controllers/statevector_controller.hpp
src/controllers/unitary_controller.hpp
src/transpile/circuitopt.hpp
src/transpile/fusion.hpp
test/terra/backends/qasm_simulator/qasm_fusion.py

Add parallelization option to transpilation and parallelize fusion
If number of operations is more than `transpile_parallelization_threshold`, transpilation is parallelized if it supports parallelization. This is a PR to add features of #986.

parallelize fusion transpilation

---

qiskit/providers/aer/backends/qasm_simulator.py
qiskit/providers/aer/backends/statevector_simulator.py
qiskit/providers/aer/library/__init__.py
qiskit/providers/aer/library/save_probabilities.py
releasenotes/notes/save-data-instructions-24b127612c9f6502.yaml
src/framework/operations.hpp
src/framework/results/data/data.hpp
src/framework/results/data/mixins/data_rdict.hpp
src/framework/results/data/mixins/pybind_data_rdict.hpp
src/framework/results/data/pybind_data.hpp
src/simulators/density_matrix/densitymatrix_state.hpp
src/simulators/matrix_product_state/matrix_product_state.hpp
src/simulators/stabilizer/stabilizer_state.hpp
src/simulators/statevector/statevector_state.hpp
test/terra/backends/qasm_simulator/qasm_save.py
test/terra/backends/qasm_simulator/qasm_save_probabilities.py

Adds `SaveProbabilities` and `SaveProbabilitiesDict` instructions.
~Depends on #1101~
TODO: Handle extended stabilizer method in a separate PR

Add `SaveProbabilities` and `SaveProbabilitiesDict` instructions

---

test/terra/backends/qasm_simulator/qasm_save_expval.py

Add missing tests for SaveExpectationValueVariance instruction
Closes #464

Add tests for SaveExpectationValueVariance

---

qiskit/providers/aer/extensions/snapshot.py

Backport of the Snapshot part of #1139. This will let stable Aer work properly with master terra once PR https://github.com/Qiskit/qiskit-terra/pull/5701 is merged.

Add `_directive=True` attr to Snapshot instruction

---

releasenotes/notes/fix-conditional-noise-178f5d03b97a8dd5.yaml
src/noise/noise_model.hpp
test/terra/reference/ref_pauli_noise.py

Fixes #1153 
Noise model sampling wasn't checking if the noisy gate was conditional or not. Now the noisy instruction is conditional, the sampled noise instructions will also be conditional so they are only applied when the conditional gate is applied.

Fix noise sampling for conditional gates

---

src/framework/json.hpp

Pass some json utils function args by const reference

---

qiskit/providers/aer/extensions/__init__.py
qiskit/providers/aer/extensions/snapshot_density_matrix.py
qiskit/providers/aer/extensions/snapshot_expectation_value.py
qiskit/providers/aer/extensions/snapshot_probabilities.py
qiskit/providers/aer/extensions/snapshot_stabilizer.py
qiskit/providers/aer/extensions/snapshot_statevector.py
qiskit/providers/aer/noise/device/models.py
qiskit/providers/aer/noise/errors/readout_error.py

Add pending deprecation warnings to snapshot instructions and API docs
Fixes #996

Add pending deprecation warnings to snapshots

---

qiskit/providers/aer/noise/noise_model.py
qiskit/providers/aer/utils/noise_transformation.py
releasenotes/notes/remove-deprecated-ba6eb1060207af99.yaml
src/framework/creg.hpp
src/framework/operations.hpp
src/noise/noise_model.hpp
src/simulators/extended_stabilizer/extended_stabilizer_state.hpp

Remove deprecated old-style conditional support
Remove deprecated old-style x90 noise model decomposition

Remove previously deprecated methods

---

test/terra/backends/qasm_simulator/qasm_save_expval.py

The save expectation value tests are currently failing due to recent update in Terra in https://github.com/Qiskit/qiskit-terra/pull/5941. This aims to unblocks CI until a fix can be merged in https://github.com/Qiskit/qiskit-terra/pull/5984

Fix failing CI tests

---

pyproject.toml
requirements-dev.txt
setup.py

Adds minimum version requirement to scikit-build
Closes #1180

Add min version for scikit-build

---

qiskit/providers/aer/backends/aerbackend.py
releasenotes/notes/config-local-46d47ae08eeab339.yaml
test/terra/backends/test_config_pulse_simulator.py

Always set config.local to True

---

src/framework/results/data/data.hpp
src/framework/results/data/metadata.hpp

Fix JSON serialized of empty Data and Metadata

---

src/framework/pybind_json.hpp

This PR adds general iterable python type objects to the `to_json` conversion function. It kicks in when no other more specific conversion matches.

Add python iterables to to_json conversion method

---

releasenotes/notes/bug-fix-mps-kraus-764cc96854585030.yaml
releasenotes/notes/fix-initialize-sampling-b6948e39112f6a46.yaml
releasenotes/notes/fix-normalize-statevector-extended-stabilizer-3811f44e003099f3.yaml
releasenotes/notes/set-mps-b0efa4a250c1e8ef.yaml

This commit prepares the 0.8.1 release notes for release.

Prepare 0.8.1 release

---

qiskit/providers/aer/extensions/snapshot_statevector.py

Commit message is explanatory.

Fix snapshot_statevector deprecation warning message

---

src/simulators/matrix_product_state/matrix_product_state.hpp

This PR makes sampling of MPS parallelized.
Original MPS does not use parallelization to sample counts.
This PR add OMP parallelization to MPS based on a number of shots.

Parallelize sampling in mps

---

.github/workflows/tests_windows.yml
test/terra/backends/qasm_simulator/qasm_noise.py
test/terra/backends/qasm_simulator/qasm_save_amplitudes.py
test/terra/noise/test_noise_model.py

Fix test fails from recent Terra's updates
This PR will fix some test errors due to recent updates of Terra.

fix test errors due to recent terra updates

---

qiskit/providers/aer/noise/errors/standard_errors.py

Pauli was changed to symplectic form.
https://github.com/Qiskit/qiskit-terra/pull/5261
In this PR, I change import path.

Remove deprecated Pauli

---

src/simulators/statevector/qv_avx2.cpp

User `#pragma omp threadprivate` for local storage of omp threads
Thread-local storage for SIMD kernel is necessary for diagonal.
Originally, `omp_get_thread_num()` is used to identify thread id and memory is identified.
#1291 resolved an issue when nested OMP is used. However, recently, this issue is happening away.
This PR uses `#pragma omp threadprivate` to generate thread-local storage. Because a constraint of this pragma, variables `tmp_float` and `tmp_double` are defined as global.

use omp threadprivate in qv simd kernel

---

qiskit/providers/aer/noise/errors/quantum_error.py

Fix issue 1258

---

qiskit/providers/aer/backends/compatibility.py
test/terra/backends/test_compatibility.py

This is not entirely complete for all possible magic methods, but covers
the use cases in downstream projects that we know about.
Fix #1399.

Add Python iterable magic methods to compatibility classes

---

src/simulators/state_chunk.hpp
src/simulators/statevector/qubitvector_thrust.hpp

This is the fix for multi-shots optimization for GPU simulator.
Previous implementation does not support noise with Pauli gate operation, can be tested by `test.terra.backends.aer_simulator.test_noise.TestNoise.test_pauli_gate_noise` 
This fix implements handling Pauli noise with Pauli gate that contains multiple qubits and Pauli string.

Fix multi-shots Pauli noise with Pauli gate operation

---

qiskit/providers/aer/noise/noise_model.py

If a backend properties didn't have T1, T2, or frequency values this function would raise an exception. This adds a try block to just skip adding the delay noise pass in these cases, which is the same behavior of the rest of the noise model from previous version of aer.

Add try block for backend noise model delay pass

---

README.md

This updates the README to reflect that `pip install qiskit` no longer installs all elements.
This is a parallel change to https://github.com/Qiskit/qiskit-terra/pull/7476.

Update README.md: `pip install qiskit` no longer installs all elements

---

qiskit/providers/aer/noise/__init__.py

remove the duplicated `pauli error`.

Remove duplicate documentation entry

---

qiskit/providers/aer/noise/device/parameters.py

Fixes #1487 by correcting documentation on `qiskit.providers.aer.noise.device.thermal_relaxation_values`

Fix 1487 by correcting documentation

---

releasenotes/notes/cuQuantum_22.05.0.41_support-cb0e797b57d20c3a.yaml
src/controllers/aer_controller.hpp
src/simulators/state_chunk.hpp
src/simulators/statevector/chunk/cuStateVec_chunk_container.hpp
src/simulators/statevector/statevector_state.hpp

This PR is update for the latest cuQuantum release.
Thread safety issues in some cuStateVec APIs are fixed in the latest release.
So OpenMP parallel threads on the host is now turned on when enabling cuStateVec for multi-shots and multi-chunk parallelization.

Support for cuQuantum 22.5.0.41

---

qiskit/providers/aer/pulse/__init__.py

https://peps.python.org/pep-0632/

Remove distutils import per PEP 632

---

cmake/conan_utils.cmake

fix #1558 if possible
Update spdlog

Updates spdlog from 1.5.0 to 1.9.2

---

qiskit/providers/aer/primitives/estimator.py

If the parameters are empty lists, we don't need bind_circuits in assemble.
Related to https://github.com/Qiskit/qiskit-terra/pull/8407.

Improve the performance (Primitives)

---

qiskit/providers/aer/primitives/estimator.py
qiskit/providers/aer/primitives/sampler.py

Primitives in Terra 0.22 have new feature `run` method. https://github.com/Qiskit/qiskit-terra/pull/8382
This PR makes Aer 0.11 compatible with both Terra 0.21 and 0.22.

Primitives support Terra 0.22 (run method)

---

qiskit_aer/primitives/estimator.py
qiskit_aer/primitives/sampler.py

This reverts commit 788e2c31c8d2fc1787d142bad01cd8c8a296e7f5.
Terra 0.22's feature #1578 should be included in Aer 0.12, not 0.11.

Revert "Primitives support Terra 0.22 (#1578)"

---

src/controllers/aer_controller.hpp

Corrected an English grammar error in error message
Not terribly important, but there it is!

Correct English grammar error

---

README.md

Since we're moving to remove Qiskit Aer from the metapackage, we should update our documentation to reflect that as well.

Update pip install command to reference qiskit-aer

---

qiskit_aer/primitives/sampler.py
releasenotes/notes/sampler-cache-78f916cedb0c5421.yaml
test/terra/primitives/test_sampler.py

Sampler caches transpiled circuits

---

releasenotes/notes/support_terra_primitive_022-8852b784608bcdcb.yaml

#1598 missed its release note. This complements it.
This adds a release note for Primitive support.

add release note for #1598 that supports Primitive of Terra 0.22

---

qiskit_aer/primitives/sampler.py
releasenotes/notes/sampler-counts-90e5aaabccdc415b.yaml
test/terra/primitives/test_sampler.py

Fix SamplerResult num_clbits

---

releasenotes/notes/fix_test_aer_statevector-8fed972e1581d937.yaml
test/terra/states/test_aer_statevector.py

Fix test case for AerStatevector caused by the latest Terra

Fix test_aer_statevector

---

releasenotes/notes/fix-ndarray-contiguity-e903d0fda4744100.yaml

This PR is to add a release note for #1685.

Add release note for #1685

---

qiskit_aer/primitives/estimator.py
test/terra/primitives/test_estimator.py

I realized that raising error here is API breaking. This PR changes it to warning.

Fix AerError in Estimator to warn

---

qiskit_aer/backends/aerbackend.py
test/terra/backends/test_parameterized_qobj.py

https://github.com/Qiskit/qiskit-aer/pull/1717#issuecomment-1432595770
Sorry, this PR does not affect quantum kernel benchmark because conditional branches do not go in this improvement.
However, this PR improves VQE.
My simple benchmark for UCCSD ansatz:

[perf] improve _convert_circuit_binds

---

.github/workflows/build.yml
pyproject.toml
releasenotes/notes/use_conan_1.x-f12570e2cfc8bb26.yaml
requirements-dev.txt

This is just to check CI is correctly working.

Pin the version of conan with 1.X to work around API changes in conan 2.0

---

releasenotes/add-aer-densitymatrix-959c261c954fa60e.yaml

Remove a release note (which was for 0.12.0 release) in an invalid location.
Essentially equivalent content is already incorporated in #1739.

Remove a release note in an invalid location

---

src/controllers/aer_controller.hpp

Build in broken since c052d07f71758b02d26259237ca600ddfaa31788
Fix compilation issues to build binary with MPI.

Fix MPI build break

---

qiskit_aer/backends/backend_utils.py
qiskit_aer/backends/qasm_simulator.py
releasenotes/notes/enhancement_ecr_for_stabilizer_simulator-00110a1b39d35054.yaml
src/simulators/stabilizer/stabilizer_state.hpp
test/terra/backends/aer_simulator/test_cliffords.py
test/terra/reference/ref_2q_clifford.py

fixes #1883 
Implemented ecr gate for aer_stabilizer_simulator.

Implemented ecr for stabilizer simulator.

---

.github/workflows/docs.yml
releasenotes/notes/fix_matplotlib_dependency-5b8ba26da6a98e3a.yaml

Fix the version of matplotlib required by seaborn
changed from <3.3.0 to >= 3.3.0

Fix matplotlib version

---

src/simulators/statevector/statevector_state.hpp

`Supported` was misspelled in the method doc for `apply_gate`. This PR aims to update this spelling.

Update misspelling apply_gate method doc

---

.github/workflows/tests.yml
tox.ini

This PR fixes test failure of Doc and Tutorials, test-json-input
removed `--` from wheel option

Fix build failure of tests

---

releasenotes/notes/fix_batch_shots-837c066d8b993a2d.yaml
src/simulators/batch_shots_executor.hpp

This is fix for GPU batched execution. 
checking return value from `apply_batched_op` function was wrong

Fix GPU batched execution

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/docs-publish.yml
.github/workflows/docs.yml
.github/workflows/tests.yml
.github/workflows/unit-tests-latest-qiskit.yml

Similar to https://github.com/Qiskit/qiskit-ibm-runtime/pull/1439, following my recent PR #2101 I noticed several warnings in the CI for deprecated actions in the workflows so I opened a PR to update them.

Update deprecated actions in workflows

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/docs-publish.yml
.github/workflows/docs.yml
.github/workflows/tests.yml
pyproject.toml

upgrade github actions for macos_arm64 and windows
Upgrading Python version from 3.8 to 3.10 except for docs/tutorials.
Using `macos-latest` for `arm64` and `macos-13` for others.

Fix CI failures

---

qiskit_aer/backends/aerbackend.py
releasenotes/notes/fix_issue2084-632a829da1a8dfc5.yaml
test/terra/primitives/test_sampler.py

This is fix for #2084 
`backend.set_max_qubits` was not implemented correctly when backend._target is None (max number of qubits should be set before transpile if `AerSimulator()` is initialized without any parameters)

Fix issue 2084 again

---

.pylintrc
constraints.txt
qiskit_aer/backends/aer_compiler.py
qiskit_aer/backends/aer_simulator.py
qiskit_aer/backends/aerbackend.py
qiskit_aer/backends/qasm_simulator.py
qiskit_aer/backends/statevector_simulator.py
qiskit_aer/backends/unitary_simulator.py
qiskit_aer/jobs/aerjobset.py
qiskit_aer/noise/errors/quantum_error.py
qiskit_aer/noise/noise_model.py
qiskit_aer/primitives/estimator.py
qiskit_aer/version.py
requirements-dev.txt
test/terra/backends/aer_simulator/test_fusion.py
test/terra/states/test_aer_densitymatrix.py
test/terra/states/test_aer_statevector.py
tox.ini

- Updates pylint version to the same one pinned in qiskit 
- Fixes linting errors and pylint config with updated version.

Update pylint version

---

.github/workflows/tests.yml

`pip check` is reverted in this PR which was removed in #2200.

run `pip check` again in macos CI

---

.github/workflows/deploy.yml

Add wildcard

---

.github/workflows/deploy.yml
pyproject.toml
tools/install_rust.sh

Revert cibuildwheel to 2.19.2

---

qiskit_aer/noise/noise_model.py

The noise_model.from_backend method should support both backend v1 and v2 for compatibility with pre-2.0 qiskit versions.
I ran the qiskit unit test suite with 1.4.1 and this PR installed and tests ran without issues.

Update noise model for compatibility with  Qiskit 1.4.x and 2.x

---

setup.py

add python-dateutil as requirement
